### ISSUE TITLE
Type Quantity is defined as Float, but some functions return Integers

### ISSUE THREAD

**Issue by tubedude** [bitwalker/timex#102]
Looking at the [Time Module](https://github.com/bitwalker/timex/blob/master/lib/time/time.ex) the quantity type is defined as [`@type quantity :: float`](https://github.com/bitwalker/timex/blob/master/lib/time/time.ex#L10).
But some functions such as [`to_usecs/1`](https://github.com/bitwalker/timex/blob/master/lib/time/time.ex#L10) or [`to_usecs/2`] (https://github.com/bitwalker/timex/blob/master/lib/time/time.ex#L64-L65) will only return `Integers`.

Should we change the definition of quantity to `Number`or should we change the functions to always return a `Float`?

**Comment by bitwalker** [comment]
It would probably be more appropriate to stop using `quantity` and instead use `integer` or `float` where appropriate. I have an issue to fix in the Time module anyway, so I can make this another one of my TODOs. I'll leave this open until that's merged. Thanks for spotting that!

**Comment by tubedude** [comment]
@bitwalker I was considering working on documentation of the Time module as well: adding tests and [better error messages](https://github.com/tubedude/timex/blob/time_tests/lib/time/time.ex#L208) by adding a [Timex.Time.Exceptions](https://github.com/tubedude/timex/blob/time_tests/lib/time/exceptions.ex).

I sent you a message on Elixir Slack.

**Comment by bitwalker** [comment]
@tubedude Just an FYI, but feel free to open issues on the tracker for discussion, enhancements, feature additions and the like. It's easier to keep track of the history and context around things like that over time :).
