### ISSUE TITLE
RFC: Add support for milliseconds to `Date.from`

### ISSUE THREAD

**Issue by stoft** [bitwalker/timex#111]
Many systems/applications represent Unix time/epoch as milliseconds (any system using java.sql.Timestamp for example), not seconds. Adding milliseconds as an option would be a simple convenience to avoid having to take an extra step through `Time.from` first:

```elixir
msecs |> Time.from(:msecs) |> Date.from(:timestamp)
```

Would become:
```elixir
Date.from(msecs, :msecs)
```

**Comment by bitwalker** [comment]
@stoft Sure that seems like a good request to remain compatible with Unix timestamps coming from those systems, I'll get it added :)

**Comment by stoft** [comment]
:smile:
