### ISSUE TITLE
Time wrong (after my macbook slept)

### ISSUE THREAD

**Issue by YayConnolly** [bitwalker/timex#112]
Here are some relevant lines from my iex session (with the latest release, 1.0.0-rc3) after waking my macbook. Was working fine yesterday. The time reported by :calendar is correct.
```
iex(16)> :calendar.local_time
{{2015, 12, 8}, {7, 39, 9}}

iex(17)> :calendar.universal_time
{{2015, 12, 8}, {15, 39, 15}}

iex(18)> Timex.Date.now
%Timex.DateTime{calendar: :gregorian, day: 8, hour: 3, minute: 1, month: 12,
 ms: 693, second: 43,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}

iex(19)> Timex.Date.now("PST")
%Timex.DateTime{calendar: :gregorian, day: 7, hour: 19, minute: 2, month: 12,
 ms: 809, second: 6,
 timezone: %Timex.TimezoneInfo{abbreviation: "PST",
  from: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}, full_name: "America/Dawson",
  offset_std: 0, offset_utc: -480,
  until: {:sunday, {{2016, 3, 13}, {2, 0, 0}}}}, year: 2015}

iex(20)> Timex.Date.local
%Timex.DateTime{calendar: :gregorian, day: 7, hour: 19, minute: 2, month: 12,
 ms: 865, second: 13,
 timezone: %Timex.TimezoneInfo{abbreviation: "PST",
  from: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}, full_name: "America/Los_Angeles",
  offset_std: 0, offset_utc: -480,
  until: {:sunday, {{2016, 3, 13}, {2, 0, 0}}}}, year: 2015}

iex(21)> :calendar.local_time
{{2015, 12, 8}, {7, 40, 9}}

iex(22)> :calendar.universal_time
{{2015, 12, 8}, {15, 40, 16}}
```

**Comment by YayConnolly** [comment]
I'm planning to use this workaround to get the correct Timex.DateTime in PST:
`:calendar.universal_time |> Timex.Date.from("PST")`

**Comment by bitwalker** [comment]
I'm really glad you discovered this! Timex was using `:erlang.system_time` instead of `:os.system_time`, the difference being of course that `:erlang.system_time` is the VM's system time, not the OS, so sleeping suspends the clock until it catches up.

**Comment by bitwalker** [comment]
The fix is in master by the way, I'll push a new release soon.

**Comment by YayConnolly** [comment]
Awesome, that was quick! Thank you for all your work on this library :+1:

**Comment by YayConnolly** [comment]
Also want to make sure you don't miss the second issue regarding Timex.Date.from/2 (converting from erlang time into a timezone directly)
