### ISSUE TITLE
Difference in years with the diff function

### ISSUE THREAD

**Issue by JustMikey** [bitwalker/timex#117]
I don't know if it's expected or it's a bug but `Date.diff` function when used with years just returns (year2 - year1) so even if there is one day difference between dates (31.12.2015 and 01.01.2016), it will return 1. 
Wouldn't it be better to check the actual dates and use logic as in  *difference in days / 365* (I know it's way too simplified, but it shows the point)

**Comment by bitwalker** [comment]
Definitely a bug! Thanks for reporting, I'll take a look and get a fix for this pushed.

**Comment by bitwalker** [comment]
Question: currently, `Date.diff` returns an integer value. Presumably, the result of your example should be 0, is that what you expect? Are you expecting a fractional value? My feeling is that it should return an integer, and thus 0 for your example, but I just want to confirm that's what you originally expected.

**Comment by JustMikey** [comment]
Yeah, I expected it to be 0. I think it should work with years exactly as it works with, let's say, hours, where the logic seems to be something like `(difference_in_seconds / 60) |> Float.floor |> round`.

**Comment by bitwalker** [comment]
Pushed a fix to master, should have a new release out soon!

**Comment by JustMikey** [comment]
I am afraid this fix can cause some other problems:

1) If we want to get difference in months between 01.01.2016 and 31.01.2016, it will return 1, I am not sure but I think the expected value would be 0 because it's the same month.

2) Also, I am not sure, but there may be a problem with calculating difference in years when leap years are in play.  For example, it will return 1 for dates: 29.02.2012 and 28.02.2013, when I believe there will be a one year difference only between 29.02.2012 and 01.03.2013.

This is all just my opinion so I may miss something here. But I think you should consider using this formula from [here](https://support.microsoft.com/en-us/kb/214134) (it's for Excel but the logic is clear) for months:

    IF(DAY(LDate)>=DAY(EDate),0,-1)+(YEAR(LDate)-YEAR(EDate))*12+MONTH(LDate)-MONTH(EDate)

and I am not sure how to go about the years.

**Comment by bitwalker** [comment]
I'll review the logic for that formula for addressing the lack of precision in 1. I have a TODO to review both implementations because as you've pointed out, they are not precise, but handling the edge cases is non-trivial, and I wanted to at least get something less broken than what was there before. I'll reopen this to track it though.

**Comment by JustMikey** [comment]
Yeah I understand, thank you.

**Comment by bitwalker** [comment]
Rolling this into 2.0, should be released tomorrow.

**Comment by bitwalker** [comment]
Fixed diffing of weeks, months, years, and added diffing by calendar weeks as well. Closing this for now, feel free to reopen it if you find issues in 2.x when I release it sometime today (or tomorrow morning).
