### ISSUE TITLE
Error in time comparison

### ISSUE THREAD

**Issue by rafal-radziszewski** [bitwalker/timex#118]
On our system we noticed, that time comparisons on Timex are currently wrong. Snippet:

```elixir
iex(kingschat@coreos1.appunite.net)10> msg.created_at
%Timex.DateTime{calendar: :gregorian, day: 4, hour: 9, minute: 47, month: 2,
 ms: 609.0, second: 31,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}
iex(kingschat@coreos1.appunite.net)11> cs.last_read
%Timex.DateTime{calendar: :gregorian, day: 4, hour: 9, minute: 47, month: 2,
 ms: 628.0, second: 22,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}
iex(kingschat@coreos1.appunite.net)12> msg.created_at > cs.last_read
false
```

If I had to guess, milliseconds have higher priority than seconds.

**Comment by JustMikey** [comment]
My wild guess would be that you're just comparing two maps and since `ms` is apparently gets compared before the `second` (alphabetical order I'd guess), thus you get this result since 609.0 < 628.0.

But that's just my guess, I may be wrong.

**Comment by bitwalker** [comment]
@rafal-radziszewski As @JustMikey has pointed out, you are actually comparing two maps, not two DateTimes when using the comparison operators. You have to use `Date.compare/2`.
