### ISSUE TITLE
l10n support via gettext

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/timex#125]
I want to make formatting/parsing locale-aware, so I plan on looking up the locale data and using gettext to implement it, and modifying the API to take a locale, as well as setting a default locale via configuration.

- [x] Obtain translations
- [ ] Add support for detecting locale
- [ ] Add API support for specifying locale
- [x] Add configuration support for setting default locale

**Comment by keichan34** [comment]
@bitwalker I've been looking over this to see what it'll be like when it's time to translate (planning on submitting a Japanese translation), but one problem I noticed is that in the `relative_time` and `units` domains, `dngettext` isn't being used for strings that have plural forms, like `in %{n} day`, `in %{n} days`, etc.

I can put together a PR for this in the next day or so if you'd like, but it'll require a few changes to the po / pots. Not knowing Russian, I wouldn't know how to do it, but I can give it my best shot and someone who actually knows the language can correct it :smile:

**Comment by bitwalker** [comment]
Hey! I'd love that! The localization stuff is still a work in progress for sure, for one thing, the Russian forms for numbers of things have more than single and plural forms, there is the concept of few vs many and occasionally rules like "x every year, but y on decades only". I know Russian decently enough to handle the translation, but finding a system which works for complex rules like that is my current challenge. Perhaps taking on the Japanese translation will give you some ideas?

**Comment by bitwalker** [comment]
Closing this, as the support has been merged, as have several locales. Thanks everyone for helping!
