### ISSUE TITLE
Expand test suite to include property-based testing

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/timex#126]
I want to use [ExCheck](https://github.com/parroty/excheck) to add QuickCheck-style tests for the full API, so that I can expose any lurking bugs.

Part of this effort is also attempting to achieve 100% test coverage, which is in progress, but will help validate that there are no untested code paths.
- [x] Evaluate ExCheck
- [ ] Determine what properties are testable with ExCheck
- [ ] Write test suite of property-based tests
- [ ] Get to 100% test coverage

**Comment by zacck** [comment]
Hey I'm keen to help on this,  I think I can start working on bumping up the test coverage

**Comment by mkorszun** [comment]
@bitwalker wanted to catch up on this initiative. Is anything happening around this topis (property based test). We have a WIP branch, where we have started introducing some property tests for functions we know and use -> https://github.com/vorce/timex/tree/property_based_tests.

We have decided to use [`StreamData`](https://github.com/whatyouhide/stream_data). We plan to propose a PR very soon.

Any thoughts about that?

**Comment by bitwalker** [comment]
@mkorszun A PR for that would be great! I generally prefer `proper` or `eqc`, but I'm willing to give StreamData a go - tests can always be ported to another tool if desired.

**Comment by fenollp** [comment]
@mkorszun any progress on this? Thanks

**Comment by mkorszun** [comment]
@fenollp https://github.com/bitwalker/timex/pull/480

**Comment by bitwalker** [comment]
Property testing via StreamData was merged in 3.6.1, so closing this for now
