### ISSUE TITLE
Upgrading From 1.0.0 (timex_ecto 0.7.0) to 2.1.0 (1.0.1)

### ISSUE THREAD

**Issue by baoist** [bitwalker/timex#131]
### Steps to reproduce

- `Timex.set(%Timex.Date{}, month: Timex.month_to_num(month), year: year)`,
  `Repo.update(changeset)`
- "January", 2012

### Description of issue

- What are the expected results?
When attempting to create/update a `Timex.Ecto.Date` field I get the following error:
```
** (CaseClauseError) no case clause matching: {{2020, 1, 1}, {0, 0, 0}}
       (ecto) lib/ecto/query/planner.ex:29: anonymous fn/6 in Ecto.Query.Planner.fields/4
     (stdlib) lists.erl:1262: :lists.foldl/3
       (ecto) lib/ecto/query/planner.ex:21: Ecto.Query.Planner.fields/4
       (ecto) lib/ecto/repo/schema.ex:449: Ecto.Repo.Schema.dump_changes/5
       (ecto) lib/ecto/repo/schema.ex:146: anonymous fn/11 in Ecto.Repo.Schema.do_update/4
       (ecto) lib/ecto/repo/schema.ex:477: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/9
       (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
       (ecto) lib/ecto/adapters/sql.ex:582: Ecto.Adapters.SQL.transaction/8
       (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.transaction/3
     (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
        (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
        (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
        (iex) lib/iex/evaluator.ex:108: IEx.Evaluator.eval/4
        (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.loop/3
        (iex) lib/iex/evaluator.ex:18: IEx.Evaluator.init/3
```

I've updated to the most recent `timex` and `timex_ecto` (at the time 2.1.0, and 1.0.1, respectively).

Note: I'm running ecto 1.1.3; is `2.0.0-beta` required?

**Comment by bitwalker** [comment]
I'll take a look ASAP, thanks for reporting!

**Comment by bitwalker** [comment]
I've pushed a new release 1.0.2 of timex_ecto with the bugfix for this. It was a stupid issue, I definitely need a proper test suite for timex_ecto :/

**Comment by baoist** [comment]
Thanks for getting this out so quickly!

That resolves one issue, but it comes up with another:
```bash
** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.DateTime.encode_date/1
lib/ecto/adapters/postgres/datetime.ex:36: Ecto.Adapters.Postgres.DateTime.encode_date({{0, 1, 1}, {0, 0, 0}})
```

I think that `postgres/datetime.ex` maybe doesn't like the `{{y, m, d}, {h, m, s}}` format that `Timex.to_erlang_datetime` outputs (refer to: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/postgres/datetime.ex#L36).

Around https://github.com/bitwalker/timex_ecto/blob/master/lib/types/date.ex#L54, could this be a possible solution:
```elixir
  def dump(%Date{} = date) do
    {ymd, _} = Timex.to_erlang_datetime(date)
    {:ok, ymd}
  end
```

My apologies if I'm misunderstanding the nature of the issue.

**Comment by bitwalker** [comment]
@baoist Ok, this time I spent extra time actually roundtripping all the types to the database and back a few different ways. New release is 1.0.3. Should be solid now!
