### ISSUE TITLE
How do you use Timex.Ecto.* as column default value?

### ISSUE THREAD

**Issue by ibizaman** [bitwalker/timex#132]
How would you define a default value for a `Timex.Ecto.*` column? I tried the obvious, using `Timex.Date.from` but it does not work when using `mix ecto.migrate` because `:tzdata` is not yet started.

```elixir
defmodule WPI.Postgres.MyTable do
    use Ecto.Schema
    schema "my_table" do
        field :my_date, Timex.Ecto.DateTimeWithTimezone, default: Timex.Date.from({{2099, 1, 1}, {0, 0, 0}}, "UTC")
    end
end
```

```
== Compilation error on file lib/database/postgres.ex ==
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
    lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
    lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
    lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
    lib/tzdata.ex:61: Tzdata.zone_exists?/1
    lib/timezone/timezone.ex:91: Timex.Timezone.get/2
    lib/date/date.ex:321: Timex.Date.from/2
    lib/database/postgres.ex:223: (module)
```

Is there a workaround or is this not achievable?
I am still using timex 1.X.X.

**Comment by bitwalker** [comment]
Add `Application.ensure_all_started(:timex)` at the top of the module, but you can also use an Erlang datetime time as the default, I believe, that might be worth trying first, that or constructing the DateTime struct manually, especially since it's UTC, the default DateTime value is UTC, so you really just have to set the date fields.

Anyway, those are a few options :)

**Comment by ibizaman** [comment]
The erlang datetime struct does not work as default, I get:
```
** (ArgumentError) invalid default argument `{{2099, 1, 1}, {0, 0, 0}}` for field :my_date of type Timex.Ecto.DateTimeWithTimezone
```

Although creating the datetime struct directly works great:
```elixir
%Timex.DateTime{day: 1, month: 1, year: 2099}
```

Thanks!
