### ISSUE TITLE
How to use Timex.Ecto.DateTime as column type in schema migration easily?

### ISSUE THREAD

**Issue by ibizaman** [bitwalker/timex#133]
Here is what I have came up with to handle migrations with a table having a Timex.Ecto.* column type. This setup works fine although I would like to get rid of the separate `ALTER` statement.

```elixir
defmodule WPI.Repo.Migrations.MyTable do
  use Ecto.Migration

  def up do
    execute """
    CREATE TYPE datetimetz AS (
    dt timestamptz,
    tz varchar
    );
    """

    create table(:my_table) do
      # add :my_date, :datetimez
    end

    execute """
    ALTER TABLE my_table ADD COLUMN my_date datetimetz;
    """
  end

  def down do
    drop table(:my_table)

    execute """
    DROP TYPE datetimetz;
    """
  end
end
```

Do you have an idea how to do that?

**Comment by bitwalker** [comment]
Let me do some experimenting and get back to you, I think we can find a better way

**Comment by ibizaman** [comment]
Awesome, thanks!

**Comment by bitwalker** [comment]
I'm going to close this for now. I haven't been able to find a cleaner way, though I haven't dived too deep into it. If you would like to reopen it, feel free to do so on the timex_ecto issue tracker, since it's likely to get more discussion there.

**Comment by ibizaman** [comment]
Too bad but thanks for the update.
