### ISSUE TITLE
:erlang.system_time vs :os.system_time (Time.now)

### ISSUE THREAD

**Issue by sikanhe** [bitwalker/timex#134]
I think the :erlang version is preferred over the :os version in erlang 18, because :erlang supports time warp and is a monotonically increasing time (:os is not).

**Comment by bitwalker** [comment]
That's probably a good change to make, I also need to update the measure/elapsed functions to use `monotonic_time` instead of the current diffing method. I'll add that to my TODO for the next release.

**Comment by sikanhe** [comment]
After looking into some past issues, i saw the reason why you changed it to :os was because: 

https://github.com/bitwalker/timex/issues/112

**Comment by bitwalker** [comment]
Ah, sure enough, I knew I had chosen it for a reason, but going back and reviewing the documentation for this issue didn't jog my memory. I still need to make changes for measure/elapsed, so I'll keep this open as a reminder, but after reviewing that issue, I think I'll keep the current usage of `:os.system_time`, unless there is an alternate solution for #112 that allows us to both resolve the sleep issue while getting to use `:erlang.system_time`

**Comment by sikanhe** [comment]
perhaps by using some kind of configuration, allow you to set it differently in :dev and :prod

**Comment by bitwalker** [comment]
That is an option - the default config could use `:os.system_time`, and it could be overridden to allow the use of `:erlang.system_time`, something like:

```elixir
config :timex,
  system_time_source: :os # or :erlang
```

**Comment by sikanhe** [comment]
ah! thanks

**Comment by bitwalker** [comment]
I've added this (though not yet committed to master), so it will show up in a future release. I'll close this for now, but I'll update this thread when a release is pushed and we can reopen it if there are issues.
