### ISSUE TITLE
No match of right hand side value: [] for Timex.Timezone.convert/2

### ISSUE THREAD

**Issue by burmajam** [bitwalker/timex#139]
### Steps to reproduce

- API function called
Timex.Timezone.convert tx, tz
timex version: 0.19.5

- Arguments provided
dt = {{2016, 3, 27}, {1, 10, 0}}
tx = Timex.Date.from(dt, "UTC")
tz = "Europe/Vienna"

### Description of issue

- What are the expected results?
UTC (Time Zone)           Sunday, 27 March 2016, 01:10:00 UTC  UTC         
Vienna (Austria - Vienna) Sunday, 27 March 2016, 03:10:00 CEST UTC+2 hours 

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

http://www.timeanddate.com/worldclock/converted.html?iso=20160327T0110&p1=0&p2=259

**Comment by bitwalker** [comment]
This is fixed in 2.x (and likely in 1.x as well). Can you upgrade?

**Comment by burmajam** [comment]
I've tried it with 2.1.4 and works as expected. Thanks!
