### ISSUE TITLE
Problem with Timex.shift

### ISSUE THREAD

**Issue by JustMikey** [bitwalker/timex#141]
So I have a phoenix model where I use Timex.Ecto.Datetime for some of my columns.

Now when I update one of those column setting the column's value to `Timex.DateTime.now` and then retrieve the record and get that column's value, I get a struct 

`#<DateTime(2016-03-27T16:59:54Z)>`

that turns into a map like this: 

```
%{calendar: :gregorian, day: 27, hour: 16, millisecond: 608000, minute: 59,
  month: 3, second: 54, timezone: #<Timezone(UTC - UTC (+00:00))>, year: 2016}
```

Now the problem appears when I try to shift this retrieved struct like this: 

`user.my_datetime_column |> Timex.DateTime.shift([minutes: 40])`

when I get the following error: 

```
(FunctionClauseError) no function clause matching in Timex.Timezone.resolve/2
    (timex) lib/timezone/timezone.ex:182: Timex.Timezone.resolve("UTC", {{2016, 3, 27}, {17, 39, 54, 608000}})
```

Now if I do this:

`Timex.DateTIme.now |> Timex.DateTime.shift([minutes: 40])``

I get what's expected: 

`#<DateTime(2016-03-27T17:49:25Z)>`

I think the problem is with the `millisecond` map key that has a value with 6 digits because it works if I remove the last 3 zeros:

`%{user.my_datetime_column | millisecond: 608} |> Timex.DateTime.shift([minutes: 40])`

I may have made some foolish mistake and apologize if so, but if seems like a bug to me.

**Comment by bitwalker** [comment]
Turns out the problem is actually in `timex_ecto`, it's getting microseconds from the Ecto type, and not converting that to milliseconds, and the guard clause for resolve ensures that the date/time provided is within valid ranges - of which milliseconds is 0-999. I'll get a fix pushed shortly into `timex_ecto` and update this thread.

**Comment by JustMikey** [comment]
Oh I see, thank you very much;

**Comment by bitwalker** [comment]
Both timex and time_ecto have updated versions on hex now. You'll need both in order for the fix to work - timex was only allowing integer milliseconds, and rather than lose the precision, I've updated it to allow fractional milliseconds.
