### ISSUE TITLE
diff in weeks seems to be off

### ISSUE THREAD

**Issue by frpaulas** [bitwalker/timex#152]
### Steps to reproduce

- d1 = Timex.date {2016, 3, 27}
- d2 = Timex.date {2016, 4, 3}
- Timex.diff d1, d2, :days # => 7
- Timex.diff d1, d2, :weeks # => 0

### Description of issue

- if the diff in days is 7 I would expect the diff in weeks to be 1

**Comment by bitwalker** [comment]
Fixed in master
