### ISSUE TITLE
Parsing am/pm time ignores {AM} when it's before {h12}

### ISSUE THREAD

**Issue by Ygreg** [bitwalker/timex#156]
### Steps to reproduce

```
iex(1)> Timex.Parse.DateTime.Parser.parse!("3 pm", "{h12} {AM}")                                                
#<DateTime(0-01-01T15:00:00Z)>
iex(2)> Timex.Parse.DateTime.Parser.parse!("pm 3", "{AM} {h12}")
#<DateTime(0-01-01T03:00:00Z)>
```

### Description of issue

Both lines should output `#<DateTime(0-01-01T15:00:00Z)>`

This happens because:
-First Timex.Parse.DateTime.Parser.update_date call with the :AM token expects hour to already be set and modifies it
-Second Timex.Parse.DateTime.Parser.update_date call with the :hous12 token sets the hour, discarding the value from the call with the :AM token

**Comment by bitwalker** [comment]
Pending a rebase of your PR, I'll close this out :)

**Comment by Ygreg** [comment]
Sorry, but my PR was for another bug, which has been already fixed in master. This is another issue I found at the same time. I've described what happens, but I don't know how to fix this one.
