### ISSUE TITLE
Timex.DateTime.now/1 raises when DateTime is ambiguous

### ISSUE THREAD

**Issue by Theemuts** [bitwalker/timex#157]
### Steps to reproduce

To reproduce, set the system clock to a datetime which will occur twice in a specific timezone (e.g. 2016-10-30 02:00:00 in Europe/Amsterdam. If you call Timex.DateTime.now("Europe/Amsterdam"), it will raise due to a missing key.

### Description of issue

This function shoud return a Timex.AmbiguousDateTime-struct to reflect the fact that the datetime is ambiguous in this timezone.

**Comment by bitwalker** [comment]
Good find! I'll get this addressed in the next release. Thanks!

**Comment by bitwalker** [comment]
Fixed in master
