### ISSUE TITLE
Different output from documentation - intended?

### ISSUE THREAD

**Issue by arthurcolle** [bitwalker/timex#161]
### Steps to reproduce

- Date.today, DateTime.today
- none

### Description of issue

- According to the documentation provided [here](https://hexdocs.pm/timex/Timex.html), the expected output, for example on an iex session, should be:
```
> date = Date.today
%Date{year: 2016, month: 2, day: 29}

> datetime = DateTime.today
%DateTime{year: 2016, month: 2, day: 29,
          hour: 12, minute: 30, second: 30, millisecond: 120, timezone: %TimezoneInfo{...}}
```
However, for me using Elixir 1.3.0-dev it actually is:
```
iex(18)> date = Date.today
#<Date(2016-04-24)>
iex(19)> datetime = DateTime.today
#<DateTime(2016-04-24T00:00:00Z)>
```
Is there a way (for experimentation) to be able to see all of the fields, as the documentation shows?

**Comment by g33kidd** [comment]
Yeah I keep getting the same thing, has anybody figured this out?

**Comment by bitwalker** [comment]
This output is just how those structs are represented with the Inspect protocol implementation. If you run `inspect Date.today, structs: false`, it will show the raw struct. The data is still the same :), I just need to update the docs to reflect the new output.
