### ISSUE TITLE
Timex parse RFC1123z example in doc returns error

### ISSUE THREAD

**Issue by sphaso** [bitwalker/timex#182]
### Steps to reproduce
```
iex> Timex.parse("Tue, 06 Mar 2013 01:25:19 +0200", "{RFC1123z}")
iex> {:error, "Expected `Z`, but found `+` at line 1, column 27."}
iex> Timex.parse("Tue, 06 Mar 2013 01:25:19 Z0200", "{RFC1123z}")
iex> {:error, "Expected end of input at line 1, column 27"}
```
Did the accepted format change? if so, what is it?
The first statement is from the documentation: https://hexdocs.pm/timex/parsing.html

**Comment by bitwalker** [comment]
Yeah the docs are slightly incorrect, I'll get those updated. `{RFC1123z}` expects only zulu-formatted timestamps (i.e. `Tue, 06 Mar 2013 01:25:19 Z`). Use `{RFC1123}` with offset-formatted timestamps (i.e. `Tue, 06 Mar 2013 01:25:19 +0200`).

**Comment by denispeplin** [comment]
Docs are still incorrect here: https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html

**Comment by bitwalker** [comment]
Fixed. Thanks!
