### ISSUE TITLE
DateTime relative formatter broken for -1 minute

### ISSUE THREAD

**Issue by eproxus** [bitwalker/timex#184]
### Steps to reproduce

```elixir
iex(1)> Timex.Format.DateTime.Formatters.Relative.format!(Timex.shift(Timex.DateTime.now, minutes: -1), "{relative}")
"-1 minutes ago"
```

### Description of issue

The relative datetime formatters returns `"-1 minutes ago"` instead of `"1 minute ago"`.

**Comment by cjhowe** [comment]
Might I suggest a pull request with a failing test?

**Comment by eproxus** [comment]
Thanks for the fix!
