### ISSUE TITLE
Changelog updates

### ISSUE THREAD

**Issue by PragTob** [bitwalker/timex#188]
Seems like the changelog hasn't been updated since 2.1.3 - would love to have those intermediate updates to make upgrading less of an adventure in the unknown :)

I know it's a bit tedious to maintain, I think it's really helpful for users to look at and also cool from a maintainer's point of view to see what was accomplished :)

PS: Thanks for timex :)

**Comment by bitwalker** [comment]
Indeed I have slacked off on this, I've got an update for 1.3 coming very soon, I'll update the changelog as part of that release :)

**Comment by PragTob** [comment]
Cool, thanks!

Personally, I like to add things to the Changelog as updates come in (i.e. after merging a PR or so) - keeps it updated all the time and nice overview of the release :)

**Comment by bitwalker** [comment]
I've updated the changelog along with the newest release, I'll keep it up to date from now on :)

**Comment by PragTob** [comment]
Thank you, that's great to hear!

**Comment by LostKobrakai** [comment]
@bitwalker seems like the changelog is currently out of date. would be nice if you could append the latest changes.
