### ISSUE TITLE
Argument Error when using DateTime

### ISSUE THREAD

**Issue by fatfalcon** [bitwalker/timex#191]
On a Mac. 

```
iex> use Timex
iex> %DateTime{} = datetime = Timex.datetime({{2016,3,13}, {1,0,0}}, "America/Chicago")

** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
             lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
             lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
             lib/tzdata/release_reader.ex:5: Tzdata.ReleaseReader.zone_list/0
             lib/tzdata/release_reader.ex:22: Tzdata.ReleaseReader.periods_for_zone_or_link/1
             lib/tzdata.ex:137: Tzdata.periods/1
             lib/tzdata.ex:216: Tzdata.periods_for_time/3
             lib/timezone/timezone.ex:193: Timex.Timezone.resolve/3
             lib/timezone/timezone.ex:230: Timex.Timezone.resolve/3
             lib/timezone/timezone.ex:251: Timex.Timezone.resolve/3
             lib/timex.ex:53: Timex.datetime/2
```

**Comment by fatfalcon** [comment]
Maybe this needs to be tracked over at TZData? - https://github.com/lau/tzdata?

**Comment by fatfalcon** [comment]
Found the problem; those encountering the same problem must add tzdata to the list of applications as suggested here - https://github.com/lau/tzdata/issues/5

**Comment by bitwalker** [comment]
You can just add `:timex` to the applications list, as it already has `:tzdata` in its own applications list.

**Comment by mjsisley** [comment]
After adding timex v3.0 to dependencies and applications, I am getting the same error when running this line and others involving timezones.

**Comment by bitwalker** [comment]
@mjsisley Are you calling any Timex APIs at compile-time? If you have `:timex` in your application's list, then the only way the error above could be produced is if you are calling Timex at compile-time without first calling `Application.ensure_all_started(:timex)`
