### ISSUE TITLE
Parse ISO 8601 duration string

### ISSUE THREAD

**Issue by mfclarke** [bitwalker/timex#205]
Is there some way of parsing an ISO 8601 formatted duration string to a ```Duration``` object? It would be great to parse "P46Y7M20DT20H11M10.458638S" for example, into seconds. I had a good trawl through the docs but could only find parsing strings to ```Time```s, ```Date```s or ```DateTime```s.

Essentially I'm looking for the inverse of ```Duration.to_string``` ([docs](https://hexdocs.pm/timex/Timex.Duration.html#to_string/1))

**Comment by bitwalker** [comment]
I just realized there is no parser for that. I just wrote one up, but I need to test it before pushing it to master. I'll follow up later today.

**Comment by mfclarke** [comment]
Great! Many thanks @bitwalker

**Comment by bitwalker** [comment]
This is in master now, you can use it with `Duration.parse(str)`. There is also support for custom duration parsers, but for now ISO-8601 is the only one baked in. Let me know if you run into any bugs and I'll take a look! Once you've given me the thumbs up, I'll cut a new release.

**Comment by mfclarke** [comment]
Works perfectly for me. Thanks again @bitwalker!
