### ISSUE TITLE
Timex.shift fails with :timezone not found in: #<DateTime(...)>

### ISSUE THREAD

**Issue by philipgiuliani** [bitwalker/timex#206]
Hi! I am  currently migrating my app to Elixir 1.3 and Timex 3.0.
Im trying to add milliseconds to a DateTime. Adding seconds, days is working fine.

### Steps to reproduce

![bildschirmfoto 2016-08-08 um 18 55 29](https://cloud.githubusercontent.com/assets/5446019/17488476/e6440c08-5d99-11e6-8b0f-dda11913b7fc.png)

```elixir
datetime = DateTime.utc_now
Timex.shift(datetime, milliseconds: 100)
```

**Comment by bitwalker** [comment]
Just pushed a fix for this, I'll get a new release cut today, after some other changes I'm working on are ready. Thanks for the report!

**Comment by philipgiuliani** [comment]
Oh thank you very much!! :) This was really fast.
