### ISSUE TITLE
`Timex.diff/3` documentation is incorrect

### ISSUE THREAD

**Issue by wleborgne** [bitwalker/timex#209]
### Steps to reproduce
Elixir 1.3.2, Erlang/OTP 19
Timex 3.0.6

From `iex`:
```elixir
iex(9)> a = "2016-01-01T01:23:45Z" |> Timex.parse!("{ISO:Extended:Z}")
#<DateTime(2016-01-01T01:23:45Z Etc/UTC)>
iex(10)> b = "2016-01-01T02:34:56Z" |> Timex.parse!("{ISO:Extended:Z}")
#<DateTime(2016-01-01T02:34:56Z Etc/UTC)>
iex(11)> Timex.diff(a, b, :seconds)
-4271
iex(12)> Timex.diff(b, a, :seconds)
4271
```
### Description of issue

According to the documentation at https://github.com/bitwalker/timex/blob/master/lib/timex.ex#L832, `Timex.diff/3` will always return a non-negative integer. However, the function is delegated to `Timex.Comparable`, where `diff/3` will return a positive or negative value depending on whether or not the first argument is after the second.

**Comment by bitwalker** [comment]
Ah yes, the docs are outdated here, I'll get that updated right away. Thanks!
