### ISSUE TITLE
`Timex.Duration.scale/2` doesn't work with floats

### ISSUE THREAD

**Issue by obrok** [bitwalker/timex#210]
### Steps to reproduce

```elixir
iex(76)> Duration.scale(Duration.parse!("P10D10M"), 0.5)
** (ArithmeticError) bad argument in arithmetic expression
    (timex) lib/time/duration.ex:548: Timex.Duration.divmod/3
    (timex) lib/time/duration.ex:542: Timex.Duration.normalize/1
```

### Description of issue

This is pretty natural and could return ~ `#<Duration(P5M5D)>`. Is this behaviour by design or a bug? If a bug I could try my hand at a fix later this week.

**Comment by bitwalker** [comment]
Could you give master a look and let me know if you run into anything broken or weird?

**Comment by obrok** [comment]
master does work in my project, including places where I previously had 

```elixir
 x |> Duration.to_seconds() |> Kernel.*(y) |> round() |> Duration.from_seconds()
```

and can now just use `Duration.scale`. It seems it fails some travis checks though :P

**Comment by bitwalker** [comment]
Yeah, it's because excoveralls doesn't work on Erlang 19 :/, still waiting on the fix for that. In any case, I'll get a new release of timex pushed with this fix :)

**Comment by bitwalker** [comment]
Pushed 3.0.8 to hex

**Comment by obrok** [comment]
Thanks for the quick fix
