### ISSUE TITLE
Documentation page is 404

### ISSUE THREAD

**Issue by andybeak** [bitwalker/timex#212]
### Steps to reproduce

Visit https://github.com/bitwalker/timex/blob/master/docs/Formatting.md
Click on link to http://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.StrftimeFormatter.html labelled as Timex.Format.DateTime.Formatters.Strftime

### Description of issue
I'm trying to work out how to convert a Twitter API style date response "Sat Aug 27 10:26:52 +0000 2016" but can't find a list of standard formatters or how to build this up manually with symbols in :strftime

**Comment by bitwalker** [comment]
You should use [hexdocs](https://hexdocs.pm/timex).

[Here](https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Strftime.html) are the module docs for the strftime formatter you were looking for, and [here](https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html) is the default formatter, which is more flexible, in case stftime doesn't work for you.
