### ISSUE TITLE
Timex.from_unix does not support negative values

### ISSUE THREAD

**Issue by fire** [bitwalker/timex#213]
### Steps to reproduce

```elixir
iex(13)> Timex.from_unix(-62135769600)
** (FunctionClauseError) no function clause matching in DateTime.from_unix/2
    (elixir) lib/calendar.ex:1010: DateTime.from_unix(-62135769600, :seconds)
    (elixir) lib/calendar.ex:1052: DateTime.from_unix!/
```

### Description of issue

- What are the expected results?
Some year from around 0001.

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

https://github.com/elixir-ecto/postgrex/blob/66a4c8cffb492968a4ea9da108d8fb555839f5a8/lib/postgrex/extensions/calendar.ex#L76

**Comment by bitwalker** [comment]
This will need to be solved in Elixir's standard library rather than Timex specifically, since `Timex.from_unix` ultimately calls `DateTime.from_unix/2`, but I can work on the PR for it. In the meantime I can probably add a workaround to Timex's implementation.

**Comment by fire** [comment]
I would like a PR for this. Thank you.

**Comment by fishcakez** [comment]
This is in Elixir master https://github.com/elixir-lang/elixir/commit/5c08f86145343afa8b4d1653f84d2a2762affb44 and has been back ported for next 1.3 release.

**Comment by bitwalker** [comment]
Thanks @fishcakez!
