### ISSUE TITLE
Convert string Datetime to milliseconds

### ISSUE THREAD

**Issue by mvbaffa** [bitwalker/timex#227]
- Timex.parse(startDay, "%Y-%m-%d %H:%M:%S", :strftime)
- startDay = "2016-08-03 00:00:00"

How can I parse and convert the date "2016-08-03 00:00:00" to milliseconds like java.util.Date.getTime() 
Thanks

**Comment by jadlr** [comment]
like so:

```elixir 
iex(1)> startDay = "2016-08-03 00:00:00"                             
"2016-08-03 00:00:00"
iex(2)> date = Timex.parse!(startDay, "%Y-%m-%d %H:%M:%S", :strftime)
~N[2016-08-03 00:00:00]
iex(3)> DateTime.to_unix(Timex.to_datetime(date), :milliseconds)   
```
not the the result of the parse is a NaiveDateTime. You need to specify a timezone in order to get unix millis from that. The code above assumes UTC

**Comment by mvbaffa** [comment]
Thanks

Em 25/10/2016 14:20, "Jonas Adler" <notifications@github.com> escreveu:
