### ISSUE TITLE
gettext 0.12.x breaks Timex 3.x

### ISSUE THREAD

**Issue by james-vanlommel-zefr** [bitwalker/timex#228]
### Steps to reproduce

- API function called: `Timex.format!()`
- Arguments provided: `"{Mfull} {D} {YYYY}, {h12}:{m}{am}"`

### Description of issue

Timex is calling a private gettext API, which changed in the past two days with their 0.12.0 release.

### Stacktrace

(I'm on Timex 3.1.0)

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Timex.Gettext.lgettext/3 is undefined or private. Did you mean one of:

      * lgettext/4

        (timex) Timex.Gettext.lgettext("en", "months", "January")
        (timex) lib/l10n/translator.ex:156: Timex.Translator.get_domain_text/3
        (timex) lib/l10n/translator.ex:103: Timex.Translator.get_months/1
        (timex) lib/format/datetime/formatter.ex:441: Timex.Format.DateTime.Formatter.format_token/6
        (timex) lib/format/datetime/formatters/default.ex:182: Timex.Format.DateTime.Formatters.Default.do_format/4
        (timex) lib/format/datetime/formatter.ex:54: Timex.Format.DateTime.Formatter.lformat!/4
```

### Temp Resolution

Forcing my mix.deps to use the `0.11.0` version made this error go away.

**Comment by max-vogler** [comment]
Thanks for the temp solution @james-vanlommel-zefr! Indeed using `{:gettext, "0.11.0"},` in `mix.exs` works.

**Comment by max-vogler** [comment]
Furthermore, I have had good experience with only allowing higher patch versions, not minor versions (e.g. by using `:gettext, "~> 0.10.0"` instead of `:gettext, "~> 0.10"`). Especially, because many libraries introduce breaking changes in minor version changes of `0.*`. This might be an idea for this repo as well? @bitwalker
