### ISSUE TITLE
No specs in time module

### ISSUE THREAD

**Issue by nmnowak** [bitwalker/timex#23]
The date module seems to be really well speced out but I don't see any specs in the time module. Is there any reason for this or is it just something that is waiting to be done, maybe by me?

**Comment by X4lldux** [comment]
Plus there are some missing type information in some modules.

**Comment by bitwalker** [comment]
I've manually merged @gabrielelana's PR adding some types/specs, so I'll close this for now, as fleshing out documentation is part of #9
