### ISSUE TITLE
Timex 2.2.1 fails to format RFC1123 dates

### ISSUE THREAD

**Issue by mspanc** [bitwalker/timex#236]
### Steps to reproduce

Under timex 2.2.1, which is the last supported on Elixir 1.2, the following fails:

(record is some Ecto model)

- record.updated_at |> Ecto.DateTime.to_iso8601 |> Timex.parse!("{ISO:Extended}") |> Timex.format!("{RFC1123}")

Causes UndefinedFunctionError because it internally calls

- Timex.Gettext.lgettext
- `["en", "months", "Jan"]`

but gettext 0.12.1 that is used in 2.2.1 requires 4 arguments to lgettext.

**Comment by bitwalker** [comment]
If you lock the version of gettext at 0.11, this issue won't affect you with 2.2.1. 3.x already has this fixed, and it affects 2.2.1 because it's version restriction on gettext is very loose.
