### ISSUE TITLE
`Date.to_secs` does not take timezone into account.

### ISSUE THREAD

**Issue by ideal-knee** [bitwalker/timex#24]
Example symptom:

```
iex(38)> Date.convert(Date.from({2014, 11, 17}, "CST"), :secs)
1416182400                                                    
iex(39)> Date.convert(Date.from({2014, 11, 17}), :secs)       
1416182400                                                    
```

Current implementation of `Date.to_secs` (https://github.com/bitwalker/timex/blob/b7b7a79aa1c20cab94e08365d772002038fb4480/lib/date/date.ex#L377-L379) is not handling timezone before sending off to Erlang.

**Comment by bbense** [comment]
Looking at the code this probably is also a bug in to_days, although you'd need to look a lot harder to find a specific example.

**Comment by bbense** [comment]
I made a first pass at this problem by writing a test that fails and a simple solution, however it seems to be causing problems in other code. Date.to_secs is fundamental to many other functions and I may be running into chicken and egg issues. 

The code is here if you want to look, will keep plugging away as I have time.

https://github.com/bbense/timex/tree/Date_to_secs_bug_24

**Comment by bbense** [comment]
This patch resolves the bug. 

https://github.com/bitwalker/timex/pull/32

No changes to the Timezone code were required, but other methods in Date required some reworking to adapt to the changes in to_secs.

**Comment by bitwalker** [comment]
Merged and published as part of the 0.13.3 release. Thanks! Do you happen to know which functions specifically required rework? I can dig through and find out, but if you know offhand, then I can open a new issue to track that.

**Comment by bbense** [comment]
Date.shift and Date.compare

**Comment by bbense** [comment]
Oh and Date.diff

**Comment by bitwalker** [comment]
@bbense Excellent, thank you sir! Might be a good place to start if you are looking for another issue to tackle. I'll cc you on it when I create it, you can decide whether you want to work that one or not.
