### ISSUE TITLE
AmbiguousDateTime values are off during Daylight Savings transition

### ISSUE THREAD

**Issue by kyleaa** [bitwalker/timex#240]
### Description of issue

During the transition from PDT to PST `Timezone.convert` returns `AmbiguousDateTime` structs. The documentation recommends using the `:after` value, but it seems that neither of these values are consistently reliable.

The first time we hit 1AM the `:before` value looks correct, but the `:after` value is 2.5 days in the past.
```
Timex.from_unix(1478419201) |> Timex.Timezone.convert("America/Los_Angeles")
#<Ambiguous(#<DateTime(2016-11-06T01:00:01-07:00 America/Los_Angeles)> ~ #<DateTime(2016-11-03T13:00:01-08:00 America/Los_Angeles)>)>
```

once the time flips and we hit 1AM again the `:before` value is now 2.5 days in the future.
```
Timex.from_unix(1478422801) |> Timex.Timezone.convert("America/Los_Angeles")
#<Ambiguous(#<DateTime(2016-11-08T13:00:01-07:00 America/Los_Angeles)> ~ #<DateTime(2016-11-06T01:00:01-08:00 America/Los_Angeles)>)>
```

**Comment by bitwalker** [comment]
I suspect I know what's going on here, definitely a bug. I'll get a fix pushed ASAP. Thanks for the report!

**Comment by bitwalker** [comment]
This appears to be working on master correctly, could you confirm? Here's the results I see:

```
iex(3)> Timex.from_unix(1478419201) |> Timezone.convert("America/Los_Angeles")
#<Ambiguous(#<DateTime(2016-11-06T01:00:01-07:00 America/Los_Angeles)> ~ #<DateTime(2016-11-06T00:00:01-08:00 America/Los_Angeles)>)>
iex(4)> Timex.from_unix(1478422801) |> Timezone.convert("America/Los_Angeles")
#<Ambiguous(#<DateTime(2016-11-06T02:00:01-07:00 America/Los_Angeles)> ~ #<DateTime(2016-11-06T01:00:01-08:00 America/Los_Angeles)>)>
```

**Comment by bitwalker** [comment]
I've pushed master as 3.1.4 as well.

**Comment by kyleaa** [comment]
Yep, its working. Sorry for the false alarm 🙁. I was on 3.0.8 as my `mix.exs` requirement was too restrictive. Thanks for taking a look.

**Comment by bitwalker** [comment]
No problem, sorry you got bit by this!

**Comment by hpopp** [comment]
Worth noting here: I had the exact same issue last night with `Timex.local` calls during the transition from CDT to CST, causing string formatting to fail. It should be good now right?

**Comment by bitwalker** [comment]
@hpopp You'll need to make sure you've updated to the latest release. The bug which was present in 3.0.8 was fixed in a recent release, but I haven't traced back to find out which one specifically.

**Comment by hpopp** [comment]
Awesome, thanks

**Comment by kyleaa** [comment]
I walked back through the versions, looks like 3.1 fixes it. 

- Kyle Anderson
