### ISSUE TITLE
Timex.timezone/2 does not handle all floating point offsets properly

### ISSUE THREAD

**Issue by techgaun** [bitwalker/timex#244]
### Steps to reproduce

I am trying to convert offset sent from javascript client to a valid timezone so that I can use `Timex.now |> Timex.beginning_of_day` based on the client timezone connecting to the backend.

Few things I tried hoping would work:

```
# Does not work
iex > %Timex.TimezoneInfo{offset_utc: 21600} |> Timex.Timezone.get
#<TimezoneInfo(Etc/UTC - UTC (+00:00:00))>

# works only for integer offset
iex> Timex.Timezone.name_of(6)
"Etc/GMT-6"

iex> Timex.Timezone.name_of(5.75)          
{:error, {:invalid_timezone, 5.75}}

# gives timezone name
iex> Timex.Timezone.name_of("GMT+5.75")
"Etc/GMT+5.75"

# but can not use the same thing to get current time in that timezone
iex> Timex.Timezone.name_of("GMT+5.75") |> Timex.now
{:error, {:invalid_timezone, {:error, {:invalid_timezone, "Etc/GMT+5.75"}}}}
```

Following code works as expected:

```
iex> Timex.timezone(-6, Timex.now) |> Timex.now
#<DateTime(2016-11-16T20:52:44.899281-06:00 Etc/GMT+6)>
```

Following code gives error:

```
iex> Timex.timezone(5.75, Timex.now) |> Timex.now
{:error,
 {:invalid_timezone,
  {:error, {:invalid_timezone, {:error, {:invalid_timezone, 5.75}}}}}}
```

I was hoping I could just pass values such as 5.75 (GMT+5:45 for Kathmandu/Nepal) and it would handle it properly.

I also suspect there might be alternative API but I can not seem to figure it out.

**Comment by bitwalker** [comment]
I've added this in master, along with a function to define your own timezones, `Timex.TimezoneInfo.create/6`. I would recommend using that instead of fractional offsets, as it will give you a timezone info struct you can use for conversions, and you can ensure it's precise, as there is inherent flaws with a floating point offset as you can imagine.
