### ISSUE TITLE
Bug with `{0ss}` format directive

### ISSUE THREAD

**Issue by azhi** [bitwalker/timex#252]
### Steps to reproduce

- Take any valid time
- Format it using format string with fractional seconds and 0 padding
- Parse resulting string back

E.g.

```elixir
with format_str = "{YYYY}-{0M}-{0D}T{0h24}:{0m}:{0s}{0ss}{Z:}" do
  Timex.now()
  |> Timex.format!(format_str)
  |> Timex.parse!(format_str)
end
```

### Description of issue

Expected result: Format/parse cycle should return original time unchanged. Instead, parsing fails with "Expected `fractional second` at line x, column y."

### Detailed description

I've spent some time investigating this, and found that `{ss}` directive is working differently depending on whether it is `format` or `parse`.

On `format`, `{0ss}` seems to mean `".#{fractional_seconds}"`, e.g.

`Timex.now() |> Timex.format!("{0ss}")` equals `".306845"`.

On `parse`, `{0ss}` seems to mean `"#{seconds}.#{fractional_seconds}"`, e.g.

`"05.123456" |> Timex.parse!("{0ss}")` equals `~N[0000-01-01 00:00:05.123456]`.

PS: [docs](https://github.com/bitwalker/timex/blob/367717a/lib/format/datetime/formatters/default.ex#L59) seems to state that `{0ss}` should work like in `parse`.

**Comment by bitwalker** [comment]
I'll take a look shortly, thanks for the report!

**Comment by bitwalker** [comment]
This is now fixed in master, please let me know if you find any other issues!
