### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by soarpatriot** [bitwalker/timex#253]
### i18n Chiese support

Timex.from_now

### Description of issue
I am a user of Timex from China and there is no  Chinese support in i18n. 
Could you add Chinese support?  or  Could I commit a PR(MR) for this issue?

- What are the expected results?
add Chinese i18n support.

**Comment by bitwalker** [comment]
I'm happy to merge the translations if you submit a PR for them :)

**Comment by bitwalker** [comment]
And merged :), thanks!
