### ISSUE TITLE
Fix formatting of negative and overflowing durations

### ISSUE THREAD

**Issue by mbramson** [bitwalker/timex#259]
### Steps to reproduce

Formatting of durations with negative components error or output nonsensical values. Some examples:

```
iex(1)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: 0, microseconds: 0})
"PT-1000000S"
iex(2)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: -1, microseconds: 0})
"PT-1000001S"
iex(3)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: -1, seconds: -1, microseconds: -1})
** (FunctionClauseError) no function clause matching in Timex.Format.Duration.Formatters.Default.get_fractional_seconds/3
    (timex) lib/format/duration/formatters/default.ex:93: Timex.Format.Duration.Formatters.Default.get_fractional_seconds(-1000001, -1, [])
    (timex) lib/format/duration/formatters/default.ex:51: Timex.Format.Duration.Formatters.Default.lformat/2
iex(4)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: 1, seconds: 1, microseconds: -1})
** (FunctionClauseError) no function clause matching in Timex.Format.Duration.Formatters.Default.get_fractional_seconds/3
    (timex) lib/format/duration/formatters/default.ex:93: Timex.Format.Duration.Formatters.Default.get_fractional_seconds(40, -1, [minutes: 46, hours: 13, days: 11])
    (timex) lib/format/duration/formatters/default.ex:51: Timex.Format.Duration.Formatters.Default.lformat/2
```

There is also at least one other buggy case in this function not involving negative numbers:
```
iex(1)> Timex.Format.Duration.Formatter.format(%Timex.Duration{megaseconds: 0, seconds: 1, microseconds: 1000000})
"PT3.0S"
```
(I'd expect `"PT2.0S"` or `"PT2S"`)
**NOTE: The above example when microseconds exceeds 1000000 has been fixed by https://github.com/bitwalker/timex/pull/260**

### Description of issue

I am not entirely sure what the expected output would be in these cases, but it definitely shouldn't be throwing an error. @bitwalker might be able to provide more guidance on what the expected output looks like.

**Comment by bitwalker** [comment]
I think at least in the case of the ISO formatter, it should be the representation of the absolute value of the duration, in other words, the negative and positive representations of a given duration would have the same output using that formatter (because they represent the same volume of time, and the format defined in the spec does not distinguish between past and present, at least as far as I can tell). The humanized formatter should probably follow suit for the same reasons, but there's no specific reason why it couldn't distinguish between past and present in the output.

**Comment by slavakisel** [comment]
@bitwalker I can prepare a fix for this issue if you don't mind

**Comment by bitwalker** [comment]
@slavakisel That would be most welcome!
