### ISSUE TITLE
Formatting of zero duration returns empty string

### ISSUE THREAD

**Issue by slavakisel** [bitwalker/timex#266]
### Steps to reproduce

Default formatter returns just "P":
```
iex> Timex.Duration.zero |> Timex.Format.Duration.Formatters.Default.format
"P"
```

Humanized formatter returns just empty string:
```
iex> Timex.Duration.zero |> Timex.Format.Duration.Formatters.Humanized.format
""
```

### Description of issue

This probably should be more informative. I also took a look at specification and ISO-8601 mandates at least one element for a zero duration (see 4.4.3.2.c - page 21):

> If the number of years, months, days, hours, minutes or seconds in any of these expressions equals zero, the number and the corresponding designator may be absent; however, at least one number and its designator shall be present.

**Comment by uesteibar** [comment]
Hi here! I've been looking around for a chance to contribute to the project, so if it's fine with you guys I'll open PR taking care of this issue.

Thanks! :)
