### ISSUE TITLE
Timex.format! will go into an infinite loop if called with invalid date tuple

### ISSUE THREAD

**Issue by manukall** [bitwalker/timex#268]
I came across this via code like

```elixir
some_var 
|> Timex.to_date 
|> Timex.format!("{ISOdate}")
```

When `somevar` is something that cannot be cast to a date, (e.g. `nil`), this will result in an endless loop.
`Timex.to_date` will return `{:error, :invalid_date}`, which leads to https://github.com/bitwalker/timex/blob/master/lib/format/datetime/formatter.ex#L49 being called over and over again.

In my opinion, an error should be raised here. Maybe we could introduce `Timex.to_naive_datetime!/1` and use that instead of `Timex.to_naive_datetime/1`, so it raises instead of returning the tuple.

**Comment by nulian** [comment]
Think that problem is introduced in 3.1.6 with the fallback_to_any protocol part.
Also had infinite loop in our app when updated to the latest version while in 3.1.5 it works just fine.

**Comment by bitwalker** [comment]
This fix is released in 3.1.8

**Comment by manukall** [comment]
@bitwalker thanks!
