### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by jschoch** [bitwalker/timex#27]
use Timex
ts = "2014-12-23T13:29:50+0000"
date = DateFormat.parse(ts,"{ISO}")
DateFormat.format!(Date.shift(date,days: 1),"{ISO}")

*** stack smashing detected ***: /usr/local/lib/erlang/erts-6.2/bin/beam terminated
   Segmentation fault (core dumped)

**Comment by bitwalker** [comment]
Fixed as part of the commit for #39

**Comment by mosic** [comment]
@bitwalker I can replicate this with the latest release (0.19.2):

```
iex(1)> 02 Sep 07:43:18 - info: compiled 3 files into 2 files in 941ms
use Timex
nil
iex(2)> ts = "2014-12-23T13:29:50+0000"
"2014-12-23T13:29:50+0000"
iex(3)> date = DateFormat.parse(ts,"{ISO}")
{:ok,
 %Timex.DateTime{calendar: :gregorian, day: 23, hour: 13, minute: 29, month: 12,
  ms: 0, second: 50,
  timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
   full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2014}}
iex(4)> DateFormat.format!(Date.shift(date,days: 1),"{ISO}")
*** stack smashing detected ***: /home/mosic/kerl/17_5/erts-6.4/bin/beam.smp terminated
```

Any suggestions?

**Comment by bitwalker** [comment]
This is happening because you are passing `date` which is `{:ok, %DateTime{...}}` to `Date.shift`, and it is not being properly handled by timex. I'll address handling the invalid argument, but if you replace `date = DateFormat...` with `{:ok, date} = DateFormat...` you'll be good to go :)

**Comment by mosic** [comment]
@bitwalker Great, thanks!
