### ISSUE TITLE
Corner case when shifting +1 months Jan 29 

### ISSUE THREAD

**Issue by marcelog** [bitwalker/timex#271]
Hello,

This is a corner case, and I'm not sure there's a workaround for it, but I'd still like to know your thoughts about it. 

Today is Jan 29th 2017. This year, February has 28 days. When adding +1 months to Jan 29, the result is Feb 28, but `Timex.diff` reports 0 months of difference.

So when doing this:

```elixir
iex(1)> {:ok, d1} = Timex.parse "Sun, 29 Jan 2017 Etc/UTC", "%a, %d %b %Y %Z", :strftime
{:ok, #<DateTime(2017-01-29T00:00:00Z Etc/UTC)>}
iex(2)> d2 = Timex.shift d1, months: 1
#<DateTime(2017-02-28T00:00:00Z Etc/UTC)>
iex(7)> Timex.diff d1, d2, :months
0
```

The result seems to be inconsistent. We're adding +1 months through the API but later on we have a diff of 0 months.

What are your thoughts?

Thanks in advance.

Best regards,

**Comment by bitwalker** [comment]
Indeed this did seem to be wrong - unfortunately I did a poor job of documenting the old diffing algorithm for months, so it's not clear to me why it was the way it was, but I've resorted to a simpler algorithm which will do a naive integer division of the diff in days by 30 (we have to make an assumption about the length of a month, and 30 is a reasonable average). I believe the old algorithm attempted to be more accurate, but clearly had a flaw handling that edge case, so I've thrown it out in favor of the simpler implementation.

**Comment by marcelog** [comment]
Thank you very much @bitwalker 👍
