### ISSUE TITLE
Timex.from_now/1 is inaccurate if the timezone is non-UTC

### ISSUE THREAD

**Issue by jbrowning** [bitwalker/timex#277]
`Timex.from_now/1` is inaccurate if the timezone is non-UTC. This is unexpected because they should both be the same moment in time.

`Timex.from_now/2` **is** accurate if the given `reference_date` time is in the same timezone as the `datetime`

### Steps to reproduce

```
iex(1)> utc_now = Timex.now
#<DateTime(2017-02-08T22:23:02.035812Z Etc/UTC)>
iex(2)> converted_now = Timex.Timezone.convert(time, "America/Indianapolis")
#<DateTime(2017-02-08T17:23:02.035812-05:00 America/Indianapolis)>
iex(3)> Timex.from_now utc_now
"1 minute ago"
iex(4)> Timex.from_now converted_now
"10 hours ago"
```

### Description of issue

- What are the expected results?

For both times to return the same `from_now` result.

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

Just the same time in UTC vs another timezone. :wink:

**Comment by bitwalker** [comment]
The reason is that `from_now/1` uses UTC as it's reference point, but the input date/time is not converted to UTC prior to diffing. Thanks for the report! I'll get this fixed ASAP.

**Comment by jbrowning** [comment]
Yep, figured. Thank you so very much for the quick reply and fix. 🙌
