### ISSUE TITLE
Possible bug in local timezone lookups (Windows)

### ISSUE THREAD

**Issue by mjaric** [bitwalker/timex#28]
This is rather feature request than a bug :)

If I include this as dependency in my project under Windows Operating system I'm getting error 
" Unsupported operating system!"

** (exit) an exception was raised:
    ** (RuntimeError) Unsupported operating system!
        lib/timezone/timezone_local.ex:29: Timex.Timezone.Local.lookup/1
        lib/timezone/timezone.ex:656: Timex.Timezone.local/0
        lib/date/date.ex:145: Timex.Date.local/0

**Comment by bitwalker** [comment]
Interesting, it should work on Windows. That error pops up if it's unable to find the local timezone. What version of Windows are you running? I can test on my work machine when I get a chance.

**Comment by mjaric** [comment]
It is Windows 8.1. I took some time to identify what is issue and apparently erlang is returning tuple {:win32, :nt} instead of {:nt}. So OS detection do not work for Win 8.1. Below is case wich is throwing exception
```
case :os.type() do
      {:unix, :darwin} -> localtz(:osx, date)
      {:unix, _}       -> localtz(:unix, date)
      {:nt}            -> localtz(:win, date)
      _                -> raise "Unsupported operating system!"
    end
```
But, even if fix it it opens more issues, which could be due erlan/elixir version.

Let say I change above case and add one above _
`{:win32, :nt}    -> localtz(:win, date)`

the method localtz will try to open windows registry, but `:win32reg.open(:local_machine)` will return {:error, :einval} , then instead of opening :local_machine I put there [] as parameter...

But each fix lead to other issue. I'm not sure what was  in that registry key in previous Win versions, but looks like values are not the same or some erlang change was added in version I'm using. So below is change I added in localtz function

```
# Get the locally configured timezone on Windows systems
  @local_tz_key '\\hklm\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation'
  @sys_tz_key   '\\hklm\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones'
  # We ignore the reference date here, since there is no way to lookup
  # transition times for historical/future dates
  defp localtz(:win, _date) do
    # Windows has many of it's own unique time zone names, which can
    # also be translated to the OS's language.
    {:ok, handle} = :win32reg.open([])
    :ok           = :win32reg.change_key(handle, @local_tz_key)
    {:ok, values} = :win32reg.values(handle)
```

and this module works so when I call Timex.Date.local I'm getting error
```
** (ArgumentError) argument error
    :erlang.iolist_to_binary({'TimeZoneKeyName', 'Central Europe Standard Time'})
    lib/timezone/timezone_local.ex:96: Timex.Timezone.Local.localtz/2
    lib/timezone/timezone.ex:656: Timex.Timezone.local/0
    lib/date/date.ex:145: Timex.Date.local/0
    (elixir_timex) lib/mix/tasks/elixir_timex.start.ex:10: Mix.Tasks.Start.run/1
    (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:537: Enum.each/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2


```

**Comment by mjaric** [comment]
Update to above

I used Mix task to run code. It is something like this

```
defmodule Mix.Tasks.Start do
  use Mix.Task
  use Timex
  @shortdoc "Testing timex"
  #@recursive true

  
  def run(_args) do
    Mix.Task.run "app.start", []
    date = Date.local
    IO.inspect date
    IO.puts(DateFormat.format!(date, "{ISO}"))
  end
end
```

Now, when I change the last part I mentioned in localtz method to this
```
# Get the locally configured timezone on Windows systems
  @local_tz_key '\\hklm\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation'
  @sys_tz_key   '\\hklm\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones'
  # We ignore the reference date here, since there is no way to lookup
  # transition times for historical/future dates
  defp localtz(:win, _date) do
    # Windows has many of it's own unique time zone names, which can
    # also be translated to the OS's language.
    {:ok, handle} = :win32reg.open([])
    :ok           = :win32reg.change_key(handle, @local_tz_key)
    {:ok, values} = :win32reg.values(handle)
    if List.keymember?(values, 'TimeZoneKeyName', 0) do
      # Windows 7/Vista
      # On some systems the string value might be padded with excessive \0 bytes, trim them
      {_key, tz_name } = List.keyfind(values, 'TimeZoneKeyName', 0)
      tz_name
      |> IO.iodata_to_binary
      |> String.strip ?\0
```

I can get time, but timezone info still has error. If I inspect resulting time, I'm getting 

```
%Timex.DateTime{calendar: :gregorian, day: 10, hour: 10, minute: 35, month: 1, ms: 379, second: 41, timezone: {:error,  "No timezone found for: No timezone found for: Central Europe Standard Time"}, year: 2015}
```

Which causing all formatting functions to fail.

I hope this helps. I'm realy realy new to elixir and erlang so I will avoid this time to make pull request since I can't guarantee the fix would work for all scenarios.

**Comment by bitwalker** [comment]
Yeah, there is a map which converts Windows timezone names to Olson timezone names, you have to run the result of the lookup through that conversion before you'll be able to get the actual TimezoneInfo struct for the zone. There should be some code already there which does this, you'll have to consult the source though, I don't recall the specifics off the top of my head.

I've been out of town the past few days, I'm hoping to catch up on this and other issues starting today, so I can help sort out a fix soon.

**Comment by OnorioCatenacci** [comment]
Hi Paul,

I was doing a bit of digging on this issue too.  I haven't come up with a fix but I did find some stuff that I hoped might help.

  # Get the locally configured timezone on Windows systems
  @local_tz_key 'SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation'
  @sys_tz_key   'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones'
  # We ignore the reference date here, since there is no way to lookup
  # transition times for historical/future dates
  defp localtz(:win, _date) do
    # Windows has many of it's own unique time zone names, which can
    # also be translated to the OS's language.
    {:ok, handle} = :win32reg.open([:read])                      # A
    :ok           = :win32reg.change_key(handle, 'HKEY_LOCAL_MACHINE')  #B
    :ok           = :win32reg.change_key(handle, @local_tz_key)

On Windows 8.1 I had to add line A (this is with Elixir 1.0.3 and Erlang 17.4).  And line B would throw an error when I attempted to call it with the :local_machine atom but it works fine when I call it with HKEY_LOCAL_MACHINE.  I got that far but then there seem to be some issue with finding the @local_tz_key path once it gets there.  I can see the path just fine in regedit but win32reg simply refuses to see it.  When I manually list subkeys of HKLM, I get "Software" and nothing else.  And when I list subkeys of HKLM\Software I get an empty list.

I'd submit a pull request but I can't see much point in asking you to merge code that's only a little less broken. 

Hope this helps some Paul.  I'm going to keep digging on it as my time permits.

**Comment by bitwalker** [comment]
Hey guys, I'm out of the country until the 5th of April. I can dive into this then, or if you want to produce a PR that I can merge in the meantime, I can do that as soon as one is submitted. I'm putting the last few bug fixes into my new timezone code, so I'll address this there as well.

**Comment by OnorioCatenacci** [comment]
I've got an answer on the issue I was seeing so I may be able to make some progress on this.  If I make any headway I'll send along a PR if it's appropriate.

**Comment by bitwalker** [comment]
Could you folks pull master and test on your Windows boxen? I've tested on a Windows 10 machine, but I don't have anything older handy, and I'd like to confirm that things are working properly before closing this issue. Thanks!

**Comment by OnorioCatenacci** [comment]
Yes I will try this out.

**Comment by OnorioCatenacci** [comment]
Just tried it on my Win 8.1 box.  All the test ran without a failure.   I also tried out Timex within an iex session and everything seems to be working as expected.

**Comment by bitwalker** [comment]
@OnorioCatenacci That's great to hear, thanks for taking the time to test it!

Hopefully someone can test on a Win7 box, but if not at least we know we're in a good place going forward.

**Comment by bitwalker** [comment]
I'm going to close this for now in favor of more specific issues as they come up. If anyone is still encountering issues with local timezone lookups on Windows, please open a new issue with the details.
