### ISSUE TITLE
Interval with incorrect step leads to infinite cycle on enumerating

### ISSUE THREAD

**Issue by hedgesky** [bitwalker/timex#292]
Steps to reproduce:

```elixir
Interval.new(step: [month: 1]) |> Enum.count 
```

I guess this is due to lack of check in `Interval.has_recursion_ended?/3`:

```elixir
defp do_reduce({current_date, end_date, right_open, keywords}, {:cont, acc}, fun) do
  if has_recursion_ended?(current_date, end_date, right_open) do
    {:done, acc}
  else
    # here .shift returns {:error, {:unknown_shift_unit, :month}}
    # which is then passed to .has_recursion_ended? without a check
    next_date = Timex.shift(current_date, keywords)
    do_reduce({next_date, end_date, right_open, keywords}, fun.(current_date, acc), fun)
  end
end
```

Had hard time figuring this out; accidentally typing `month` instead of `months` drove me crazy.

I guess we can add the check to `Interval.new` and `Interval.with_step`, raising `FormatError` on incorrect steps. Can tackle this if suggested solution is acceptable.

**Comment by mbramson** [comment]
Looks like this happens because `Enum.count/1` uses the implementation of reduce, which for a right_open interval never ends. You can reproduce this with a reduce as well (and likely anything else in `Enum` that relies on the implementation of `Enum.reduce/3` for intervals with right_open of true.
