### ISSUE TITLE
Timex.max()

### ISSUE THREAD

**Issue by elpikel** [bitwalker/timex#294]
Can i add Timex.max() that will return December 31, 9999 ? I'm form .net and there you can find: https://msdn.microsoft.com/en-us/library/system.datetime.maxvalue(v=vs.100).aspx which can be useful.

**Comment by bitwalker** [comment]
Could you provide an example of where you would use it?

**Comment by mbramson** [comment]
Not arguing either way, but this value is actually at least supported by elixir itself in typespecs: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar/iso.ex#L19

**Comment by bitwalker** [comment]
I'm not saying it's an "invalid" date/time value, but rather where it's use fits in to code you would write with Timex. Comparisons already support the concept of "far future" and "far past" which are effectively maximum values (though they are really more like infinity/negative infinity). You can already create date/time values which represent a value of 9999/12/31, so a convenience function for that seems a bit unnecessary unless it's something that would be commonly used.
