### ISSUE TITLE
Timex.format on a time without a timezone does not return valid `ISO:Extended` string

### ISSUE THREAD

**Issue by sgtpepper43** [bitwalker/timex#297]
### Steps to reproduce

```elixir
dateTime = Timex.parse!("1/2/2015", "{M}/{D}/{YYYY}")

dateTime
|> Timex.format!("{ISO:Extended}")
|> Timex.parse("{ISO:Extended}")
# {:error, "Expected either Z or a valid timezone offset, but got ``"}
```

- API function called
Timex.format/Timex.parse
- Arguments provided
`"{ISO:Extended}"`

### Description of issue

When I format something into `{ISO:Extended}`, it doesn't create a proper ISO 8601 string (at least not according to `Timex.parse`). The reason given from `Timex.parse` is that the timezone is missing. I don't know what the best solution is, perhaps `format` could give an error if `ISO:Extended` (or any format with a timezone) is used when there is no time zone information.

- What are the expected results?
  - If `format` is successful with a specified `format_string`, I would expect that calling `parse` on the result with the _same_ `format_string` should also be successful.
    
    
    
     
This is coming from having to update some old code that was running on v2 of Timex, and the solution to my original was to use `ISO:Extended:Z`. I actually _really_ like the fact that you _don't_ assume the local timezone when parsing a date; for some reason in most time libraries parsing a timezone-less time into UTC without actually changing the time is practically impossible, and can only be done by manually adding `Z` to the end of the string.

**Comment by bitwalker** [comment]
The problem here is that you are attempting to format something with no timezone information using a timezone-aware format. You must tell the formatter to assume UTC with the `{ISO:Extended:Z}` directive, this will ensure the formatted date/time is in `UTC` and suffixed with the `Z` timezone designation.

**Comment by sgtpepper43** [comment]
Exactly, but shouldn't `format` return an error when you attempt to format something with no timezone using a timezone-aware format?

**Comment by bitwalker** [comment]
Yes it should be returning an error, I'll make sure it does in the next release.
