### ISSUE TITLE
Parsing with Strftime, flag behavior not working as expected

### ISSUE THREAD

**Issue by ddresselhaus** [bitwalker/timex#298]
So, I'm trying to parse this string:
```
"2017-04-05 15:34:37.348"
```

Using the strftime format:
```
Timex.parse("2017-04-05 15:34:37.348", "%Y-%m-%d %H:%M:%S.%f", :strftime)
{:ok, ~N[2017-04-05 15:34:37.000348]}
```

This is zero-padding on the left-side, returning .000348 microseconds, instead of .348000 microseconds.

In the code, the "-" flag is documented here:
https://github.com/bitwalker/timex/blob/a9c9cc6c185ee0b3e5be8f5dbc3b4711398efb65/lib/format/datetime/formatters/strftime.ex#L22
It seems like what I should be using to avoid the padding, but it returns the same results:
```
Timex.parse("2017-04-05 15:34:37.348", "%Y-%m-%d %H:%M:%S.%-f", :strftime)
{:ok, ~N[2017-04-05 15:34:37.000348]}
```
Any thoughts?

**Comment by bitwalker** [comment]
I know what's going on here, I'll get this fixed in the next release
