### ISSUE TITLE
RFC: Timex.equal? – Be explicit about comparison granularity

### ISSUE THREAD

**Issue by fpoehler** [bitwalker/timex#302]
Example

```
a = DateTime.from_naive! ~N[2017-04-26 08:08:08.123Z], "Etc/UTC"
b = DateTime.from_naive! ~N[2017-04-26 08:08:08.456Z], "Etc/UTC"
Elixir.Timex.equal?(a, b)
=> true    # ... shouldn't this be false?
           # a and b are obviously _not_ equal,
           # 123 milliseconds != 456 milliseconds!
```

According to the documentation, the arguments of `Timex.equal?` are equal (only) if they "represent the same moment in time", just as one would expect.

However, the implementation only does a comparison with a `:seconds` granularity, i.e. two `DateTime`s having the same calendar, timezone, date, hour, minute and second, but different milliseconds, are still equal as of `Timex.equal?`, even though in reality they are not *equal*, but at best *looking mostly equal*.

This was not the behaviour I did expect after I have read the docs. "The same moment in time" is not the same as "the same second". – It's "the same second, same millisecond, same nanosecond and so on, down to the smallest representable unit of time".

To remove that ambiguity, I would like to propose

* either to mention in the documentation that `equal?` does not consider the sub-second parts of a `DateTime`, and that users who need sub-second granularity can fallback on `Timex.compare(a, b) == 0` as an alternative
* or (even better) to make the granularity configurable in the code (and to reflect that in the documentation):
    ```
    def equal?(a, b, granularity \\ :seconds) do
      Comparable.compare(a, b, granularity) == 0
    end
    ```

Thanks for considering.

**Comment by bitwalker** [comment]
The latter of these two options is what should be there, I'll make sure this and the docs are updated. Thanks for the report!
