### ISSUE TITLE
GMT timezone

### ISSUE THREAD

**Issue by Linbubin** [bitwalker/timex#305]
I want to

```
iex(2)> Timex.now("Etc/GMT+8")
#<DateTime(2017-05-09T09:28:47.035192+08:00 Etc/GMT+8)>
```

but why show me

`#<DateTime(2017-05-08T17:28:47.035192-08:00 Etc/GMT+8)>`

Is there any simple way to get the results I expected?
Only set the time zone to GMT-8？

**Comment by bitwalker** [comment]
The `Etc/GMT*` zone names are reversed intentionally, i.e. `GMT+8` is actually GMT - 8 hours, and `GMT-8` is actually GMT + 8 hours. This is an issue with the Olson timezone database, not Timex, and is an unfortunate artifact of how wonky timezones are :(
