### ISSUE TITLE
[Question] Convert Ecto.DateTime to Timex.DateTime

### ISSUE THREAD

**Issue by vsmart** [bitwalker/timex#306]
Hi. 

Is there a way to convert an Ecto.DateTime to a Timex.DateTime and vice versa? 

I know it's possible to use Timex on Ecto using the `timex_ecto` plugin as explained  in [Using with Ecto](https://github.com/bitwalker/timex/blob/90f446a5a94d1a31d088deec860b51acbe2f6e0e/docs/Using%20with%20Ecto.md), but I'd love to use Timex for some date/time calculations without switching over the entire DB to Timex date types. 

Thank you for your work!

**Comment by bitwalker** [comment]
They are the same thing in recent versions of both :). Both Ecto 2 and Timex 3 use the native Elixir calendar types, including `DateTime`. You should be able to just take a `DateTime` from Ecto and pass it right to the Timex API with no issues!

**Comment by vsmart** [comment]
hey! thanks for the quick response.

I'm on ecto 2.1 and timex 3.1., so should be up to date as you mentioned.  Still, I am getting this error when trying to use the Ecto.DateTime in my Timex calculations. 

```Protocol.UndefinedError) protocol Timex.Comparable not implemented for #Ecto.DateTime<2012-01-01 00:00:00>``` on operations like `Timex.before?`, 
and the error `{:error, :invalid_date}` when trying to do `Timex.shift` or simply `Timex.day` with the same value.

Do you have any ideas what the problem could be? Thank you!

**Comment by bitwalker** [comment]
Ah, you're right, they are supposed to be used in Ecto 2.2, but that hasn't released yet. You should be able to pipe the Ecto DateTime through `Ecto.DateTime.dump/1` then `Timex.DateTime.Helpers.construct/1` and get an Elixir DateTime. I'm going to push a new release which can take care of the conversion for you as part of the Timex protocol

**Comment by vsmart** [comment]
great. that works. thank you!
