### ISSUE TITLE
how to get dates based on years and days

### ISSUE THREAD

**Issue by Linbubin** [bitwalker/timex#307]
I find function **day**:
```
iex> Timex.day(~D[2015-06-26])
177
```

but now, I want to find a function reversal the function **day**,
`Timex.get_day(year, day_num)`
it means
```
iex> Timex.get_day(2015, 177)
~D[2015-06-26]
```

Is there a ready-made method I haven't found?
Or who can give me some ideas to construct this function?

anyway, thanks!

**Comment by Linbubin** [comment]
I write a function maybe can help.

```
  def get_date(year, month \\ 1, num) do
    date = {year, month, num}
    num =
      cond do
        month in [1,3,5,7,8,10,12] -> num - 31
        month == 2 -> if Timex.is_leap?(year),do: num - 29,else: num - 28
        month in [4,6,9,11] -> num - 30
      end
    month = month + 1
    if num > 0 do
      get_nth_month(year,month,num)
    else
      date
    end
  end
```

You can improve it, add it to the method, and help someone else if they need it.
thanks!

**Comment by bitwalker** [comment]
Either `Timex.shift({<year>, 1, 1}, <day_num>)`, or `Timex.from_iso_day/2` should cover this case.
