### ISSUE TITLE
Some translations/locale aren't working

### ISSUE THREAD

**Issue by lebart** [bitwalker/timex#308]
Hello, 

Using Timex 3.1.13, some locale aren't working: 

```
Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> use Timex
Timex.Timezone
iex(2)> Timex.from_now(Timex.shift(DateTime.utc_now(), days: -2))
"2 days ago"
iex(3)> Timex.from_now(Timex.shift(DateTime.utc_now(), days: -2), "fr")
"2 days ago"
iex(4)> Timex.from_now(Timex.shift(DateTime.utc_now(), days: -2), "ru")
"2 дня назад"
iex(5)>
```

I was looking for the french translation, I didn't test for other languages.

**Comment by bitwalker** [comment]
When I run your second example, I get:

```elixir
iex(4)> Timex.from_now(Timex.shift(DateTime.utc_now(), days: -2), "fr")
"il y a 2 jours"
```
But I just double checked, and this because French wasn't added until 3.1.14 :)

**Comment by lebart** [comment]
Thanks! That makes sense! 

On hex.pm I didn't see 3.1.14 should I use the git repo in my mix conf instead?

**Comment by bitwalker** [comment]
I'll get 3.1.14 pushed up right away :)

**Comment by lebart** [comment]
hehe thanks a lot! :)

**Comment by bitwalker** [comment]
3.1.15 is up!
