### ISSUE TITLE
Strftime parser doesn't parse flags

### ISSUE THREAD

**Issue by mbaeuerle** [bitwalker/timex#312]
### Steps to reproduce

``` elixir
Timex.parse!("1/2/2017", "%-m/%-d/%Y", :strftime)
#=> ** (Timex.Parse.ParseError) Expected `2 digit month` at line 1, column 1.
#   (timex) lib/parse/datetime/parser.ex:96: Timex.Parse.DateTime.Parser.parse!/3
```

### Description of issue

- I expected that the modifiers and flags are also working when parsing

**Comment by bitwalker** [comment]
I've fixed this in master, it will go out in the next release. Thanks for the report!
