### ISSUE TITLE
Compiler warning in lib/timex.ex

### ISSUE THREAD

**Issue by dkln** [bitwalker/timex#316]
### Steps to reproduce

- Use Elixir 1.4.4 with Erlang 19
- Compile an Elixir project with Timex version 3.1.15

### Description of issue

Compiler shows warning in `lib/timex.ex' on line 979:

```
==> timex
Compiling 57 files (.ex)
warning: this clause cannot match because a previous clause at line 979 always matches
  lib/timex.ex:979
```

P.S.: Thanks for this awesome library! <3

**Comment by bitwalker** [comment]
Fixed in master. Thanks!
