### ISSUE TITLE
strftime formatter does not pad microseconds when fractional part is equal to zero

### ISSUE THREAD

**Issue by narkq** [bitwalker/timex#322]
### Steps to reproduce
```
iex(1)> Timex.to_datetime({2017, 1, 1}) |> Timex.format("%f", :strftime)
{:ok, "0"}
```
### Description of issue

Expected result: `{:ok, "000000"}`

For example, in Python:
```
>>> from datetime import datetime
>>> datetime.strftime(datetime(2017, 1, 1), '%f')
'000000'
```

**Comment by bitwalker** [comment]
Timex pads the fractional seconds based on the precision of the `microsecond` field of the date/time struct - when converting a Date to a DateTime like in your example, the precision is going to be 0 (IIRC), and so only a single digit will be printed. If instead you created a DateTime with a precision of 6, you would get all 6 digits in the formatted output.

**Comment by narkq** [comment]
Thank you for the clarification!

I created this issue because I've got the impression from [the docs](https://github.com/bitwalker/timex/blob/fd8916adb82266719d47cd6ef201b84eca9aabcc/lib/format/datetime/formatters/strftime.ex#L77) that `%f` directive is always padded with zeroes to 6 characters regardless of the flags and modifiers.

But still, the precision for some reason doesn't affect the formatting if the fractional part equals zero.
```
$ iex -S mix
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [lock-counting]

Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.Project.config() |> Keyword.get(:version)
"3.1.20"
iex(2)> t = Timex.parse!("2017-06-28 20:21:22.000000", "%F %T.%f", :strftime)
~N[2017-06-28 20:21:22.000000]
iex(3)> t.microsecond
{0, 6}
iex(4)> Timex.format!(t, "%f", :strftime)
"0"
```
In other cases, indeed, the width is determined by the precision, even if the width is specified in the format string.
```
iex(5)> Timex.to_datetime({2017, 6, 22}) |> Timex.format!("%06f", :strftime)
"0"
iex(6)> Timex.to_datetime({2017, 6, 22}) |> Map.put(:microsecond, {0, 3}) |> Timex.format!("%06f", :strftime)
"000"
```

**Comment by bitwalker** [comment]
Ah good catch! I'll ensure there are tests around that functionality, it should always obey the precision.

**Comment by narkq** [comment]
If so, is there a preferred way to modify precision, or `Map.update!(time, :microsecond, fn({us, _}) -> {us, 6} end)` is the way to go?

**Comment by narkq** [comment]
Although in my personal opinion width from the format string should have preference over precision.

**Comment by bitwalker** [comment]
I've pushed a fix for this to master, could you give it a look and let me know if you see any cases I've missed? In general, the precision is preferred unless there is an explicit min width for padding, so `%f` on a precision of 0 will return an empty string, but `%03f` should return `"000"`.
