### ISSUE TITLE
Error shifting time by months

### ISSUE THREAD

**Issue by CuihuaGu** [bitwalker/timex#324]
### Steps to reproduce

```
{:ok, datetime} = DateTime.from_naive(~N[2017-06-29 13:26:08.003], "Etc/UTC")
Timex.shift(datetime, months: -4)
```

### Description of issue

- This will raise an erlang error because Timex shifts the datetime to **2017-2-29**.
- Maybe explicitly checking days in months and always shift by days.

### Also:

```
Timex.shift(datetime, months: -1, days: 10)
Timex.shift(datetime, days: 10, months: -1)
```
- Those two lines will results in different values (1 day difference), for the same reason, always shift months by total days might be better.

**Comment by bitwalker** [comment]
It is expected that in the latter example that they do not shift to the same date - the order of shifts is not commutative. One reason for this is that some values do not have constant values (i.e. months/years), so we can't easily convert everything to the number of days. Additionally, depending on the order of your shifts, you may cross a timezone change between shifts, which affects the result. When you shift from say 7/31 back 1 month, there is no 6/31, so we shift to the last day of that month instead, e.g. 6/30 - which again affects how subsequent shifts are applied.

I've fixed the first issue in master and will push a new release shortly.
