### ISSUE TITLE
RFC: Consider inclusive bounds for Timex.between?/3

### ISSUE THREAD

**Issue by xavier** [bitwalker/timex#340]
Right now `Timex.between?/3` is implemented by passing the lower and upper bounds as-is to `Timex.before?/2` and `Timex.after?/2` which are both bound exclusive (which is good... most of the time) 😄
This exclusive bound behaviour doesn't fit well with "between" semantics. For instance, the `BETWEEN` clause in SQL is inclusive and so are ranges in Elixir. I think that making the bounds inclusive would make the use of this function more intuitive and avoid many potential off-by-1 errors.

I'll be happy to work on this if you think that this might be a change for the best.
I understand the breaking nature of this change and I'll welcome any guidance as how to deal with it.

**Comment by bitwalker** [comment]
I agree 100%, if you'd like to take a crack at it, that'd be great! As far as how to handle the fact that it's a breaking change, I think the best way to handle it is to introduce a new options parameter. The only option would be `inclusive: true | false`, with the default being `inclusive: false`. This gives us a deprecation cycle to change the default to `inclusive: true`, and either leave it at that or eventually deprecate the extra parameter with the new default behaviour.

As far as implementation, for the inclusive case I think we probably want to check if the input equals one of the bounds if neither before or after, using `equals?/3`, where the granularity is `:microseconds` unless another option `granularity: <unit>` is provided to override the comparison granularity.

Let me know what you think!

**Comment by xavier** [comment]
All of this sounds great, I'll get to work.

Btw, when you say `equals?/3`, are you sure you didn't mean `compare/3`?
That would have been my go-to function to implement inclusive bound checking.

**Comment by bitwalker** [comment]
@xavier Yes, use `compare/3` :)
