### ISSUE TITLE
Atlantic Daylight Time not recognized by Timex.parse

### ISSUE THREAD

**Issue by hayley** [bitwalker/timex#342]
Hi, I'm trying to parse some Canadian data, and if it's one of the major US timezones, it works just fine, but ADT is not recognized:

**works with CDT**:
```
"6:56 PM CDT Sunday 16 July 2017" |> Timex.parse!("%l:%M %p %Z %A %e %B %Y", :strftime)
#<DateTime(2017-07-16T18:56:00-05:00 CST6CDT)>
```

**fails with ADT**:
```
"6:56 PM ADT Sunday 16 July 2017" |> Timex.parse!("%l:%M %p %Z %A %e %B %Y", :strftime)

** (Timex.Parse.ParseError) {:invalid_timezone, "ADT"}
    (timex) lib/parse/datetime/parser.ex:98: Timex.Parse.DateTime.Parser.parse!/3
```

Are only the timezone abbreviations used in the contiguous US supported? Because I noticed in random testing that Alaska (AKDT) and a random Australian timezone (ACST) don't work either.

**Comment by bitwalker** [comment]
Yes, only POSIX abbreviations are present in the Olson timezone database for backwards compatibility. Outside of the U.S. those abbreviations are ambiguous (the same abbreviation is used in different locales), so we can't support them. I'm open to suggestions on how to support this situation, but up until now I haven't thought of a good way. You can parse the date/time without a timezone and then cast the resulting NaiveDateTime to a DateTime by manually specifying the timezone, assuming it's known in advance, but that's not ideal.

**Comment by hayley** [comment]
Ah, that makes sense. I think I ran into this problem with Australian timezones and Ruby way back in the day, and in the case of their stuff, though I can't remember what I did as a workaround.

I don't know how I'd solve this in general. Maybe in the case of ambiguous abbreviations, it could be solved by adding an optional argument where you could specify the country? Like, "CDT" by default would assume US, but when passed with Australia, it would mean ACDT.

Imho, sounds like a mess in general though, and I'm assuming with all of the non-standard zone abbreviations that might be out there, it's probably not worth supporting directly in the library.

I'm thinking for my case with Canada, I'll handle it by piping the time string through something to transform it before it hits `Timex.parse!`. Like:
```
"6:56 PM ADT Sunday 16 July 2017"
```
becomes
```
"6:56 PM GMT-3 Sunday 16 July 2017"
```
which will successfully parse, but let me know if there's a better way to handle it.

Thanks for your help!

**Comment by bitwalker** [comment]
It's a hack, but probably what I would end up doing as well. That said, what I would do instead of `ADT -> GMT-3` is something more like `ADT -> Canada/Central` or `ADT -> America/Toronto`. The latter two are examples of actual Olson locales you can use as timezone names in your string and will respect daylight savings time (if applicable) as well as any other locale-specific rules. It is always better to use that and then convert to UTC than to try and treat a locale as GMT(-/+)<offset>.

If you want to search for timezone names for a given locale, I just run `Timex.timezones |> Enum.filter(fn z -> z =~ "Toronto" end)` or some variant to see a list of matches.

**Comment by hayley** [comment]
Yeah, I considered trying to tie it to a location instead of the GMT+/- trick, but then I realized that, in the case of my Canadian data source, they're already handling specifying whether it's DST or not, so it would just add an extra step.

I will keep an eye out for that for future data sources though. Thanks again for your help!
