### ISSUE TITLE
Inspect.DateTime conflict in Elixir 1.5.0-rc.1 with Timex 3.1.21

### ISSUE THREAD

**Issue by ejpcmac** [bitwalker/timex#343]
[Elixir 1.5.0-rc.1](https://github.com/elixir-lang/elixir/releases/tag/v1.5.0-rc.1) now implements `Inspect` for `DateTime`.

When I compile a project using Timex 3.1.21 and Elixir 1.5.0-rc.1 I get the following warning:

```
warning: redefining module Inspect.DateTime (current version loaded from /Users/JPC/.asdf/installs/elixir/1.5.0-rc.1-otp-20/bin/../lib/elixir/ebin/Elixir.Inspect.DateTime.beam)
  lib/datetime/inspect.ex:14
```

Then, if I try to build a release with Distillery I get the following error:

```
==> Release failed, during .boot generation:
        Duplicated modules:
        'Elixir.Inspect.DateTime' specified in timex and elixir
```

Maybe `Inspect.DateTime` should not be present if we compile Timex with Elixir 1.5.0-rc.1 and later?

**Comment by bitwalker** [comment]
Yeah I'll need to conditionally implement it depending on the version of Elixir being used. Thanks for reporting! I'll get a fix pushed today.

**Comment by bitwalker** [comment]
This is fixed in master, and staged for release in 3.1.22 - just waiting for CI :)

**Comment by ejpcmac** [comment]
Thank you @bitwalker :) (And by the way, thanks for UTF-8 in conform too!)

**Comment by bitwalker** [comment]
No problem, glad to help!
