### ISSUE TITLE
Timex formatting 3.1.22 broken for Ecto.Date

### ISSUE THREAD

**Issue by tomciopp** [bitwalker/timex#345]
### Steps to reproduce
{:ok, date} = Ecto.Date.cast("1990-01-01")
Timex.format!(date, "{Mfull} {D}, {YYYY}") 

Version 3.1.21:
"January 1, 1990"

Version 3.1.22
** (UndefinedFunctionError) function :error.month/1 is undefined (module :error is not available)
            :error.month({:error, :invalid_date})
    (timex) lib/format/datetime/formatter.ex:467: Timex.Format.DateTime.Formatter.format_token/6
    (timex) lib/format/datetime/formatters/default.ex:183: Timex.Format.DateTime.Formatters.Default.do_format/4
    (timex) lib/format/datetime/formatter.ex:56: Timex.Format.DateTime.Formatter.lformat!/4

I'm unsure if this is truly a bug based on the commit log between these two versions. It looks like typespecs have become more strict which I can understand however this change does look like it has unintended consequences.

**Comment by bitwalker** [comment]
It looks like the problem is not in the formatter but in the handling of non-Calendar types. I'll take a look tonight.

**Comment by bitwalker** [comment]
This has been broken for quite some time apparently - I've fixed this and pushed it in 3.1.24. Thanks for reporting!
