### ISSUE TITLE
Timex.AmbiguousDateTime error

### ISSUE THREAD

**Issue by nicocaille** [bitwalker/timex#349]
Hello,
i have a date string that i am first converting to a NaiveDatetime

i tried with two date_string different, one is working, the other one is bringing an error i can't figure out

date_string |> NaiveDateTime.from_iso8601! |> Timex.local

```
iex(132)> date_string = "2017-02-18 22:27:34"
"2017-02-18 22:27:34"
iex(133)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
#<DateTime(2017-02-18T20:27:34-02:00 America/Sao_Paulo)>
```

If i get a date_string one hour later, i am getting the following error:

```
iex(134)> date_string = "2017-02-18 23:27:34"                      
"2017-02-18 23:27:34"
iex(135)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
** (KeyError) key :full_name not found in: #<Ambiguous(#<TimezoneInfo(America/Sao_Paulo - -02 (-02:00:00))> ~ #<TimezoneInfo(America/Sao_Paulo - -03 (-03:00:00))>)>
    (timex) lib/timex.ex:82: Timex.local/1
```

after running a few more tests, it seems that the time slot 23:00:00 -> 23:59:59 is raising a Timex error:

```
iex(141)> date_string = "2017-02-18 22:59:59"                      
"2017-02-18 22:59:59"
iex(142)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
#<DateTime(2017-02-18T20:59:59-02:00 America/Sao_Paulo)>
iex(143)> date_string = "2017-02-18 23:00:00"                      
"2017-02-18 23:00:00"
iex(144)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
** (KeyError) key :full_name not found in: #<Ambiguous(#<TimezoneInfo(America/Sao_Paulo - -02 (-02:00:00))> ~ #<TimezoneInfo(America/Sao_Paulo - -03 (-03:00:00))>)>
    (timex) lib/timex.ex:82: Timex.local/1
iex(144)> date_string = "2017-02-18 23:59:59"                      
"2017-02-18 23:59:59"
iex(145)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
** (KeyError) key :full_name not found in: #<Ambiguous(#<TimezoneInfo(America/Sao_Paulo - -02 (-02:00:00))> ~ #<TimezoneInfo(America/Sao_Paulo - -03 (-03:00:00))>)>
    (timex) lib/timex.ex:82: Timex.local/1
iex(145)> date_string = "2017-02-19 00:00:00"                      
"2017-02-19 00:00:00"
iex(146)> date_string |> NaiveDateTime.from_iso8601! |> Timex.local
#<DateTime(2017-02-18T22:00:00-02:00 America/Sao_Paulo)>
```

Thanks

**Comment by alvinlindstam** [comment]
The ambiguous datetimes are described in the docs. In your case, this is an example of [*Times with more than one valid zone period*](https://hexdocs.pm/timex/Timex.AmbiguousDateTime.html#module-ambiguity-2-times-with-more-than-one-valid-zone-period). Given datetimes between "2017-02-18 23:00:00" and "2017-02-19 00:00:00" in Sao Paulo time, there is two possible datetimes since the clock is reversed one hour at that time for DST.

`Timex.local` should, however, not raise an error on this, but return a `Timex.AmbiguousDateTime` struct instead of a DateTime. I'll look into why this is and look for a fix.

**Comment by chungwong** [comment]
Can we re-open this issue? I believe `Timex.local/1` currently broken whenever local timezone changes and resulted as system crashing.

Can we have a config option to specific in the case of ambiguous timezone info, we have the option to use `:before` or `:after` like
https://github.com/bitwalker/timex/blob/3.5.0/lib/timex.ex#L86
```
    case Timezone.local(reference_date) do
      {:error, _} = err -> err

      %Timex.AmbiguousTimezoneInfo{} = atz ->
        tz = Map.get(atz, :after)  # or use :before
        Timezone.convert(date, tz.full_name)

      tz -> Timezone.convert(date, tz.full_name)
    end
```
