### ISSUE TITLE
Consider making unit names more descriptive

### ISSUE THREAD

**Issue by alco** [bitwalker/timex#35]
The gist of the proposal is to rename time units used in `diff()`, `convert()`, and other functions to have more descriptive names:

```
usecs -> microseconds
msecs -> milliseconds
secs  -> seconds
mins  -> minutes
```

This will bring more consistency with the other units (`hours`, `days`, etc.). In the long term, having descriptive names trumps the convenience of having short ones because there is no one true way to shorten them (to my knowledge, at least).

**Comment by bitwalker** [comment]
If anyone is watching this thread, I'd like to get feedback on this change. It would affect a lot of existing code, so I want to make sure there is general buy in from the community before we start work on it.

I agree with @alco on this myself. Anyone have any thoughts to share, or think it shouldn't be done? The change would be made prior to 1.0 if we end up doing it.

**Comment by bitwalker** [comment]
Anyone have thoughts on this?

**Comment by rockerBOO** [comment]
:+1:

**Comment by alkamin** [comment]
This would be a worthwhile change.  The shortened versions of the units are not obvious or easy to remember. :+1:

**Comment by bitwalker** [comment]
Agreed, I'm going to make this part of the 1.0 release, so keep an eye out for it.

**Comment by stoft** [comment]
:+1:

**Comment by bitwalker** [comment]
This has been addressed in version 2. All unit names and functions with units in them are now consistent. The old names are deprecated with warnings in 2.0.0, the only breaking change is the `ms` field of the `DateTime` struct, which is now `millisecond`.

Version 2 is not out yet (should be tomorrow I think), but I'm closing this since it's resolved.
