### ISSUE TITLE
Week durations are not recognized

### ISSUE THREAD

**Issue by adamnbowen** [bitwalker/timex#350]
Timex.Duration doesn't seem to parse weeks in given durations.  "M" and other identifiers work as expected, but "W" does not:

```
iex(1)> Duration.parse("P1M")
{:ok, #<Duration(P1M)>}
iex(2)> Duration.parse("P1W")
{:error, "unexpected token W"}
```
As an example of another implementation of week parsing support, you can view my snippet running in with the node library iso8601-duration here: https://runkit.com/adamnbowen/597fa5d955331200125dbe02

I'm not quite sure where it's listed in the actual specification, but you can see the week format for durations mentioned in the Wikipedia entry on iso8601: https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by bitwalker** [comment]
I'm about to merge the PR which fixes this, so I'm going to close this issue, we're just wrapping up review.
