### ISSUE TITLE
`Timex.to_naive` first transforms to utc

### ISSUE THREAD

**Issue by waiting-for-dev** [bitwalker/timex#351]
### Steps to reproduce

```elixir
iex()> Timex.now("Europe/Madrid")
#<DateTime(2017-08-02T11:30:21.496094+02:00 Europe/Madrid)>
iex()> Timex.now("Europe/Madrid") |> Timex.to_naive_datetime
~N[2017-08-02 09:30:32.446455]
```

### Description of issue

Shouldn't `Timex.to_naive_datetime`be actually naive and not transform the value to utc? It is what, for example, does elixir core `DateTime.to_naive`:

```elixir
iex()> Timex.now("Europe/Madrid")                     
#<DateTime(2017-08-02T11:34:07.991993+02:00 Europe/Madrid)>
iex()> Timex.now("Europe/Madrid") |> DateTime.to_naive
~N[2017-08-02 11:34:11.393493]
```

**Comment by bitwalker** [comment]
Timex only transforms DateTimes with a timezone to UTC, other types which do not have timezone information are not shifted. This is so that we make a best attempt at leaving the naive date/time in a neutral zone if we can safely do so.
