### ISSUE TITLE
Timex doesn't take into account the "TZ=:/somefile" format env variable

### ISSUE THREAD

**Issue by andreausu** [bitwalker/timex#359]
### Steps to reproduce

- Set up the environment variable TZ like this: `TZ=:/etc/localtime`
- API function called: `Timex.local`
- Arguments provided: none

### Description of issue

- What are the expected results?

It should parse the file specified in the TZ variable to determine the timezone, instead it errors out.

The culprits are:

https://github.com/bitwalker/timex/blob/e249c847b09ee73ec2d0834a5ab3551a1f584b25/lib/timezone/timezone_local.ex#L72

https://github.com/bitwalker/timex/blob/e249c847b09ee73ec2d0834a5ab3551a1f584b25/lib/timezone/timezone_local.ex#L96

When the value of the TZ environment variable is not nil it should check if the value starts with a colon and if so it should parse the specified file.

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

GNU/Linux: http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

> If the TZ environment variable does not have a value, the operation chooses a time zone by default. In the GNU C Library, the default time zone is like the specification ‘TZ=:/etc/localtime’ (or ‘TZ=:/usr/local/etc/localtime’, depending on how the GNU C Library was configured; see Installation). Other C libraries use their own rule for choosing the default time zone, so there is little we can say about them.
> 
> If characters begins with a slash, it is an absolute file name; otherwise the library looks for the file /usr/share/zoneinfo/characters. The zoneinfo directory contains data files describing local time zones in many different parts of the world. The names represent major cities, with subdirectories for geographical areas; for example, America/New_York, Europe/London, Asia/Hong_Kong. These data files are installed by the system administrator, who also sets /etc/localtime to point to the data file for the local time zone. The files typically come from the Time Zone Database of time zone and daylight saving time information for most regions of the world, which is maintained by a community of volunteers and put in the public domain.

MacOS: http://www.manpages.info/macosx/tzset.3.html

> If TZ appears in the environment and its value begins with a colon (':'), the rest of its value is used as a pathname of a tzfile(5) -format file from which to read the time conversion information. If the first character of the pathname is a slash ('/') it is used as an absolute pathname; otherwise, it is used as a pathname relative to the system time conversion information directory.
> 
> If its value does not begin with a colon, it is first used as the pathname of a file (as described above) from which to read the time conversion information. If that file cannot be read, the value is then interpreted as a direct specification (the format is described below) of the time conversion information.

Thank you!

**Comment by bitwalker** [comment]
Done!
