### ISSUE TITLE
Error handling issue in Timex.to_unix 

### ISSUE THREAD

**Issue by vonmixer** [bitwalker/timex#361]
### Steps to reproduce

- API function called: ``Timex.to_unix``
- Arguments provided: ``%InvalidTime{}``

### Description of issue

- What are the expected results? - A valid exception should be thrown. Instead the following exception is thrown:  
```** (UndefinedFunctionError) function :insufficient_date_information.exception/1 is undefined (module :insufficient_date_information is not available) ```
This is happening because https://github.com/bitwalker/timex/blob/6ea19d1de8e23a789dc645d6d565bb5fa750e758/lib/convert/convert.ex#L39 returns ``{:error, :insufficient_date_information}`` to https://github.com/bitwalker/timex/blob/master/lib/datetime/map.ex#L14 which tries to ``raise :insufficient_date_information``

**Comment by bitwalker** [comment]
Thanks for the report, I'll get this fixed.
