### ISSUE TITLE
FreeBSD /etc/localtime unrecognized leading to :unknown_timezone

### ISSUE THREAD

**Issue by nicocaille** [bitwalker/timex#369]
While calling Timex.local getting an error:
```
(anaconda) [root@phoenix ~/projects/coturnix]# date
Mon Sep 18 19:11:00 BRT 2017
```

The file /etc/localtime is copied from /usr/share/zoneinfo/America/Sao_Paulo

```
(anaconda) [root@phoenix ~/projects/coturnix]# iex -S mix
iex(1)> Timex.local
{:error, {:unknown_timezone, "/etc/localtime"}}
```

```
iex(2)> Timex.now
#DateTime<2017-09-18 22:14:40.612156Z>
```

Any idea how that can be fixed ? Attaching the Sao_Paulo file from FreeBSD 11.1 (FreeBSD phoenix.tilikum.io 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0 r322480: Mon Aug 14 01:17:54 EDT 2017     root@octopus.tilikum.io:/usr/obj/usr/src/sys/TILIKUM  amd64)

[Sao_Paulo.zip](https://github.com/bitwalker/timex/files/1312450/Sao_Paulo.zip)

Thx!

**Comment by bitwalker** [comment]
Thanks for uploading your tzdata file! I will look into this and get back to you. It looks to me like there is a typo in the code or something though, given the error.

**Comment by bitwalker** [comment]
Fixed in master :)
