### ISSUE TITLE
Timezone handling broken

### ISSUE THREAD

**Issue by lau** [bitwalker/timex#38]
Just a heads up: The current way time zone handling is done, means it is impossible for time zone handling to be correct for all time zones. At best it will be correct for time zones that have not changed and in a while and only for dates that are newer than the last change.

Also for instance Morocco susspends DST in the middle of summer, which the TimezoneInfo does not seem to take into account?

It is necessary to take the previous rules into account otherwise it will not work correctly, when the rules change.

The current rules used by Timex are not up to date with the TZ database, but simply updating the data will not fix the issues.

**Comment by bitwalker** [comment]
Yes I'm aware, I've addressed timezone handling from scratch in my local branch, and I'm about 95% done, I just haven't had time the past month to finish it up. I'm going to be working on it this weekend, so hopefully I can finish up  the remaining loose ends by the end of the weekend.

**Comment by lau** [comment]
I have just released a tzdata package: https://hex.pm/packages/tzdata
You can use that if you want as a source for all of the up-to-date tz data.

**Comment by LeeroyDing** [comment]
Need any help on this? #43 would probably get fixed by this rewrite.

**Comment by bitwalker** [comment]
@LeeroyDing If you'd like to take a stab that would be great, I've been up to my eyeballs in other work and I hate delaying such an important change.

**Comment by bitwalker** [comment]
@lau I've merged my changes integrating timex with your tzdata library (great work on that!). @LeeroyDing I've updated #43, but could you verify that master resolves your issues?
