### ISSUE TITLE
Timex.diff/3 with :months granularity is wrong when the year is not the same

### ISSUE THREAD

**Issue by kelvinst** [bitwalker/timex#382]
### Steps to reproduce

Is pretty simple to repeat:

```elixir
iex(1)> Timex.diff(~D[2017-12-20], ~D[2017-10-19], :months)
2
iex(2)> Timex.diff(~D[2018-01-20], ~D[2017-10-19], :months)
4
```

### Description of issue

The expected behaviour would be:

```elixir
iex(1)> Timex.diff(~D[2017-12-20], ~D[2017-10-19], :months)
2
iex(2)> Timex.diff(~D[2018-01-20], ~D[2017-10-19], :months)
3
```

We suspect the problem is in this private function: https://github.com/bitwalker/timex/blob/master/lib/comparable/diff.ex#L115-L127

More specifically this logic: https://github.com/bitwalker/timex/blob/master/lib/comparable/diff.ex#L118-L125

The logic should be something like:

```elixir
if d2 >= d1, do: 12 - (m1 - m2), else: 12 - (m1 - (m2 - 1))
```

I'm working on a PR for it!

**Comment by bitwalker** [comment]
Fixed in master
