### ISSUE TITLE
Timex.diff does not check granularity validity if there is no difference

### ISSUE THREAD

**Issue by tubedude** [bitwalker/timex#384]
When `Timex.diff/3` is called with an invalid granularity, with the same value for `a` and `b` it does not check the granularity and returns `0`.
Although the result is correct, the function will fail at runtime.

```
Timex.diff(Timex.today, Timex.today, :invalid) 
#> 0
```
Should it check for the granularity validity independently of the upcoming result?

**Comment by fsabe** [comment]
For comparison, `Timex.shift` behaves in the way you expected.

```elixir
iex(1)> Timex.shift(Timex.now, days: 1)
#<DateTime(2017-10-25T18:46:49.595747Z Etc/UTC)>
iex(2)> Timex.shift(Timex.now, dayz: 1)
{:error, {:unknown_shift_unit, :dayz}}
```

**Comment by fsabe** [comment]
It also does fail when diffing times:

```
iex(9)> Timex.diff(~T[12:00:00], ~T[12:00:00], :hours)
0
iex(10)> Timex.diff(~T[12:00:00], ~T[12:00:00], :hourz)
{:error, {:invalid_granularity, :hourz}}
```

**Comment by fsabe** [comment]
Based on those observations, I've opened a PR changing that behavior to be consistent.
