### ISSUE TITLE
Regression: fractional second

### ISSUE THREAD

**Issue by isaacsanders** [bitwalker/timex#387]
### Steps to reproduce

Timex 3.1.24
```elixir
iex(1)> Timex.parse("2017-10-25T12:34:02.010", "{YYYY}-{0M}-{0D}T{h24}:{0m}:{ss}")
{:error, "Expected `fractional second` at line 1, column 18."}
```

### Description of issue

- What are the expected results?

```elixir
iex(1)> Timex.parse("2017-10-25T12:34:02.010", "{YYYY}-{0M}-{0D}T{h24}:{0m}:{ss}")
{:ok, ~N[2017-10-25 12:34:02.010]}
```

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

The above expected results are from Timex 3.0.8

**Comment by isaacsanders** [comment]
It appears that 3.1.24 performs as:

```elixir
iex(2)> Timex.parse("2017-10-25T12:34:02.010", "{YYYY}-{0M}-{0D}T{h24}:{0m}:{s}{ss}")
{:ok, ~N[2017-10-25 12:34:02.010]}
```

Is this intentional?

**Comment by bitwalker** [comment]
Yes there were issues with them being combined, I thought we had sorted things out so the change was backwards compatible, but it looks like that was broken at some point, sorry about that. I've updated the docs accordingly.
