### ISSUE TITLE
Fractional seconds are not padded with zeroes when formatting

### ISSUE THREAD

**Issue by fsabe** [bitwalker/timex#388]
```elixir
iex> t                            
#<DateTime(2014-11-03T01:41:02.023Z Etc/UTC)>
iex> Timex.format(t, "%f", :strftime)
{:ok, "230"}
iex> Timex.format(t, "{ss}")
{:ok, ".230"}
```

I expected the result to be `{:ok, "023000"}` and `{:ok, ".023"}`.

**Comment by fsabe** [comment]
This affects all formatters that include fractional seconds in the output.

e.g.
```elixir
iex> Timex.format(t, "{RFC3339}")
{:ok, "2014-11-03T01:41:02.230+00:00"}
```

**Comment by bitwalker** [comment]
I'm not clear on why `%f` should return `"023000"`, but you are correct in that the fractional seconds appear to be padded incorrectly.

**Comment by bitwalker** [comment]
Ah I see, nevermind, moving discussion to #389
