### ISSUE TITLE
days_to_beginning_of_week strange behaviour

### ISSUE THREAD

**Issue by prem-prakash** [bitwalker/timex#392]
### Steps to reproduce

```elixir
iex(21)> date = ~D[2017-11-04]
~D[2017-11-04]
iex(22)> Timex.weekday(date)
6
iex(23)> Timex.days_to_beginning_of_week(date)
5
```

### Expected result

If today is saturday, I would expect that there are 1 more day to the beginning of the next week, which is monday.

```elixir
iex(21)> date = ~D[2017-11-04]
~D[2017-11-04]
iex(22)> Timex.weekday(date)
6
iex(23)> Timex.days_to_beginning_of_week(date)
1
```

Or if this function is related to the current week, would not be better to call this `days_from_beginning_of_week` ?

**Comment by bitwalker** [comment]
It is related to the current week, i.e. it is the number of days you need to shift backwards to reach the first logical day of the week.
