### ISSUE TITLE
Timezone.beginning_of_day strips time precision

### ISSUE THREAD

**Issue by gbxl** [bitwalker/timex#393]
### Steps to reproduce

- Get a date through `Timex.Timezone.beginning_of_day`

### Description of issue

- Get any date through `Timex.Timezone.beginning_of_day` and precision is gone. Even if you try to re-format it using something like `Timex.parse("%FT%T.%f%:z", :strftime)` it won't put `0` in place of seconds-microsecs, it will just be nothing.

Eg: `Timex.local |> Timex.shift(days: 3) |> Timex.Timezone.beginning_of_day |> Timex.format!("%FT%T.%f%:z", :strftime)`
=> `"2017-11-09T00:00:00.-08:00"`

I'd expect it to at least allow for re-formating. I should keep the date in the format it is entered.

**Comment by bitwalker** [comment]
Fixed in master
