### ISSUE TITLE
strftime formatting of milliseconds

### ISSUE THREAD

**Issue by jurta** [bitwalker/timex#398]
### Steps to reproduce

- `Timex.now |> Timex.format!("%Y/%m/%d %T.%L", :strftime)`
- or just `Timex.now |> Timex.format!("%L", :strftime)`
- fails with:
```
** (Timex.Format.FormatError) got {:formatter, :unsupported_token, :ms} while retrieving Exception.message/1 for %Timex.Format.FormatError{message: {:formatter, :unsupported_token, :ms}} (expected a string)
    (timex) lib/format/datetime/formatter.ex:58: Timex.Format.DateTime.Formatter.lformat!/4
```

### Description of issue

- Expected to return a string with milliseconds (000..999) as described in the documentation.

Thanks!

**Comment by prook** [comment]
The FormatError reason handling may be improved, but the original problem remains: "%L" blows up with `{:formatter, :unsupported_token, :ms}`, because Timex.Format.DateTime.Formatter lacks format_token for `:ms` type.
