### ISSUE TITLE
 diff is not accurate for months

### ISSUE THREAD

**Issue by krystofbe** [bitwalker/timex#407]
### Steps to reproduce

In Module `Timex.Comparable.Diff` hence `Timex.diff` is not working properly when diffing months.

### Description of issue

- `Timex.diff(~D[2018-01-02], ~D[2017-01-01] , :months)` should be `12` months, not `11`. Compare to https://www.wolframalpha.com/input/?i=months+from+2018-01-02+until+2017-01-01

I've provided a bug fix in https://github.com/bitwalker/timex/pull/406

**Comment by hackling** [comment]
I believe this has been discussed at some length here:
https://github.com/bitwalker/timex/issues/360

**Comment by hackling** [comment]
I think a fix is also provided here: https://github.com/bitwalker/timex/pull/375

I too would like this "resolved" though, as it's bitten us again. 
You can pin to an earlier version before these changes were made `{:timex, "<= 3.1.13"},`

**Comment by krystofbe** [comment]
Thanks @hackling!

Since the fix i've provied in https://github.com/bitwalker/timex/pull/406 is pretty trivial (just switching two variables) i'd recommend to merge this one soon before merging https://github.com/bitwalker/timex/pull/375

**Comment by bitwalker** [comment]
Closed via #406 and #360
