### ISSUE TITLE
translation to relative dates

### ISSUE THREAD

**Issue by pedromvieira** [bitwalker/timex#409]
### Steps to reproduce

{status, relative_str} = Timex.Format.DateTime.Formatters.Relative.relative_to(Timex.shift(Timex.now(), minutes: -25), Timex.now(), "{relative}", "pt-BR")

{:ok, "25 minutes ago"}

### Description of issue

Desired (pt-BR):

{:ok, "25 minutos atrás"}

How to extract to pot or use gettext translation to achieve this localization?

**Comment by obsidienne** [comment]
Hi,

Have you find a solution ? I have the same difficulty but to override an existing translation. 

Thanks

**Comment by ckhrysze** [comment]
First, sorry for the delayed response! I'm using a later release than you likely were when reporting, but the immediate issue is just the locale string itself:

`iex(1)> {status, relative_str} = Timex.Format.DateTime.Formatters.Relative.relative_to(Timex.shift(Timex.now(), minutes: -25), Timex.now(), "{relative}", "pt-BR")      
{:ok, "25 minutes ago"}

iex(2)> {status, relative_str} = Timex.Format.DateTime.Formatters.Relative.relative_to(Timex.shift(Timex.now(), minutes: -25), Timex.now(), "{relative}", "pt_BR")
{:ok, "25 minutos atrás"}
`
The larger issue is probably how to know that without digging through the code. Is there a place in the documentation you would have checked first? Is there a guide or something else that should be in place?

I'm going to close this, but please reply with documentation suggestions (or a PR!).

**Comment by nesimtunc** [comment]
How can I see what locales are supported? I just tried `tr_TR` is not existed, it returns English.
