### ISSUE TITLE
Interval overlap with open bounds

### ISSUE THREAD

**Issue by evnu** [bitwalker/timex#410]
#395 implements an `overlaps?/2` function for intervals. The current implementation does not take right-openness into account:

```elixir
@spec overlaps?(__MODULE__.t, __MODULE__.t) :: boolean()
def overlaps?(interval_a, interval_b) do
  interval_a.from in interval_b ||
    interval_a.until in interval_b ||
    interval_b.from in interval_a
end
```

So for two intervals `a = [t0,t1)` and `b = [t1, t2)`, they may overlap according to the definition above, but should not overlap in reality.

### Example

```elixir
iex(1)> a = Timex.Interval.new(from: ~D[2016-03-07], until: [days: 1], right_open: true)
%Timex.Interval{
  from: ~N[2016-03-07 00:00:00],
  left_open: false,
  right_open: true,
  step: [days: 1],
  until: ~N[2016-03-08 00:00:00]
}
iex(2)> b = Timex.Interval.new(from: ~D[2016-03-08], until: [days: 1])                 
%Timex.Interval{
  from: ~N[2016-03-08 00:00:00],
  left_open: false,
  right_open: true,
  step: [days: 1],
  until: ~N[2016-03-09 00:00:00]
}
iex(3)> Timex.Interval.overlaps?(a, b)
true
```

### Expected Result

I would expect that `a, b` from the example above do not overlap, as `~D[2016-03-08]` is not within `a`:

```elixir
iex(22)> b.from in a
false
```

They do overlap according to `overlaps?/2` because `a.until` is in `b`. But `a.until` is not part of `a` according to the definition taken from Wikipedia (and present in the moduledoc of `Timex.Interval`):

> "An interval is said to be left-open if and only if it has no minimum 
(an element that is smaller than all other elements); right-open if it has no maximum;
and open if it has both properties. The interval [0,1) = {x | 0 ≤ x < 1}, for example,
is left-closed and right-open. The empty set and the set of all reals are open intervals,
while the set of non-negative reals, for example, is a right-open but not left-open interval.
The open intervals coincide with the open sets of the real line in its standard topology."

Note that I did not check the implementation against all possible `_open` combinations.

**Comment by rafaelrochasilva** [comment]
Since the function makes 3 checks, it is returning true, when:
```elixir
a.until in b
```
That's the reason it is been returning true and it is not considering the right-openness.

**Comment by bitwalker** [comment]
The interval overlap behaviour was broken, it has been reworked in master (and the 3.4.0 tag, not yet on hex)
