### ISSUE TITLE
Invalid time zone in match Europe/Moscow

### ISSUE THREAD

**Issue by majioa** [bitwalker/timex#418]
### versions

Elixir 1.7.0dev
timex 3.1

### Steps to reproduce

- API function called
- Arguments provided

        Timex.local

        ** (MatchError) no match of right hand side value: ["ZONE=Europe/Moscow\n"]
        lib/timezone/timezone_local.ex:227: Timex.Timezone.Local.read_timezone_data/3
        lib/timezone/timezone_local.ex:124: Timex.Timezone.Local.localtz/2
        lib/timezone/timezone_local.ex:58: Timex.Timezone.Local.lookup/1
        lib/timezone/timezone.ex:53: Timex.Timezone.local/1
        lib/timex.ex:62: Timex.local/0

### Description of issue

- What are the expected results?

   local time of MSK zone

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

**Comment by majioa** [comment]
@bitwalker ?

**Comment by bitwalker** [comment]
This was fixed in master, in the commit linked above, sorry if that wasn't clear!

**Comment by majioa** [comment]
ok
