### ISSUE TITLE
Week index in a month for a given date

### ISSUE THREAD

**Issue by shankardevy** [bitwalker/timex#42]
I am working on a project, where I needed week index in the context of the month and not year.  I ended up writing my own private function like below

```
  defp week_index_in_month(date) do
    {_, week_index_of_given_date} = Timex.Date.iso_week(date)
    {_, week_index_of_first_day_of_given_month} = Timex.Date.iso_week(%{date | day: 1})
    week_index_of_given_date - week_index_of_first_day_of_given_month
  end
```

are you interested in getting this into the library? If so, I can provide a PR.

**Comment by bitwalker** [comment]
Sure! Could we call this function `week_of_month`?

**Comment by bitwalker** [comment]
Included in Version 2.
