### ISSUE TITLE
Timex.parse problems?!

### ISSUE THREAD

**Issue by ohashijr** [bitwalker/timex#420]
### Steps to reproduce

iex(10)> Timex.parse("2018-02-30", "{YYYY}-{0M}-{0D}")
{:ok, ~N[2018-02-30 00:00:00]}
iex(11)> ~D[2018-02-30]
** (ArgumentError) cannot parse "2018-02-30" as date, reason: :invalid_date
    (elixir) lib/calendar/date.ex:276: Date.from_iso8601!/2
    (elixir) expanding macro: Kernel.sigil_D/2
    iex:11: (file)
iex(11)> Timex.parse("2018-02-30", "%Y-%m-%d", :strftime)
{:ok, ~N[2018-02-30 00:00:00]}
iex(12)> Timex.parse!("2018-02-30", "%Y-%m-%d", :strftime)
~N[2018-02-30 00:00:00]

### Description of issue

- What are the expected results?
Why the 2018-02-30 is converting, ok?

**Comment by karlseguin** [comment]
To give an example of why this is a problem. We get user input and validate/convert it by using `Timex.parse/2` if we get `{:ok, date}` we pass `date` around. This date isn't valid though and will fail in any other places that applies correct validation, i.e.,  Ecto/Postgrex.
