### ISSUE TITLE
Monthly iteration with Timex.Interval broken?

### ISSUE THREAD

**Issue by jacegu** [bitwalker/timex#424]
I'm not 100% sure this is a bug or intended, but I thought it was worth asking.

### Steps to reproduce

This is the code I was using:

```elixir
interval = Timex.Interval.new(from: ~N[2018-12-31 12:00:00], until: [months: 12], step: [months: 1])
# %Timex.Interval{
#   from: ~N[2018-12-31 12:00:00],
#   left_open: false,
#   right_open: true,
#   step: [months: 1],
#   until: ~N[2019-12-31 12:00:00]
# }

Enum.take(interval, 12)
# [~N[2018-12-31 12:00:00], ~N[2019-01-31 12:00:00], ~N[2019-02-28 12:00:00],
#  ~N[2019-03-28 12:00:00], ~N[2019-04-28 12:00:00], ~N[2019-05-28 12:00:00],
#  ~N[2019-06-28 12:00:00], ~N[2019-07-28 12:00:00], ~N[2019-08-28 12:00:00],
#  ~N[2019-09-28 12:00:00], ~N[2019-10-28 12:00:00], ~N[2019-11-28 12:00:00],
#  ~N[2019-12-28 12:00:00]]
```

### Description of issue

Note how the day of the month shifts to the 28th for all months after February. Also the final element of the interval doesn't match `until`.

I was expecting the result to be the last day of each month for every month. This is:
```elixir
# [~N[2018-12-31 12:00:00], ~N[2019-01-31 12:00:00], ~N[2019-02-28 12:00:00],
#  ~N[2019-03-31 12:00:00], ~N[2019-04-30 12:00:00], ~N[2019-05-31 12:00:00],
#  ~N[2019-06-30 12:00:00], ~N[2019-07-31 12:00:00], ~N[2019-08-31 12:00:00],
#  ~N[2019-09-30 12:00:00], ~N[2019-10-31 12:00:00], ~N[2019-11-30 12:00:00],
#  ~N[2019-12-31 12:00:00]]
```

The behaviour I was expecting comes from a somewhat equivalent implementation using Ruby and [`active_support`](https://github.com/rails/rails/tree/master/activesupport):

```ruby
require 'date'
require 'active_support/all'

date = DateTime.parse("2018/12/31 12:00:00")
# => Mon, 31 Dec 2018 12:00:00 +0000
interval = (0..13).lazy.map { |month_number| date + month_number.months }
interval.first(13).to_a
# => [Mon, 31 Dec 2018 12:00:00 +0000, Thu, 31 Jan 2019 12:00:00 +0000, Thu, 28 Feb 2019 12:00:00 +0000, Sun, 31 Mar 2019 12:00:00 +0000, Tue, 30 Apr 2019 12:00:00 +0000, Fri, 31 May 2019 12:00:00 +0000, Sun, 30 Jun 2019 12:00:00 +0000, Wed, 31 Jul 2019 12:00:00 +0000, Sat, 31 Aug 2019 12:00:00 +0000, Mon, 30 Sep 2019 12:00:00 +0000, Thu, 31 Oct 2019 12:00:00 +0000, Sat, 30 Nov 2019 12:00:00 +0000, Tue, 31 Dec 2019 12:00:00 +0000]
```

**Comment by ckhrysze** [comment]
@jacegu Thank you for taking the time to create an issue!

I think the big difference is intervals step from the previous value, and once a February (or any shorter month really) is the previous, the context for 'end of the month' is basically lost. However, the ruby code in this example isn't quite a direct translation, it repeatedly adds the number of months to the original. Equivalent elixir/timex also gives the expected result:

```elixir
d = ~N[2018-12-31 12:00:00]
# ~N[2018-12-31 12:00:00]

0..12 |> Enum.map(fn (i) -> Timex.shift(d, months: i) end)

# [~N[2018-12-31 12:00:00], ~N[2019-01-31 12:00:00], ~N[2019-02-28 12:00:00],
#  ~N[2019-03-31 12:00:00], ~N[2019-04-30 12:00:00], ~N[2019-05-31 12:00:00],
#  ~N[2019-06-30 12:00:00], ~N[2019-07-31 12:00:00], ~N[2019-08-31 12:00:00],
#  ~N[2019-09-30 12:00:00], ~N[2019-10-31 12:00:00], ~N[2019-11-30 12:00:00],
#  ~N[2019-12-31 12:00:00]]
```

While I agree that the Timex behavior that created this issue is non-ideal from a user intent perspective, changing the behavior may lead to imprecision or vague results. As such I'm closing this issue, but please re-open if you'd like to discuss further.
