### ISSUE TITLE
Timex.diff/3 reporting zero at granularity :months between 3/31/2018 and 4/30/2018

### ISSUE THREAD

**Issue by wfgilman** [bitwalker/timex#425]
### Steps to reproduce

Timex 3.1.24
- Timex.Comparable.diff/3
```
iex(3)> {:ok, d1} = Date.new(2018, 03, 31)
{:ok, ~D[2018-03-31]}
iex(4)> {:ok, d2} = Date.new(2018, 04, 30)
{:ok, ~D[2018-04-30]}
iex(5)> Timex.diff d1, d2, :months
0
```

### Description of issue

- I noticed a test of mine failing today all of a sudden. It's because `Timex.diff/3` is reporting a zero month difference between 2018-03-31 and 2018-04-30.

The following code works, however:
```
iex(9)> {:ok, d1} = Date.new(2018, 03, 31)
{:ok, ~D[2018-03-31]}
iex(10)> Timex.shift d1, months: 1
~D[2018-04-30]
iex(11)>
```

**Comment by bitwalker** [comment]
This is fixed in master
