### ISSUE TITLE
Timex.Timezone.convert has very surprising return results

### ISSUE THREAD

**Issue by samphilipd** [bitwalker/timex#435]
### Description of issue

I don't know if this applies to other functions in the Timex library, but `Timex.Timezone.convert` has a surprising return signature:

```
convert(date :: DateTime.t(), tz :: Timex.AmbiguousTimezoneInfo.t()) ::
  Timex.AmbiguousDateTime.t() | {:error, term()}
```

The usual convention for Elixir functions that can fail is to either:

1. Return `{:ok, result}` or `{:error, description}`
2. Return result or raise exception

This function seems to have one foot in each camp. The fact it returns the result without being wrapped in an `{:ok, result}` tuple implies that it cannot fail. It also makes it more difficult to match on the result (you have to use `DateTime{} = ...`).

We have just been caught out by a bug in production code where a `{:error, :invalid_date}` showed up in an unexpected place and it took a long time to track down. Are there plans to change the interface?

**Comment by bitwalker** [comment]
You should avoid using that API, as it is private. Use `Timex.to_datetime/2` to either create DateTimes in a given time zone, or convert a DateTime to a different timezone.

**Comment by codeadict** [comment]
@bitwalker - Would you say that `Timex.to_datetime/2` is a complete replacement with on par features for `Timex.Timezone.convert`?

**Comment by codeadict** [comment]
I see issues when handling DST with `to_datetime/2`. Taking for example "2017-03-12", the DST started and clocks skipped from 1:59:59 to 3:00:00. Hence the time 2:30:00 never happened that day in America/New_York:
```
iex(1)> dt = ~N[2017-03-12 02:30:00]
iex(2)> dt |> Timex.Timezone.convert("America/New_York")
#DateTime<2017-03-11 21:30:00-05:00 EST America/New_York>
iex(3)> dt |> Timex.to_datetime("America/New_York")
{:error, {:could_not_resolve_timezone, "America/New_York", 63656505000, :wall}}
```
Curious to hear why they are different?
