### ISSUE TITLE
Version 3.4 not published to hex

### ISSUE THREAD

**Issue by sztosz** [bitwalker/timex#444]
It's not a bug per se, but latest version on hex.pm https://hex.pm/packages/timex is 3.3, is this expected "behaviour"? Or just someone simply forgot to push it to hex.pm?

**Comment by ckhrysze** [comment]
After discussing this with @bitwalker, it was tagged expecting an additional change, but that PR was never finished. It will probably never be pushed, and 3.5 is likely to be the next pushed version.
