### ISSUE TITLE
Shifting a DateTime by a month does not always work as expected

### ISSUE THREAD

**Issue by nihalgonsalves** [bitwalker/timex#451]
### Steps to reproduce

- API function called: `Timex.shift/2`
- Arguments provided: `[#DateTime<2018-07-31 00:00:00Z>, [months: -1]]`

### Description of issue

The documentation for [`shift/2`](https://hexdocs.pm/timex/Timex.html#shift/2) states:

> Shifting by months will always return a date in the expected month. Because months have different number of days, shifting to a month with fewer days may may not be the same day of the month as the original date.

Just today (on 31st July) we had a test mysteriously fail, and we managed to pinpoint the issue to the fact that the test subtracted a month from `DateTime.utc_now()`.

### Expected results

Shifting by `-1` months should result in a date in the previous month

### Actual results

```ex
iex(1)> {:ok, datetime, _} = DateTime.from_iso8601("2018-07-31T00:00:00Z")
{:ok, #DateTime<2018-07-31 00:00:00Z>, 0}
iex(2)> Timex.shift(datetime, months: -1)
#DateTime<2018-07-01 00:00:00Z>
```

This behaviour is inconsistent with how it works with a Date struct, which works correctly:

```ex
iex(3)> Timex.shift(~D[2018-07-31], months: -1)
~D[2018-06-30]
```

**Comment by bitwalker** [comment]
Fixed in master
