### ISSUE TITLE
Convert Date From Unixtime

### ISSUE THREAD

**Issue by rizafahmi** [bitwalker/timex#46]
I have `epoch_time` taken from RethinkDB I believe that's unixtime format, for example: `1423155600`. How to convert it into Date format using Timex?

**Comment by bitwalker** [comment]
Use `Date.from_secs(secs, :epoch)` :)

**Comment by rockwood** [comment]
Looks like this has changed. Is this now the proper way to parse an epoch integer?

`Timex.DateFormat.parse(Integer.to_string(1442156633), "{s-epoch}")`

**Comment by bitwalker** [comment]
@rockwood I typo'd in my post above, it's actually `Date.from(1442156633, :secs)`, `:epoch | :zero` can be provided as a third argument to determine which point in time the integer is relative to (unix epoch or year zero of the gregorian calendar).
