### ISSUE TITLE
"not expr1 in expr2" is deprecated

### ISSUE THREAD

**Issue by dc0d** [bitwalker/timex#462]
### Steps to reproduce

- $ mix deps.get
- $ mix compile

### Description of issue

Using Elixir ~> 1.7, after `mix compile`, these warnings show up:

```
warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
  lib/comparable/diff.ex:62

warning: "not expr1 in expr2" is deprecated. Instead use "expr1 not in expr2" if you require Elixir v1.5+, or "not(expr1 in expr2)" if you have to support earlier Elixir versions
  lib/calendar/julian.ex:81
```

**Comment by ckhrysze** [comment]
Thank you for reporting! This issue was related to the issue breaking the build for a bit, but that has been resolved, and this warning no longer appears on master.
