### ISSUE TITLE
Uniform parsing of "Z" and "+0000" timezones

### ISSUE THREAD

**Issue by obrok** [bitwalker/timex#47]
Currently there seems to be no way to uniformly parse an ISO 8601 string. Additionally some valid ways of representing timezone offsets are rejected. If I understand correctly the following assertions should be true but all of them give a parse error.

    date1 = Date.from({{2014, 8, 14}, {12, 34, 33}})
    assert { :ok, ^date1 } = parse("2014-08-14T12:34:33Z", "{ISO}")
    assert { :ok, ^date1 } = parse("2014-08-14T12:34:33+00", "{ISO}")
    assert { :ok, ^date1 } = parse("2014-08-14T12:34:33+00:00", "{ISO}")

I can try my hand at fixing that if you think this is correct.

**Comment by bitwalker** [comment]
I have this fixed on another branch actually, I'll merge that ASAP :)

**Comment by bitwalker** [comment]
Fixed in a8a7885

**Comment by jeznet** [comment]
[a8a7885](https://github.com/bitwalker/timex/commit/a8a78854d1e87825a269677c5a89b2fd860a3e87) does solve this issue reported by @obrok:
> Additionally some valid ways of representing timezone offsets are rejected

but it (nor any comment here) does not address:
>  there seems to be no way to uniformly parse an ISO 8601 string

@bitwalker Could you comment on that? 
I personally would need such a function that would behave as @obrok specified with the assertions (a function that would proper interpret any valid ISO-8601 date time string).

**Comment by bitwalker** [comment]
@jeznet I agree that this is a needed enhancement, I'll look into this today and see what is required to change the `{ISO}` and `{ISOz}` shortcuts to allow any valid ISO 8601 datetime string (with the exception that `{ISOz}` would assert that the input string is zulu-formatted.

**Comment by obrok** [comment]
It seems `{ISOz}` should assert the offset is 0 instead of checking for the litaral `Z`?

**Comment by bitwalker** [comment]
@obrok `{ISOz}` is a shortcut for the Zulu-suffixed ISO 8601 format, i.e. `2015-07-01T12:00:00.000Z`. My plan would be to allow `{ISO}` to parse both Zulu-suffixed and offset-suffixed formats, but for `{ISOz}` to only allow the Zulu-suffixed format.

**Comment by bitwalker** [comment]
@jeznet / @obrok I pushed a new version of timex which contains a change to handle this request (and provide the structure for doing similar things with other directives, as well as some internal restructuring. Could you two pull down master (or the tag 0.16.0) and test with it? Once I get some confirmation that things are looking good for you, I'll push to hex.

**Comment by jeznet** [comment]
@bitwalker Tested it and things are looking good for me.

Side note: I had to only change Timex.DateFormat.parse to Timex.Format.DateTime.DateFormat.parse (which I in the end replaced with calling `use Timex` and using just `DateFormat.parse` as described in the README).

**Comment by bitwalker** [comment]
@jeznet Yeah that's the one change I'm a little nervous about, which is why I incremented the minor version. The change was kind of necessary to keep things better organized and named, but the `DateFormat` module is the only one (with the exception of custom parsers) which might affect users. I feel like most people use the `use Timex` method, in which case it's transparent, but I'm sure you're not the only one to reference the module directly.

**Comment by obrok** [comment]
Can't really upgrade in my project, as `timex_ecto` requires `timex ~> 0.15.0`. Is that a bug by the way?

**Comment by bitwalker** [comment]
@obrok I've pushed `timex_ecto` 0.2.0 which has been updated to use timex 0.16.0. You can always do this in your mix.exs if this comes up again though:

```elixir
def deps do
  [{:timex, "x.x.x", override: true}, {:timex_ecto, "x.x.x"}]
end
```

That will override the timex dependency. Of course you risk running into bugs overriding deps this way, but usually if everything compiles you are good to go.

**Comment by bitwalker** [comment]
Since this has been pushed to hex, I'm closing this for now. Please reopen if there are any problems with this specific issue.

**Comment by obrok** [comment]
@bitwalker Forgot about that! I'll try it out tomorrow, thanks.

**Comment by obrok** [comment]
Tested `0.16.0` briefly, seems to work as expected.
