### ISSUE TITLE
Shifting to non-existing target time in given timezone returns an error

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#474]
### Steps to reproduce

- API function called: `Timex.shift/2`
- Arguments provided: `[Timex.Timezone.resolve("Canada/Yukon", {{2012, 3, 12}, {2, 43, 31}}), days: -1]`
- Version: `3.4.1`

### Description of issue

- What are the expected results?
The target time - `2012-03-11 02:43:31-07:00` does not exist in given timezone. Still would expect `Timex.shift/2` to return corresponding / nearest time in given timezone, which would be `2012-03-11 03:43:31-07:00`
- Actual results:
~~~
iex(6)> Timex.shift(Timex.Timezone.resolve("Canada/Yukon", {{2012, 3, 12}, {2, 43, 31}}), days: -1)
{:error, {:could_not_resolve_timezone, "Canada/Yukon", 63498653011, :wall}}
~~~
- Similar logic with [`moment.js`](https://momentjs.com/)

~~~
$ npm install moment-timezone
$ node
> var moment = require('moment-timezone');
> moment.tz("2012-03-12 02:43:31", "Canada/Yukon").subtract(1, 'day').format()
'2012-03-11T03:43:31-07:00'
~~~

**Comment by bitwalker** [comment]
This is fixed in master, let me know if you spot further issues!
