### ISSUE TITLE
The bounds of intervals are inverted now!

### ISSUE THREAD

**Issue by arfl** [bitwalker/timex#482]
Hi.
In your [commit](https://github.com/bitwalker/timex/commit/063e2dd1d5c0767e5e24ee3b8bc8bd2157aa7362) you swapped the bounds of intervals.
BUT: Your initial implementation was correct, see your link in the docs. Now your code as well as your documentation are just wrong

> An **open interval** does not include its endpoints, and is indicated with parentheses `()`.

> A **closed interval** is an interval which includes all its limit points, and is denoted with square brackets `[]`.

Revert the commit?

Greetings

Andreas

**Comment by tmpduarte** [comment]
Me and @marinho10 just stumbled across this exact same problem and we thought it was our code, thanks @arfl for reporting
