### ISSUE TITLE
Timex#shift broken in version 3.4.2

### ISSUE THREAD

**Issue by tomciopp** [bitwalker/timex#484]
### Steps to reproduce
- API function called
- Arguments provided

current = DateTime.from_naive(~N[2018-11-05 00:19:06.381665], "Etc/UTC")

Timex.shift(current, days: -4) 
=> 2018-11-01 00:19:06.381665

Timex.shift(current, days: -5) 
=> 2018-11-01 00:19:06.381665

### Description of issue
Shifting by a negative date does not work correctly. I haven't taken a deep look at the code yet, but it looks like the changes to `Timex#shift` have broken negative shifts. The thing that immediately looks suspicious to me is that the day lands on a month boundary, but I'd have to look into it to see what error was introduced. As shown above, negative shifting by a different number of days returns the same point in time.

**Comment by baldmountain** [comment]
I have a similar issue and I think it is related. I'll add it to this issue. Both are related to the DST time change. I would expect this:

```elixir
iex(5)> Timex.now("America/New_York") |> Timex.beginning_of_month() |> Timex.shift(months: 1)
#DateTime<2018-11-30 23:00:00-05:00 EST America/New_York>
```
 to be equal to:

```
#DateTime<2018-12-01 00:00:00-05:00 EST America/New_York>
```

not 11:00pm on the 30th.

**Comment by baldmountain** [comment]
I was wrong. These are two different issues.

**Comment by alex88** [comment]
Just checked and downgrading to 3.4.1 fixes the issue:
```
# 3.4.2

iex(5)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -0)
#DateTime<2018-01-04 00:00:00Z>
iex(6)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -1)
#DateTime<2018-01-03 00:00:00Z>
iex(7)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -2)
#DateTime<2018-01-02 00:00:00Z>
iex(8)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -3)
#DateTime<2018-01-01 00:00:00Z>
iex(9)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -4)
#DateTime<2018-01-01 00:00:00Z>
iex(10)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -5)
#DateTime<2017-12-31 00:00:00Z>
iex(11)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -6)
#DateTime<2017-12-30 00:00:00Z>

# 3.4.1

iex(2)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -0)
#DateTime<2018-01-04 00:00:00Z>
iex(3)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -1)
#DateTime<2018-01-03 00:00:00Z>
iex(4)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -2)
#DateTime<2018-01-02 00:00:00Z>
iex(5)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -3)
#DateTime<2018-01-01 00:00:00Z>
iex(6)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -4)
#DateTime<2017-12-31 00:00:00Z>
iex(7)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -5)
#DateTime<2017-12-30 00:00:00Z>
iex(8)> Timex.parse!("2018-01-04T00:00:00+00:00", "{ISO:Extended}") |> Timex.shift(days: -6)
#DateTime<2017-12-29 00:00:00Z>
```

**Comment by baldmountain** [comment]
This PR fixes the issue. https://github.com/bitwalker/timex/pull/487 Someone just needs a chance to look at it.

**Comment by mkorszun** [comment]
Having similar issues:

~~~
# 3.4.1 / Correct
iex(5)> Timex.Timezone.convert(~N[2018-09-28T10:00:00], "Europe/Berlin") |> Timex.shift(months: 1)
#DateTime<2018-10-28 12:00:00+01:00 CET Europe/Berlin>
~~~

~~~
# 3.4.2 / Incorrect
Timex.Timezone.convert(~N[2018-09-28T10:00:00], "Europe/Berlin") |> Timex.shift(months: 1)
#DateTime<2018-10-28 11:00:00+01:00 CET Europe/Berlin>
~~~

Similar logic with `moment.js`:
~~~
> var moment = require('moment-timezone');
undefined
> moment.tz(moment.utc("2018-09-28T10:00:00"), "Europe/Berlin").add(1, 'month')
moment.parseZone("2018-10-28T12:00:00.000+01:00")
~~~

**Comment by coladarci** [comment]
Just got destroyed by this - we heavily rely on shifting and the moment 4pm west coast hit and UTC NOW was the first of the month "tomorrow", our negative shifts crossed the month barrier and all hell broke loose. 

I can confirm that 3.4.1 works correctly as we are reverting to that release to try and dig out of this fire.

**Comment by williamweckl** [comment]
Confirming that 3.4.1 works correctly too.

**Comment by asummers** [comment]
3.4.1 has issues with shift, too. Not as many but we still have bugs on 3.4.1. Had to roll back to 3.3.0 to keep tests passing.

**Comment by asummers** [comment]
I can confirm https://github.com/bitwalker/timex/pull/487 fixes all of my issues, however.

**Comment by mkarnebeek** [comment]
https://github.com/bitwalker/timex/commit/2721fe2c35725755ef35bdbe019853ccf477476a puts a refactor in a patch version.

**Comment by asummers** [comment]
All we need now is a Hex bump.

**Comment by bitwalker** [comment]
On it

**Comment by bitwalker** [comment]
Done as 3.5.0
