### ISSUE TITLE
[Daylight Savings] AmbiguousDateTime returned when it should not

### ISSUE THREAD

**Issue by stavro** [bitwalker/timex#488]
Timex version `3.4.2` (latest as of the time of writing)

### Steps to reproduce
```elixir
{:ok, datetime, _} = DateTime.from_iso8601("2018-11-04T09:30:00Z")

Timex.Timezone.convert(datetime, "America/Los_Angeles")
# => #<Ambiguous(#DateTime<2018-11-04 02:30:00-07:00 PDT America/Los_Angeles> ~ #DateTime<2018-11-04 01:30:00-08:00 PST America/Los_Angeles>)>
```

### Description of issue
The Timex API returns an `AmbiguousDateTime` when it should not.

Further examination of the Tzdata for this period of time:

```elixir
Tzdata.periods_for_time "America/Los_Angeles", :calendar.datetime_to_gregorian_seconds({{2018,11,04},{1,30,00}}), :wall

[%{from: %{standard: 63687952800, utc: 63687981600, wall: 63687956400},
   std_off: 3600,
   until: %{standard: 63708512400, utc: 63708541200, wall: 63708516000},
   utc_off: -28800, zone_abbr: "PDT"},
 %{from: %{standard: 63708512400, utc: 63708541200, wall: 63708512400},
   std_off: 0,
   until: %{standard: 63719402400, utc: 63719431200, wall: 63719402400},
   utc_off: -28800, zone_abbr: "PST"}]
```

There is no overlap of UTC time between PDT and PST.  The transition between PDT and PST happens exactly at `63708541200`, which is _before_ the input of `"2018-11-04T09:30:00Z" (utc: 63708543000)`

The UTC time of `"2018-11-04T09:30:00Z"` can _only_ be represented as 1:30 PST.  The value of 2:30 PDT is not a valid option.

### Moment.js

```javascript
moment.tz("2018-11-04T09:30:00", "UTC").tz("America/Los_Angeles").format()
"2018-11-04T01:30:00-08:00"
```

### Postgres
```sql
SELECT (TIMESTAMP '2018-11-04T09:30:00Z' AT TIME ZONE 'UTC') AT TIME ZONE 'America/Los_Angeles';

      timezone
---------------------
 2018-11-04 01:30:00
```

### Ruby
```ruby
TZInfo::Timezone.get("America/Los_Angeles").utc_to_local(Time.utc(2018, 11, 4, 9, 30, 0))
=> 2018-11-04 01:30:00 UTC
```

**Comment by brianmay** [comment]
I just encountered what looks like a similar problem with converting from UTC to "Australia/Melbourne" timezone:

```
iex(3)> DateTime.from_naive!(~N[2017-04-01 15:00:00], "Etc/UTC") |> Timex.Timezone.convert("Australia/Melbourne")
#<Ambiguous(#DateTime<2017-04-02 02:00:00+11:00 AEDT Australia/Melbourne> ~ #DateTime<2017-04-02 01:00:00+10:00 AEST Australia/Melbourne>)>
```

This was the expected result:

```
iex(6)> DateTime.from_naive!(~N[2017-04-01 15:00:00], "Etc/UTC") |> Calendar.DateTime.shift_zone("Australia/Melbourne")
{:ok, #DateTime<2017-04-02 02:00:00+11:00 AEDT Australia/Melbourne>}
```

Similarly, I believe this time conversion is not ambiguous.

**Comment by glassbead0** [comment]
I encountered this when `shift`ing times as well in version 3.4.2, and I believe there is a bug somewhere in `Timex.Timezone.convert` or `Timex.Timezone.resolve` that is the root of this. 

```
iex(1)> time = Timex.to_datetime({{2018, 11, 04}, {00, 45, 00}}, "America/Denver") # 15 minutes before the "fall back" change
#DateTime<2018-11-04 00:45:00-06:00 MDT America/Denver>
iex(2)> time |> Timex.shift(minutes: 15)
#<Ambiguous(#DateTime<2018-11-04 01:00:00-06:00 MDT America/Denver> ~ #DateTime<2018-11-04 00:00:00-07:00 MST America/Denver>)>
```

I believe the result of `time |> Timex.shift(minutes: 15)` should unambiguously be ` #DateTime<2018-11-04 00:00:00-07:00 MST America/Denver>`

This seems to only impact the "fall back" hour, not the "spring forward" hour

```
iex(5)> time = Timex.to_datetime({{2018, 03, 11}, {01, 45, 00}}, "America/Denver") # 15 minutes before the "spring forward" change
#DateTime<2018-03-11 01:45:00-07:00 MST America/Denver>
iex(6)> time |> Timex.shift(minutes: 15)
#DateTime<2018-03-11 03:00:00-06:00 MDT America/Denver>
```

This correctly returns a `DateTime` in the "new" timezone (MDT)

**Comment by silva96** [comment]
On the 6th of april 2019 Chilean time was changed from summer time (UTC-3) to daylight savings time (UTC-4)

Calling `Timex.now("America/Santiago")` after the time changed (from 00 to 1am old time) was giving 
```
Timex.now("America/Santiago")
#<Ambiguous(#DateTime<2019-04-06 23:32:55.698958-03:00 -03 America/Santiago> ~ #DateTime<2019-04-06 22:32:55.698958-04:00 -04 America/Santiago>)>
```

But why is it ambiguos? it is definitely a time that we can identify, 23.32 -03 ... the timezone changed from -4 to -3, there is not ambiguous concept there.

in ruby (rails) we have:

```
Time.zone.now
 => Sat, 06 Apr 2019 23:32:55 -03 -03:00
```

**Comment by chungwong** [comment]
> On the 6th of april 2019 Chilean time was changed from summer time (UTC-3) to daylight savings time (UTC-4)
> 
> Calling `Timex.now("America/Santiago")` after the time changed (from 00 to 1am old time) was giving
> 
> ```
> Timex.now("America/Santiago")
> #<Ambiguous(#DateTime<2019-04-06 23:32:55.698958-03:00 -03 America/Santiago> ~ #DateTime<2019-04-06 22:32:55.698958-04:00 -04 America/Santiago>)>
> ```
> But why is it ambiguos? it is definitely a time that we can identify, 23.32 -03 ... the timezone changed from -4 to -3, there is not ambiguous concept there.
> 
> in ruby (rails) we have:
> 
> ```
> Time.zone.now
>  => Sat, 06 Apr 2019 23:32:55 -03 -03:00
> ```

You can refer to this https://github.com/bitwalker/timex/issues/349
For some reason the issue got closed

**Comment by brianmay** [comment]
Until this is fixed, I suggest using the calendar library for time zone conversions, as per [example](https://github.com/bitwalker/timex/issues/488#issuecomment-440450684) it works fine.

**Comment by bitwalker** [comment]
@stavro In the OP, you are incorrect about your evaluation of overlap, the reason why tzdata returns two periods for the same wall clock time is because there is inherent ambiguity, a choice must be made. Now using UTC clock time, it is unambiguous, but in favor of PDT, not PST as you assert (you can check this by passing `:utc` instead of `:wall).

The same applies to all the examples here, so since it seems to be that the expectation is we use UTC clock time to resolve the ambiguity, and since it appears other libraries do that as well, I'm making that change in master to address this

**Comment by mtrudel** [comment]
This breaks the previous behaviour of `Timex.to_datetime(%NaiveDateTime{} = time, timezone)` where time (as a wall time in the zone) is within a backwards DST transition. On Timex 3.5.0, we get:
```
iex> Timex.to_datetime(~N[2019-11-03 01:30:00], "America/Chicago")
#<Ambiguous(#DateTime<2019-11-03 01:30:00-05:00 CDT America/Chicago> ~ #DateTime<2019-11-03 01:30:00-06:00 CST America/Chicago>)>
```
whereas on Timex 3.6.1, we get:
```
iex> Timex.to_datetime(~N[2019-11-03 01:30:00], "America/Chicago")
#DateTime<2019-11-03 01:30:00-05:00 CDT America/Chicago>
```
Previously, we would use this functionality to determine whether a given wall time was within a DST transition. Now, it seems that we need to resort to the underlying `Tzdata.periods_for_time(timezone, seconds_from_zeroyear, :wall)` call. Is this the correct way to be interrogating a wall time for ambiguity, or am I using the Timex API incorrectly here? At a minimum, it would seem that as a breaking change in a minor version revision.
