### ISSUE TITLE
Timezone convert bug when gregorian time + offset falls in DST missing hour. 

### ISSUE THREAD

**Issue by noizu** [bitwalker/timex#491]
### Steps to reproduce
```elixir
tz = "America/New_York"
time = DateTime.from_iso8601("2018-03-11T06:12:22.725Z") |> elem(1)
tz_info = Timex.Timezone.get(tz, time)
time_err = Timex.Timezone.convert(time, tz_info)
#>>  {:error, {:could_not_resolve_timezone, "America/New_York", 63687953542, :wall}}
```

### Description of issue

 When the specific time falls within the skipped dst hour tzdata is unable to match the provided and invalid wall to a period entry.

- What are the expected results?
  I would expect either an Ambigious response (the two date times that have the same utc time) or a valid date time. 
 
 For this case the expected output would be `#DateTime<2018-03-11 01:12:22.725-05:00 EST America/New_York>`

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

  Yes. It's a bug in the wall set logic the gregorian time plus delta falls into an invalid range. 

  I have a very crude temporary workaround as follows, 

  
```elixir
  def convert(%DateTime{} = date, %TimezoneInfo{full_name: name} = tz) do
    # Calculate the difference between `date`'s timezone, and the target timezone
    delta = diff(date, tz)
    secs = Timex.to_gregorian_seconds(date) + delta

    # Offset the provided date's time by the difference
    case resolve_case(resolve(name, secs, :wall), delta, date, tz) do
      {:error, {:could_not_resolve_timezone, _tz, _wall, _utc_or_wall}} = err->
        # Check if our conversion fell into the skipped DST hour.
        from_range = case tz.from do
          {_day, {_ymd, _hms} = dt} -> :calendar.datetime_to_gregorian_seconds(dt)
          v -> v
        end

        until_range = case tz.until do
          {_day, {_ymd, _hms} = dt} -> :calendar.datetime_to_gregorian_seconds(dt)
          v -> v
        end

        cond do
          !is_integer(from_range) && is_integer(until_range) -> err
          secs < from_range -> resolve_case(resolve(name, until_range, :wall), delta, date, tz)

         # Probably unneeded since it is the jumped hour that causes the problem. 
          secs >= until_range -> resolve_case(resolve(name, from_range, :wall), delta, date, tz)           
          true -> err
        end
      {:error, _} = err -> err
      v -> v
    end
  end
```

 where resolve_case has the original case statement 

```elixir
  def resolve_case(resolve, delta, date, tz) do
    case resolve do
      {:error, _} = err -> err
      ^tz ->
        {seconds_from_zeroyear, microsecs} = do_shift(date, delta)
        {{y,m,d},{h,mm,s}} = :calendar.gregorian_seconds_to_datetime(seconds_from_zeroyear)
        %DateTime{:year => y, :month => m, :day => d,
          :hour => h, :minute => mm, :second => s,
          :microsecond => microsecs,
          :time_zone => tz.full_name,
          :zone_abbr => tz.abbreviation,
          :utc_offset => tz.offset_utc,
          :std_offset => tz.offset_std}
      %TimezoneInfo{} = new_zone ->
        delta = diff(date, new_zone)
        {seconds_from_zeroyear, microsecs} = do_shift(date, delta)
        {{y,m,d},{h,mm,s}} = :calendar.gregorian_seconds_to_datetime(seconds_from_zeroyear)
        %DateTime{:year => y, :month => m, :day => d,
          :hour => h, :minute => mm, :second => s,
          :microsecond => microsecs,
          :time_zone => new_zone.full_name,
          :zone_abbr => new_zone.abbreviation,
          :utc_offset => new_zone.offset_utc,
          :std_offset => new_zone.offset_std}
      %AmbiguousTimezoneInfo{before: before_tz, after: after_tz} ->
        before_delta = diff(date, before_tz)
        {before_shifted, before_us} = do_shift(date, before_delta)
        after_delta = diff(date, after_tz)
        {after_shifted, after_us} = do_shift(date, after_delta)
        {{y,m,d},{h,mm,s}} = :calendar.gregorian_seconds_to_datetime(before_shifted)
        before_dt = %DateTime{:year => y, :month => m, :day => d,
          :hour => h, :minute => mm, :second => s,
          :microsecond => before_us,
          :time_zone => before_tz.full_name,
          :zone_abbr => before_tz.abbreviation,
          :utc_offset => before_tz.offset_utc,
          :std_offset => before_tz.offset_std}
        {{y,m,d},{h,mm,s}} = :calendar.gregorian_seconds_to_datetime(after_shifted)
        after_dt = %DateTime{:year => y, :month => m, :day => d,
          :hour => h, :minute => mm, :second => s,
          :microsecond => after_us,
          :time_zone => after_tz.full_name,
          :zone_abbr => after_tz.abbreviation,
          :utc_offset => after_tz.offset_utc,
          :std_offset => after_tz.offset_std}
        %AmbiguousDateTime{:before => before_dt, :after => after_dt}
    end
  end
```

**Comment by bismark** [comment]
For reference, moment.js handles this as follows:

```
> moment('2018-03-11T06:12:22.725Z').tz("America/New_York").format()
'2018-03-11T01:12:22-05:00'
```

**Comment by arfl** [comment]
Even stranger behavior is: 
```
# 31.03.2019 is the day of the switch to summer time
iex(17)> datetime = Timex.to_datetime({{2019, 3, 31}, {4, 0, 0}}, "Europe/Berlin")
#DateTime<2019-03-31 04:00:00+02:00 CEST Europe/Berlin>

iex(18)> Timex.Timezone.convert(datetime, "Europe/Berlin")
{:error, {:could_not_resolve_timezone, "Europe/Berlin", 63721216800, :wall}}
```
4 o'clock does not fall into the missing hour, but internally, there seems to be some kind of conversion to UTC time, which falls into the missing hour. So, timex returns here `could_not_resolve_timezone`...

**Comment by naag** [comment]
We also experienced this issue during the change from CET to CEST in timezone Europe/Berlin.

It comes down to the interaction of `Timex.Protocol.to_seconds/2` for `DateTime`, which always returns "gregorian seconds" since year 0, but subtracting the UTC offset in seconds from that number. Later, that number of gregorian seconds is input into Tzdata as a `:wall` time and not a `:utc` time, which is why Tzdata returns the wrong timezone period.

Unfortunately we were not able to come up with a fix which does not break some test. @bitwalker in case you're interested in a pull request, we'd be willing to put in some more time and work this out.

**Comment by dtrieschnigg** [comment]
Ok, I ran into a similar problem:
```
iex> "2019-03-31T04:41:55.279+02:00" 
  |> Timex.parse!("{ISO:Extended}") 
  |> Timex.to_datetime("Europe/Amsterdam")
{:error, {:could_not_resolve_timezone, "Europe/Amsterdam", 63721219315, :wall}}
```

I am now using the following workaround:
```
iex> "2019-03-31T04:41:55.279+02:00" 
  |> Timex.parse!("{ISO:Extended}") 
  |> Timex.to_datetime(:utc) 
  |> Timex.to_datetime("Europe/Amsterdam")
#DateTime<2019-03-31 04:41:55.279+02:00 CEST Europe/Amsterdam>
```
Apparently, first "removing" the timezone and then "adding" does work in getting the proper localized time.

**Comment by dtrieschnigg** [comment]
@noizu 
> ```elixir
> tz = "America/New_York"
> time = DateTime.from_iso8601("2018-03-11T06:12:22.725Z") |> elem(1)
> tz_info = Timex.Timezone.get(tz, time)
> time_err = Timex.Timezone.convert(time, tz_info)
> #>>  {:error, {:could_not_resolve_timezone, "America/New_York", 63687953542, :wall}}
> ```
Here's the fix:
```elixir
time  |> Timex.to_datetime(:utc) |> Timex.to_datetime(tz)
#DateTime<2018-03-11 01:12:22.725-05:00 EST America/New_York>
```

**Comment by noizu** [comment]
Noted Dolf,  I have some special libraries that do their best to work around the issue, although sometimes even this fails. Time to utc, although it may be an error on my end. I have a high transactional volume so billions and billions of comparisons per hour force me to do some optimization tweaks to keep cpu reasonable.

**Comment by dtrieschnigg** [comment]
Now I am quite curious how you work around the problem.
Perhaps it's faster to first try the first approach and when it fails to have a fallback via utc.

**Comment by noizu** [comment]
Not convinced my solution is any better than your fix. I'm in China for a bit, when I get back I'll dig into and update this ticket with what I find and what my approach was ^_^.

**Comment by bitwalker** [comment]
The issues in this thread should all be address in master. If not, please open new issues to keep things organized
