### ISSUE TITLE
Timex shift new year bug

### ISSUE THREAD

**Issue by gbxl** [bitwalker/timex#498]
### Steps to reproduce

- Adjusting for what day of the year you are, aim for a Timex shift that would barely put you into the previous year.
- E.G. On the 3rd of January 2019, aim for a `Timex.shift(days: -3)`

### Description of issue

- What are the expected results?
Expect shift to move the date by the given amount of time

Yet, on this day (Thu Jan 3rd 2019) if you run:

```
Timex.now() |> Timex.shift(days: -2)
#DateTime<2019-01-01 20:51:58.921654Z>

Timex.now() |> Timex.shift(days: -3)
#DateTime<2019-01-01 20:52:01.313790Z>
```

Which clearly should not be the case!
I am not sure whether this is a Timex bug or a bug in a dependency used by Timex

**Comment by bitwalker** [comment]
Fixed in 3.5.0
