### ISSUE TITLE
Relative date parser

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/timex#5]
Given a relative statement about time, parse a date/time from it. Examples:

- "two days ago"
- "three hours past noon on friday"
- "7 minutes ago"
- "3:00pm on Monday"

And the list goes on. Need to establish what valid phrases can be composed of, and write a new tokenizer for these relative date strings.

**Comment by bitwalker** [comment]
I'm closing this for now, as I see it being implemented as a third-party plugin for timex at this time, but if anyone is interested in it, let me know and I'll maybe play around with getting it started.

**Comment by sergiotapia** [comment]
@bitwalker Where is this plugin you were talking about? I'm trying to parse a string from HTML that looks like: `"22 days ago"` into a proper DateTime object to persist in my database.

In Rail's land with Chronic I can go: `Chronic.parse(string)` - is this something Timex can do today? I know this is a pretty stale thread.

**Comment by bitwalker** [comment]
@sergiotapia IIRC it was [this one](https://github.com/teifion/human_time)
