### ISSUE TITLE
Possible to extract an tuple with the datetime from Timex?

### ISSUE THREAD

**Issue by thestonefox** [bitwalker/timex#50]
Is it possible given a Timex call to return the created data-time as a tuple?

e.g.

Date.from({{2015,06,12},{09:00:00}})
|> Date.as_tuple()

would export: {{2015,06,12},{09:00:00}}

(reason is I want to do more processing on the data using Timex but then get a tuple at the end)

**Comment by bitwalker** [comment]
DateTime's are structs, which you can pattern match on easily, is there a particular reason you wish to have a tuple?

**Comment by thestonefox** [comment]
I want to create an Ecto.DateTime which can be done using Ecto.DateTime.from_erl(args) and the args are a tuple of the date and time.

**Comment by bitwalker** [comment]
Ah ok, well you can use `DateConvert.to_erlang_datetime(datetime)` which will produce an Erlang datetime tuple.

**Comment by thestonefox** [comment]
Cool, thanks very much for the info! :)

**Comment by bitwalker** [comment]
No problem :)
