### ISSUE TITLE
Gettext locale not used by default

### ISSUE THREAD

**Issue by tarzan** [bitwalker/timex#500]
By default the default locale of Timex is used, which renders `Timex.Translator.with_locale` and the putting of a specific locale kinda useless unless you specifically use the `lformat` functions over `format`. See the test below for a concrete example of how I would expect it to work.

### Steps to reproduce

- API function called
`Timex.Translator.with_locale` and `Timex.format/2`
- Arguments provided
Any of the supported language strings and some datetime string that needs localization. 

### Description of issue

- What are the expected results?

I would expect the following test to pass:
```ex
test "with_locale macro uses the specified locale" do
  use Timex
  duration = Duration.from_seconds(Timex.to_unix({2016, 2, 29}))

  in_dutch =
    Timex.Translator.with_locale "nl" do
      Timex.format_duration(duration, :humanized)
    end

  assert in_dutch == "46 jaren, 2 maanden, 1 week, 3 dagen"
end
```
- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

I am not certain this is a bug, but we currently use Timex in our multi language app and we would like to sync the language that is being used, i.e. we use a Plug in our Phoenix app to fetch the preferred language of the user and call (our app's own) `Gettext.put_locale/1`. It would be awesome to set the locale of Timex at that same time as well. Instead we would need to use `lformat` everywhere and fetch the current user's locale at that time as well. Might be that we're missing something here. Any other suggestions are greatly appreciated!

**Comment by bitwalker** [comment]
As mentioned in the [PR](#501), I think your change is the right one, but I am concerned about it potentially breaking people relying on the existing behavior, even if it is unexpected. Can anyone else using locales here chime in and let us know if you agree with this change being made? 

@tarzan On second though though, if we make it a config option until 4.0, you could get the desired behavior without it being a breaking change, and in 4.0 we can make it the default and remove the config option. Thoughts?

**Comment by Plus17** [comment]
Hi, my 2 cents with the same problem: I ended up doing the following (for now):
```elixir
Application.put_env(:timex, :default_locale, "es")
Timex.format!(Date.utc_today(), "%d de %B, de %Y", :strftime)
```
