### ISSUE TITLE
Timex.shift/2 returns invalid results

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#507]
### Steps to reproduce

- API function called: `Timex.shift/2`
- Arguments provided: 
~~~
[~N[2001-03-01T17:27:00] |> Timex.Timezone.convert("Etc/GMT-11") |> Timex.set(day: 1), months: 1]
~~~
- Version: `3.5.0`

### Description of issue

- What are the expected results (works in `3.4.1`)?

The target time `2001-03-01 04:27:00+11:00 +11 Etc/GMT-11` shifted by month returns:
`2001-04-01 04:27:00+11:00 +11 Etc/GMT-11`

~~~elixir
~N[2001-03-01T17:27:00] |> Timex.Timezone.convert("Etc/GMT-11") |> Timex.set(day: 1) |> Timex.shift(months: 1)
#DateTime<2001-04-01 04:27:00+11:00 +11 Etc/GMT-11>
~~~

- Actual results:

The target time `2001-03-01 04:27:00+11:00 +11 Etc/GMT-11` shifted by month returns:
`2001-03-29 04:27:00+11:00 +11 Etc/GMT-11`

~~~elixir
~N[2001-03-01T17:27:00] |> Timex.Timezone.convert("Etc/GMT-11") |> Timex.set(day: 1) |> Timex.shift(months: 1)
#DateTime<2001-03-29 04:27:00+11:00 +11 Etc/GMT-11>
~~~

### Comments
To ensure correctness, even for such a corner cases I would recommend property based tests - that is how we are discovering these bugs. There is even a small PR which introduces some basic ones - https://github.com/bitwalker/timex/pull/480

**Comment by sbacarob** [comment]
Currently working with version `3.4.2` here and having problems as well with the results of `Timex.shift/2`

## Steps to reproduce:

You can reproduce the error by shifting 10 weeks into the past

```elixir
Timex.now("US/Pacific") |> Timex.shift(weeks: -10)
```

Running this today (2019-02-11), the expected date would be `2018-12-03`. However, it returns:

```elixir
#DateTime<2018-12-05 11:22:51.840225-08:00 PST US/Pacific>
```

I thought it might have to do with the time zone, but I tried with no time zone and the result was exactly the same. Tried with `days: -70` instead, and got the same result once more.

**Comment by pozhega** [comment]
I had the similar issue with the `3.4.2` version this morning (NOTE: March 1st). My tests started to fail after midnight as the result of getting the same datetime from `Timex.shift(days: -1)` call. The issue was also reproducible with timezone declaration. 

```
iex(1)> Timex.now()
#DateTime<2019-03-01 11:50:59.872589Z>
iex(2)> Timex.shift(Timex.now(), days: -1)
#DateTime<2019-03-01 11:43:45.655550Z>
iex(3)> Timex.shift(Timex.now(), days: -2)
#DateTime<2019-02-28 11:43:49.558945Z>
iex(4)> Timex.now("Europe/Belgrade")
#DateTime<2019-03-01 13:00:09.457308+01:00 CET Europe/Belgrade>
iex(5)> Timex.now("Europe/Belgrade") |> Timex.shift(days: -1)
#DateTime<2019-03-01 13:00:21.614074+01:00 CET Europe/Belgrade>
```

After I've updated Timex to version `3.5` the issue was solved.

```
iex(1)> Timex.now() |> Timex.shift(days: -1)
#DateTime<2019-02-28 12:12:57.860044Z>
```

**Comment by mkorszun** [comment]
The problem still exists in `3.5.0`
