### ISSUE TITLE
Timex.shift(days: X) incorrect for shift of -1 and 0

### ISSUE THREAD

**Issue by jedeleh** [bitwalker/timex#513]
### Steps to reproduce

```
iex> Timex.now()
    |> Timex.shift(days: -1)
    |> IO.inspect
#DateTime<2019-03-01 16:45:31.245173Z>
```

```
iex> Timex.now()
    |> Timex.shift(days: 0)
    |> IO.inspect
#DateTime<2019-03-01 16:45:31.245397Z>
```

### Description of issue

I would expect shift -1 to show Feb 28th

I am not sure, but perhaps this is a leap year issue? This code worked as expected until just today.

Also, if you shift -2, -3, etc, it shows the date off by one forward as well.

shift -3  = #DateTime<2019-02-27 16:45:31.242491Z>
shift -2  = #DateTime<2019-02-28 16:45:31.244937Z>
shift -1   = #DateTime<2019-03-01 16:45:31.245173Z>
shift 0    = #DateTime<2019-03-01 16:45:31.245397Z>

**Comment by iaguirre88** [comment]
Which version of Timex are you using? I was unable to reproduce it.

```elixir
{:ok, datetime, 0} = DateTime.from_iso8601("2019-03-01 16:45:31.245397Z")
Timex.shift(datetime, days: -1)

#DateTime<2019-02-28 16:45:31.245397Z>
```

**Comment by deepankar-j** [comment]
In cast it helps anyone else, I encountered this issue when using Timex v3.1.    Upgrading Timex to v3.5 fixed the issue.
