### ISSUE TITLE
lformat march month representation for pt locale returned is not a String

### ISSUE THREAD

**Issue by fSergio101** [bitwalker/timex#515]
### Steps to reproduce

- [`Timex.lformat/4`](https://hexdocs.pm/timex/Timex.html#lformat/4)
- Arguments provided:
```
  datetime =  Timex.Parse.DateTime.Parser.parse("2019-03-06T12:19:38Z", "{ISO:Extended:Z}")
  format = '%B'
  locale = 'pt'
  formatter = :strftime
```

### Description of issue

- Expected `{:ok, "Março"}` but got `{:ok, <<77, 97, 114, 231, 111>>}`
- Using locale `pt_BR` instead of `pt`, it works as expected, But looks like using `pt` locale, for any unknown reason, representation for `ç` given is `231` instead of `195, 167` that is the expected one to be a valid `String`

**Comment by bitwalker** [comment]
This is fixed as of 3.7
