### ISSUE TITLE
Bug when formatting with %W directive

### ISSUE THREAD

**Issue by SemmelK** [bitwalker/timex#517]
The following function calls of Timex.format return inconsistent results:

`{{2019, 1, 6}, {0,0,0}} |> Timex.format!("%W", :strftime)`
Actual result: "00"
Expected result: "01"

`{{2019, 1, 6}, {0,0,1}} |> Timex.format!("%W", :strftime)`
Actual result: "01"
Expected result: "01"

I think i have an found the responsible error in the datetime formatter. Please let me know if you are interested in a pull request.

**Comment by bitwalker** [comment]
This isn't an error, `%W` starts with 0 as the first week of the year, and the date you've provided occurs in the week starting December 31, 2018, so the result of 0 is correct here.
