### ISSUE TITLE
    elixir: "~> 1.5" error

### ISSUE THREAD

**Issue by smartdevbr** [bitwalker/timex#526]
### Steps to reproduce

iex -S mix

### Description of issue

Tzdata.App.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Tzdata.EtsHolder, {{:badmatch, {:error, {:read_error, {:file_error, [99, 58, 47, 85, 115, 101, 114, 115, 47, 111, 108, 105, 118, 101, 105, 114, 97, 46, 103, 117, 115, 116, 97, 118, 111, 47, 68, 101, 115, 107, 116, 111, 112, 47, ...], :enoent}}}}, [{Tzdata.EtsHolder, :load_ets_table, 1, [file: 'lib/tzdata/ets_holder.ex', line: 59]}, {Tzdata.EtsHolder, :load_release, 0, [file: 'lib/tzdata/ets_holder.ex', line: 52]}, {Tzdata.EtsHolder, :init, 1, [file: 'lib/tzdata/ets_holder.ex', line: 14]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}}
            (tzdata) lib/tzdata/tzdata_app.ex:15: Tzdata.App.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
** (Mix) Could not start application tzdata: exited in: Tzdata.App.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Tzdata.EtsHolder, {{:badmatch, {:error, {:read_error, {:file_error, [99, 58, 47, 85, 115, 101, 114, 115, 47, 111, 108, 105, 118, 101, 105, 114, 97, 46, 103, 117, 115, 116, 97, 118, 111, 47, 68, 101, 115, 107, 116, 111, 112, 47, ...], :enoent}}}}, [{Tzdata.EtsHolder, :load_ets_table, 1, [file: 'lib/tzdata/ets_holder.ex', line: 59]}, {Tzdata.EtsHolder, :load_release, 0, [file: 'lib/tzdata/ets_holder.ex', line: 52]}, {Tzdata.EtsHolder, :init, 1, [file: 'lib/tzdata/ets_holder.ex', line: 14]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}}
            (tzdata) lib/tzdata/tzdata_app.ex:15: Tzdata.App.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4

**Comment by bitwalker** [comment]
Timex requires at least 1.6
