### ISSUE TITLE
Timex.shift/2 fails for datetimes close to DST change

### ISSUE THREAD

**Issue by Coffei** [bitwalker/timex#533]
### Steps to reproduce
```
iex(1)> Timex.shift(Timex.to_datetime(~N[2019-03-31T00:29:55], "Europe/Prague"), hours: 2)
{:error, {:could_not_resolve_timezone, "Europe/Prague", 63721218595, :wall}}
```
This is because `~N[2019-03-31T02:29:55]` doesn't exist in `Europe/Prague` tz, it's a DST change when at 2AM the time is changed to 3AM. However, I was under the impression that `shift` is supposed to skip these DST changes. Actually, the docs mention this should work, as per the example here: https://hexdocs.pm/timex/Timex.html#shift/2-shifting-across-timezone-changes

Is this expected behaviour or am I missing something? Is there an alternative shift method to skip over DST changes?

**Comment by Coffei** [comment]
Well, it turns out I was running older version of timex so I upgraded to latest and the example above now works. However, my code still crashes but now at even weirder situation.

Added the following test to `shift_test.exs` in timex and it fails there too.
```
  test "shift should skip over DST time changes" do
    date = Timex.shift(Timex.to_datetime(~N[2019-03-31 04:29:55], "Europe/Prague"), hours: 1)
    expected = ~N[2019-03-31T05:29:55] |> Timex.to_datetime("Europe/Prague")
    assert date == expected
  end
```
Don't see any reason why it should fail, so I'd assume this is a bug.

**Comment by Coffei** [comment]
Tracked it down to the following calls
```
Timex.timezone("Europe/Prague", Timex.to_datetime(~N[2019-03-31 04:29:55], "Europe/Prague"))
```
```
Timex.Timezone.resolve("Europe/Prague", 63721218595)
```
and finally 
```
Tzdata.periods_for_time("Europe/Prague", 63721218595, :wall)
```

**Comment by hrubi** [comment]
Likely the same as https://github.com/bitwalker/timex/issues/514 and https://github.com/bitwalker/timex/issues/491

**Comment by bitwalker** [comment]
Fixed in master

**Comment by Coffei** [comment]
Thank you!
