### ISSUE TITLE
precision is lost when converting from NaiveDateTime to DateTime via timezone

### ISSUE THREAD

**Issue by norpan** [bitwalker/timex#537]
### Steps to reproduce

```
iex(14)> ~N[2000-01-01 00:00:00.123456] |> Timex.to_datetime("Europe/Stockholm")
#DateTime<2000-01-01 00:00:00.123456+01:00 CET Europe/Stockholm>
iex(15)> ~N[2000-01-01 00:00:00.123000] |> Timex.to_datetime("Europe/Stockholm")
#DateTime<2000-01-01 00:00:00.123+01:00 CET Europe/Stockholm>
```
### Description of issue

- What are the expected results?
I expect the precision to be maintained in the conversion, so that I get
```
#DateTime<2000-01-01 00:00:00.123000+01:00 CET Europe/Stockholm>
```
in the second case.

I have microsecond precision, it's just that it happens to be 000 sometimes.

**Comment by bitwalker** [comment]
This is now fixed in master, will be in the next release
