### ISSUE TITLE
Parse format not documented

### ISSUE THREAD

**Issue by mgwidmann** [bitwalker/timex#538]
### Description of issue

- What are the expected results?
When parsing a date string it should be easy to find the table for constructing the parsing format string.
For example
```
Timex.parse(date_string, "{YYYY}-????what goes here???")
```
Checking a few locations there is no complete listing of all parsing format strings.
https://hexdocs.pm/timex/getting-started.html (no mention)
https://hexdocs.pm/timex/parsing.html (few examples but no complete listing)
https://hexdocs.pm/timex/faq.html (no mention)
https://hexdocs.pm/timex/Timex.html#content (examples but no complete listing)

The following shows the strf time version, but is not the same syntax:
https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Strftime.html

**Comment by bitwalker** [comment]
You're looking for [this page](https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html#content). It used to be linked to directly from one of the main pages, not sure what happened there, but you are right that we need it to be documented clearly, I'll update the docs today.
