### ISSUE TITLE
Feature: Automatic integration with Ecto, as per calecto

### ISSUE THREAD

**Issue by ewildgoose** [bitwalker/timex#54]
I feel tied between "calendar" and "timex".  I need to parse a datestring for which timex seems to have far stronger support. But I then wish to write these to a database, where the automatic integration of calendar with ecto is neat (calecto project).  

Could you consider adding an equivalent to calecto (timecto...). It appears to boil down to integrating the ecto protocol?

Thanks for listening!

**Comment by bitwalker** [comment]
@ewildgoose I was just thinking about Ecto integration yesterday, so I'll bump this up in priority a bit and take a look today :)

**Comment by bitwalker** [comment]
@ewildgoose I've pushed a plugin to hex.pm for Ecto, called `timex_ecto`. Would you be willing to test it out and let me know how it can be improved? The repo and docs are located [here](https://github.com/bitwalker/timex_ecto).

**Comment by bitwalker** [comment]
Since this has been pushed to hex, and it seems that people are using it without reported issues so far, I'm closing this one. @ewildgoose please let me know if you run into any problems over on the timex_ecto repository!
