### ISSUE TITLE
Changelog stops at 3.5.1 (which is not on hex.pm)

### ISSUE THREAD

**Issue by schnittchen** [bitwalker/timex#541]
The fact 3.5.1 was not released confused me at first. The Changelog seems to lag behind.

**Comment by bitwalker** [comment]
I generally haven't had time to update the changelog, so it does lag behind. Until I find time to update it properly, the best bet is always the git log, as I try to keep the git history clean and commits informative enough that it functions as a readable history of changes. Not quite the same as a prepared changelog, but those take more time to produce.

I will make a note in the PR template to add changes to the changelog, perhaps that will help

**Comment by schnittchen** [comment]
Thank you Paul! <3
