### ISSUE TITLE
variable compare

### ISSUE THREAD

**Issue by RazgrizHsu** [bitwalker/timex#543]
Hi, i have code like this..

```
dts = Timex.parse!( "2019-01-01T00:00:00.000Z", "{ISO:Extended:Z}" )
now = Timex.parse!( "2019-01-01T00:00:00.100Z", "{ISO:Extended:Z}" )

dt = Timex.shift( dts, seconds: 5 )
	
if ( dt <= now ) do
	raise ( "why? dt already shift seconds... dt[#{ inspect dt }] now[#{ inspect now }]" )
else
	:ok
end
```

but i thought that such a comparison should be the opposite result…

**Comment by bitwalker** [comment]
In Elixir (and Erlang) the comparison operators do not work with structs, such as `DateTime`. See [this section of the Erlang manual](http://erlang.org/doc/reference_manual/expressions.html#term-comparisons) for details on how those comparison operators work (the actual operators are slightly different than in Elixir, but the behavior of the operators is the same). 

Instead, you need to use the comparison functions provided in the standard library (or the `Timex` APIs, like `compare` or `before?`/`after?`, etc.).

**Comment by RazgrizHsu** [comment]
thank you very much 👍
