### ISSUE TITLE
Format does not work as described

### ISSUE THREAD

**Issue by grufino** [bitwalker/timex#549]
The steps to reproduce the issue is simple running or reading Timex test case:

format_default_test.exs

Documentation:

https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html#format!/2

> {ASN1:GeneralizedTime} - YYYYMMDD<time>. Full 4-digit year date and time in local timezone without separators and with optional fractional seconds (e.g. **20070813134801.032**)

Actual test:

```
test "format ASN1 Generalized Time" do
    local = {{2013,3,5},{23,25,19}}
    date = Timex.to_datetime(local, :local)

    assert { :ok, "20130305232519" } = format(date, "{ASN1:GeneralizedTime}")

    date = Timex.to_datetime(local)

    assert { :ok, "20130305232519" } = format(date, "{ASN1:GeneralizedTime}")
  end
```

Expected according to documentation

```
test "format ASN1 Generalized Time" do
    local = {{2013,3,5},{23,25,19}}
    date = Timex.to_datetime(local, :local)

    assert { :ok, "20130305232519.000" } = format(date, "{ASN1:GeneralizedTime}")

    date = Timex.to_datetime(local)

    assert { :ok, "20130305232519.000" } = format(date, "{ASN1:GeneralizedTime}")
  end
```

As stated above, the fraction of seconds are not being shown in this particular format.

**Comment by mikepc** [comment]
I'd like to also point out an error in the formatter documentation:
```
    {RFC3339z} - e.g. 2013-03-05T23:25:19Z
```

```
   iex>  Timex.local  |>  Timex.format!("{RFC3339z}")
  "2019-10-03T13:57:19.550645Z"
```
Researching now how to get rid of those pesky miliseconds

**Comment by bitwalker** [comment]
Your second comment isn't actually an error in the docs - RFC3339 supports fractional seconds, I just didn't use that example in the documentation, but I'm open to changing that to make things clearer of course.

To get rid of milliseconds in the general case, you can use `DateTime.truncate(datetime, :second)`
