### ISSUE TITLE
DateFormat.parse with RFC1123z problem

### ISSUE THREAD

**Issue by b0oh** [bitwalker/timex#55]
Erlang 17.5
Elixir 1.0.4
Timex 0.14.3

If I take example from DateFormat file for RFC 1123 format
`Timex.DateFormat.parse("Tue, 05 Mar 2013 23:25:19 +0200", "{RFC1123z}")` everything works fine but if I change `+0200` to `+0100` like `Timex.DateFormat.parse("Tue, 05 Mar 2013 23:25:19 +0100", "{RFC1123z}")` I got an error:
```
** (MatchError) no match of right hand side value: {:error, "No timezone found for: Etc/GMT-100"}
    lib/timezone/timezone.ex:147: Timex.Timezone.diff/2
    lib/date/date.ex:380: Timex.Date.to_secs/2
    lib/timezone/timezone.ex:115: Timex.Timezone.get/2
    lib/timezone/timezone.ex:136: Timex.Timezone.convert/2
    lib/parsers/dateformat/parser.ex:106: Timex.Parsers.DateFormat.Parser.do_parse/4
```

**Comment by bitwalker** [comment]
I'll take a look ASAP!

**Comment by bitwalker** [comment]
@b0oh I've also pushed a new release `0.15.0` with this fix amongst many others.

**Comment by b0oh** [comment]
@bitwalker thanks!
