### ISSUE TITLE
Shifting back over exactly the one missing DST hour

### ISSUE THREAD

**Issue by schnittchen** [bitwalker/timex#550]
### Steps to reproduce

```
    time = DateTime.from_unix!(1553994000) |> Timex.Timezone.convert("Europe/Berlin")
    assert time != Timex.shift(time, hours: -1) 
```

The mechanical shift by one hour produces a nonexisting hour, which is fixed up here https://github.com/bitwalker/timex/blob/master/lib/datetime/datetime.ex#L260 by moving back one hour into the future.

**Comment by bitwalker** [comment]
This is fixed in 3.7
