### ISSUE TITLE
Wrong compare result to_datetime

### ISSUE THREAD

**Issue by Strapidustra** [bitwalker/timex#551]
### Steps to reproduce
`iex(3)> Timex.to_datetime(~N[2019-08-06 18:01:00], "Europe/Saratov") < Timex.now("Europe/Saratov")`
`true`
Wrong compare result
`iex(4)> Timex.to_datetime(~N[2019-08-06 18:55:00], "Europe/Saratov") < Timex.now("Europe/Saratov")`
`true`
`iex(5)> Timex.now("Europe/Saratov")`
`#DateTime<2019-08-06 18:09:24.837391+04:00 +04 Europe/Saratov>`
check again
`iex(6)> Timex.to_datetime(~N[2019-08-06 18:55:00], "Europe/Saratov") > Timex.now("Europe/Saratov")`
`false`
Checking datetime
`iex(7)> Timex.to_datetime(~N[2019-08-06 18:55:00], "Europe/Saratov")
#DateTime<2019-08-06 18:55:00+04:00 +04 Europe/Saratov>`

**Comment by lucazulian** [comment]
@Strapidustra as stated in the documentation
```
We call them "naive" because this datetime representation does not have a time zone. This means the datetime may not actually exist in certain areas in the world even though it is valid.
```
So in the case 'Timex.to_datetime(~N[2019-08-06 18:01:00], "Europe/Saratov")` what you are doing is to crate a new DateTime attaching the specified timezone. To me the comparisons you provided are correct. Do you agree? Am I missing something?

**Comment by bitwalker** [comment]
You can't compare DateTimes in this manner, you must use Timex comparison functions, or the `compare` functions provided by the standard library.
