### ISSUE TITLE
Ambiguous ambiguous date time

### ISSUE THREAD

**Issue by mindreader** [bitwalker/timex#565]
### Steps to reproduce

Timex: 3.6.1

```
dt = "2016-10-28 15:50:00+000" |> Timex.parse!("{ISO:Extended}")
time_zone = "Europe/Istanbul"
dt |> Timex.to_datetime(time_zone)

#<Ambiguous(#<Ambiguous(#DateTime<2016-10-28 18:50:00+03:00 +03 Europe/Istanbul> ~ #DateTime<2016-10-28 18:50:00+03:00 EEST Europe/Istanbul>)> ~ #<Ambiguous(#DateTime<2016-10-28 18:50:00+03:00 +03 Europe/Istanbul> ~ #DateTime<2016-10-28 18:50:00+03:00 EEST Europe/Istanbul>)>)>
```
### Description of issue

- What are the expected results?
I expected a date time or at worst an ambiguous date time but what I got was an ambiguous date time where both before and after are also ambiguous, which probably shouldn't happen.  I think the top level before and after are the same and the befores and afters in the sub ambiguous date times are what I would have expected at the top level.

- If you are certain this is a bug in Timex, do you have references I

I'm not really sure what happened in turkey around this time.

"2016-09-06 22:00:00+000" is where it gets weird.
"2016-10-29 21:59:00+000" goes back to normal.

Best guess from reading around.  Turkey was on dst.  Then they changed the law to just continue using it forever but people didn't actually entirely take action on it until a month later.

**Comment by lucazulian** [comment]
Hi @mindreader,
I've tried to reproduce the issue but what I get is something like that:
```
iex(23)> dt = "2016-10-28 15:50:00+000" |> Timex.parse!("{ISO:Extended}")
~U[2016-10-28 15:50:00Z]
iex(24)> time_zone = "Europe/Istanbul"
"Europe/Istanbul"
iex(25)> dt |> Timex.to_datetime(time_zone)
#DateTime<2016-10-28 18:50:00+03:00 +03 Europe/Istanbul>
```
As you can see I don't receive an `Ambiguous` DateTime.
Versions of Erlang and Elixir are the following:
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
IEx 1.9.1 (compiled with Erlang/OTP 20) 
```
Can you provide other information in order to reproduce the issue?

**Comment by mindreader** [comment]
Interesting!  It still happens for me.

    Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
    IEx 1.9.4 (compiled with Erlang/OTP 22)

**Comment by mindreader** [comment]
I figured this one out.  We were locked to tzdata 0.5.21 (also exhibited with 0.5.22)

It is a combination of that older version of tzdata, timex and newer time zone info.  I managed to catch it at startup.

```
(search)`t': Timex.now("America/Whitehorse")
15:09:29.320 [info]  tzdata release in place is from a file last modified Tue, 26 Mar 2019 05:40:14 GMT. Release file on server was last modified Fri, 24 Apr 2020 04:15:20 GMT.
 
#DateTime<2020-04-27 08:09:29.427680-07:00 PDT America/Whitehorse>

15:09:30.721 [info]  Tzdata has updated the release from 2019a to 2020a

iex(devapi@b8ed2a70716a)2> Timex.now("America/Whitehorse")
#<Ambiguous(#<Ambiguous(#DateTime<2020-04-27 08:09:30.794756-07:00 MST America/Whitehorse> ~ #DateTime<2020-04-27 08:09:30.794756-07:00 PDT America/Whitehorse>)> ~ #<Ambiguous(#DateTime<2020-04-27 08:09:30.794756-07:00 MST America/Whitehorse> ~ #DateTime<2020-04-27 08:09:30.794756-07:00 PDT America/Whitehorse>)>)>
```

For me it is fixed by upgrading to the 1.x versions of tzdata.
