### ISSUE TITLE
Gettext 0.17.2 update breaks Timex.Translator

### ISSUE THREAD

**Issue by sparta-developers** [bitwalker/timex#569]
### Steps to reproduce

Update project which uses Timex to Gettext 0.17.2.

### Description of issue

[This](https://github.com/elixir-gettext/gettext/commit/e2a51e9ba39140313b5e494b78e4bccaaa22d24e) commit in gettext appears to get rid of `Gettext.lgettext/4`, and replaces it with `Gettext.lgettext/5`. Unfortunately, `Timex.Translator.get_domain_text/3` uses `lgettext/4`.

```
  datetime |> Format.format(format: "%H:%M %p")

     ** (UndefinedFunctionError) function Timex.Gettext.lgettext/4 is undefined or private
     stacktrace:
       (timex) Timex.Gettext.lgettext("en", "day_periods", "AM", %{})
       (timex) lib/l10n/translator.ex:156: Timex.Translator.get_domain_text/3
       (timex) lib/l10n/translator.ex:148: Timex.Translator.get_day_periods/1
       (timex) lib/format/datetime/formatter.ex:616: Timex.Format.DateTime.Formatter.format_token/6
       (timex) lib/format/datetime/formatters/default.ex:183: Timex.Format.DateTime.Formatters.Default.do_format/4
       (timex) lib/format/datetime/formatter.ex:52: Timex.Format.DateTime.Formatter.lformat!/4
```

I'm not sure if this is an issue with gettext, as this is a breaking change that I would not expect from a `0.17.1` to `0.17.2` bump. On the other hand, it might be easier to fix as the consumer?

Thanks!

**Comment by glaucomorandini** [comment]
I'm with the same problem, but I didn't updated the gettext. I'm using gettext version 0.17.0 and timex version 3.6.

**Comment by rupurt** [comment]
Code to lock to working version while this is resolved:

```elixir
# ...mix.exs
defp deps do
   [
      # https://github.com/bitwalker/timex/issues/569
      # {:gettext, "~> 0.17"},
      {:gettext, "0.17.1"}
   ]
end
```

**Comment by Wijnand** [comment]
A newer version has been released now.
See also https://github.com/elixir-gettext/gettext/issues/236

**Comment by bitwalker** [comment]
Is this still an issue with the latest version that was just released? Seems like an unintentional breaking change, but if we have to adapt, that's fine, assuming the functionality is present via another API.

**Comment by sparta-developers** [comment]
@bitwalker It looks as if Gettext 0.17.3 fixes this issue, but you might want to take a look at the comments in their issue. Jose suggests that `lgettext` is a private API, and that they might change it in the future.

Thanks for following up with this! If you want to close this based on the more recent gettext update, that sounds good. We'll leave this open pending your decision.
