### ISSUE TITLE
{WDmon} and {WDsun} not working?

### ISSUE THREAD

**Issue by Brianvdb** [bitwalker/timex#570]
### Steps to reproduce

```
d = Timex.parse!("2020-01-11T12:00:00+00:00", "{ISO:Extended}")
IO.inspect Timex.format!(d, "{WDmon}")
IO.inspect Timex.format!(d, "{WDsun}")
```

This outputs:

```
"6"
"6"
```

### Description of issue

2020-01-11 is a saturday so I expect `WDmon` to log "5" but instead it logs "6" for both format.

The docs describe this:
```
{WDmon} - weekday, Monday first (0..6, no padding)
{WDsun} - weekday, Sunday first (0..6, no padding)
```

**Comment by Jcambass** [comment]
You're right. I can reproduce this. Now I wonder what the correct behaviour would be.

If we're look into the `Strftime` formatter we'll see that we have similar options but with the correct documentation. https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Strftime.html#content

> %u - weekday, Monday first (1..7)
%w - weekday, Sunday first (0..6)

This formatter uses the same code as the default formatter. So both basically use `Timex.weekday` directly which returns a 1..7(Monday..Sunday) range.

While I personally would favour having both `{WDmon}` and `{WDsun}` returning the same range I think that we should not break the behaviour of the correctly documented `Strftime` implementation.
Note that the compound directive `{ISOweek-day}` also returns the 1..7(Monday..Sunday) range.

**Comment by doughsay** [comment]
The original behavior was correct I think, and the recent changes have broken things.  See my issue here:  #668, but just for reference:

if you're counting from 1 to 7 starting on Monday:

```
"Mon 1"
"Tue 2"
"Wed 3"
"Thu 4"
"Fri 5"
"Sat 6"
"Sun 7"
```

Or counting from 0 to 6 starting on Sunday:

```
"Sun 0"
"Mon 1"
"Tue 2"
"Wed 3"
"Thu 4"
"Fri 5"
"Sat 6"
```

Saturday is always 6.

I'm proposing that the documentation was wrong for the default formatter, and it should have matched with what is in the strftime formatter.
