### ISSUE TITLE
RFC: Add yesterday to relative formatter

### ISSUE THREAD

**Issue by heimann** [bitwalker/timex#578]
First of all, I :heart: this package, it's fantastic.

I use the relative formatter a lot and it's so plug and play it almost feels like cheating. However, I wonder if others feel like the `22-36 hours` section https://github.com/bitwalker/timex/blob/741ed40e30bd1af248cc10005dcfe6cd75058a53/lib/format/datetime/formatters/relative.ex#L17 should say `yesterday` instead? `a day ago` sounds awkward to me.

Happy to implement this and submit a PR if maintainers agree

**Comment by bitwalker** [comment]
@heimann Sorry for the long delay in responding to this. Since we already have the translations, I've gone ahead and made this change, it will be in 3.7.2
