### ISSUE TITLE
Is a repository cleanup welcome?

### ISSUE THREAD

**Issue by qhwa** [bitwalker/timex#579]
First of all, thank you for the excellent work on this project. I used it in many projects of mine and really enjoyed it.

It seems that codes are not formatted and the specifications are broken.

### Steps to reproduce

- mix format --check-formatted lib/**/*.ex
- mix dialyzer

### Description of issue

I saw there are some issues open and thought maybe I can help. After cloning the project and running it, I think that maybe a cleanup is a good start, future updates will benefit from it.

But I am not sure whether this is a good idea or not, maybe it will cause a lot of conflicts with other developing branches (although there seem to be no active developing branches). So I open this issue to ask if code formatting with `mix format` and fixing of specifications welcome? If so, I will start work on the master branch and open a pull request later.

What do you think? @bitwalker 

UPDATE: Sorry I was reading the codes on an outdated revision. I see most of the files in the master branch has already been formatted. That's awesome. Things get a lot easier based on your work.

**Comment by bitwalker** [comment]
Additional help keeping the codebase tidy and building clean is always welcome :)
