### ISSUE TITLE
parse timezone failed at osx yosemeti with elixir 1.0.4

### ISSUE THREAD

**Issue by xbinxu** [bitwalker/timex#58]
While calling Date.local, an exception is raised:

```
** (Protocol.UndefinedError) protocol Access not implemented for %Timex.Parsers.ZoneInfo.TransitionInfo{abbrev_index: 0, abbreviation: "N/A", gmt_offset: 32400, is_dst?: true, is_std?: true, is_utc?: false, starts_at: 0}
    (elixir) lib/access.ex:1: Access.impl_for!/1
    (elixir) lib/access.ex:44: Access.get_and_update/3
    (elixir) lib/kernel.ex:1593: Kernel.put_in/3
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
     (timex) lib/parsers/zoneinfo/zoneinfo.ex:133: Timex.Parsers.ZoneInfo.do_parse_transition_info/3
     (timex) lib/timezone/timezone_local.ex:225: Timex.Timezone.Local.parse_tzfile/2
```

System timezone:

```
sudo systemsetup -gettimezone
Password:
Time Zone: Asia/Shanghai
```

**Comment by bitwalker** [comment]
@xbinxu Could you run `ls -l /etc/localtime` so I can see what it's symlinked to? I assume it's the same but I just want to confirm.

**Comment by bitwalker** [comment]
Running `sudo systemsetup -settimezone "Asia/Shanghai"` and `iex> Timezone.local` returns me:

```
%Timex.TimezoneInfo{abbreviation: "CST",
 from: {:saturday, {{1991, 9, 14}, {23, 0, 0}}}, full_name: "Asia/Shanghai",
 offset_std: 0, offset_utc: 480, until: :max}
```

What version of timex are you on just in case I'm testing on the wrong version? If you're on an older one, can you update and test with the latest stable version on hex?

**Comment by bitwalker** [comment]
Judging by the error, this must've been a fairly old version of timex, as the TransitionInfo struct has implemented the Access protocol for quite some time. Can you confirm that?

**Comment by xbinxu** [comment]
@bitwalker,  according to your last message, I tried remove _build folder and re-compile the whole project, the error is gone. 

FYI, I updated timex from 0.13 to 0.15 yesterday and the error occurred. It seems that not all beam files are updated at compile time, I still have no idea about it but this issue can definitely be closed. 

Thank you!
