### ISSUE TITLE
{AM} and {am} mnemonics triggers error :undef

### ISSUE THREAD

**Issue by fcevado** [bitwalker/timex#585]
when using `{AM}` or `{am}` mnemonics triggers error `:undef` but is documented here:
https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html#module-time

```elixir
iex> Timex.now() |> Timex.format("{AM}")
{:error, :undef}

iex> Timex.now() |> Timex.format("{am}")
{:error, :undef}
```

I've tested it alone in the format string or with other mnemonics, always trigger the same error.
version tested: `timex 3.6.1`

**Comment by bitwalker** [comment]
This doesn't appear to be a problem anymore as of 3.7, haven't looked at earlier versions.
