### ISSUE TITLE
Timex.to_datetime truncates microseconds

### ISSUE THREAD

**Issue by turion** [bitwalker/timex#588]
### Steps to reproduce

```
> Timex.to_datetime({{2017, 1, 1}, {0, 0, 0, 0}})
~U[2017-01-01 00:00:00Z]
> Timex.to_datetime({{2017, 1, 1}, {0, 0, 0, 1}})
~U[2017-01-01 00:00:00.000001Z]
```

### Description of issue

I would expect the result of the first call to be `~U[2017-01-01 00:00:00.000000Z]`.

**Comment by bitwalker** [comment]
See discussion in #589 for why this is expected.
