### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by qhwa** [bitwalker/timex#590]
CI is broken after my last pull request. 
https://travis-ci.org/github/bitwalker/timex

Sorry to bring it to the room.

I'm trying to address the reason and will update the progress here.

Current state:

At this point, I noticed that all builds running on **MacOS** failed. However, it is strange that they used to work, oddly with OTP for ubuntu installed.

**Comment by qhwa** [comment]
update:

I think I have found the reason. It seems [Travis does not support erlang prebuilt on osx](https://github.com/travis-ci/travis-build/pull/1130#issuecomment-429654578).

**But why was the CI working before?**

It was `macos` in the Travis CI config, instead of `osx`. So it was mistakenly interpreted as `ubuntu`

I'll open a PR on this issue.

**Comment by bitwalker** [comment]
CI is fixed now that we've migrated to Cirrus
