### ISSUE TITLE
Is the Readme wrong? Missing deps in Mix Release

### ISSUE THREAD

**Issue by Adzz** [bitwalker/timex#593]
### Steps to reproduce

The Readme says [this](https://github.com/bitwalker/timex#adding-timex-to-your-project):

> To use Timex with your projects, edit your mix.exs file and add it as a dependency:
```elixir
defp deps do
  [{:timex, "~> 3.5"}]
end

defp application do
  [applications: [:timex]]
end
```

If I do the above and then make a `mix release` I have deps inexplicably missing from the release (in my case Absinthe and Absinthe plug)

If I remove the `[applications: [:timex]]` the deps appear in the release

Am I missing something obvious? Or should it not just be:

> To use Timex with your projects, edit your mix.exs file and add it as a dependency:
```elixir
defp deps do
  [{:timex, "~> 3.5"}]
end
```

**Comment by aselder** [comment]
When you said `[applications: [:timex]]`, you excluded all other application from running, since they weren't listed. If you don't define the `applications` key, elixir will figure out what to start from your mix.exs file.

**Comment by Adzz** [comment]
Thanks I put a PR to update the README as I don't think users should need to use the applications key at all.
