### ISSUE TITLE
Docs wrongly say timezone offsets are in minutes

### ISSUE THREAD

**Issue by jrusso1020** [bitwalker/timex#596]
### Steps to reproduce
In the https://hexdocs.pm/timex/Timex.TimezoneInfo.html#content docs it says
```
offset_std is the offset in minutes from standard time for this period
offset_utc is the offset in minutes from UTC for this period Spec:
```

However this doesn't appear to be correct, it appears that it is actually in seconds
```
-28800 = Timex.Timezone.get("America/Los_Angeles").offset_utc
3600 = Timex.Timezone.get("America/Los_Angeles").offset_std

utc_timezone = Timex.Timezone.get("Etc/UTC")
pt_timezone = Timex.Timezone.get("America/Los_Angeles")
et_timezone = Timex.Timezone.get("America/New_York")
// To get UTC offset in hours
-7.0 = Timex.Timezone.diff(utc_timezone, pt_timezone) / 60 / 60
-4.0 = Timex.Timezone.diff(utc_timezone, et_timezone) / 60 / 60
```

### Description of issue
- What are the expected results?
The expected results are that the offsets are in the same unit of time as specified in the docs. Either both minutes or both seconds.

**Comment by bitwalker** [comment]
Ah yes, this changed some time back when Elixir introduced its calendar types. Thanks for catching that.
