### ISSUE TITLE
BST is not a valid timezone

### ISSUE THREAD

**Issue by the-kid89** [bitwalker/timex#597]
### Steps to reproduce

{:error, {:invalid_timezone, "BST"}} = Timex.Timezone.get("BST")

### Description of issue

- What are the expected results?
BST should return the same value as UTC +1

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

https://www.timeanddate.com/time/zones/bst

**Comment by bitwalker** [comment]
BST is not a timezone name in the Olson timezone database - it is an abbreviation of a zone name, for a specific time of year, and Timex (and more precisely, `tzdata`) only supports abbreviations for a few zones for legacy reasons, namely their use in POSIX standards, which are limited to the North American abbreviations only as far as I can recall, e.g. `PST`, `MST`, `CST`, `EST`.

What you should use instead is `Europe/London`, which represents the time zone properly across DST boundaries.
