### ISSUE TITLE
Auto-generate TimezoneInfos from Olson tzdata

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/timex#6]
Right now, TimezoneInfos are generated from a list of tuples which were generated from this year's tzdata. This is not maintainable moving forward. My plan for fixing/improving this:

- [x] Write a tzdata parser for the Olson timezone database
- [x] Write a mix task which downloads the most current tzdata, parses it and converts to Elixir terms which are then stored in `priv/tzdata/database.exs`.
- [x] On compilation, read `priv/tzdata/database.exs`, and inline lookups for individual zones.
- [ ] Reimplement Timezone modules using data from the Olson database.

This will make it so that it's trivial to keep Timex up to date with Olson db changes.

**Comment by NhanHo** [comment]
With this approach, it seems like the tzdata is only updated on compilation time, or am I mistaken?

**Comment by bitwalker** [comment]
That's correct, there is a mix task which can be used to update it on demand as well, but it does require re-compilation of timex.
