### ISSUE TITLE
DateFormat not as simple as possible

### ISSUE THREAD

**Issue by hitoridewanai** [bitwalker/timex#60]
As per timex.ex
```
defmodule Timex do
  defmacro __using__(_) do
    quote do
      alias Timex.DateTime
      alias Timex.Date
      alias Timex.Time
      alias Timex.TimezoneInfo
      alias Timex.Timezone
      alias Timex.Format.DateTime.DateFormat
      alias Timex.Date.Convert, as: DateConvert
      alias Timex.Format.Time.TimeFormatter, as: TimeFormat
    end
  end
  @moduledoc File.read!("README.md")
end
```

DateFormat is only easily accessible if I do "use Timex". Would you consider moving the module to "Timex.DateFormat" to be easily accessible (and possibly delegate all the functionality wherever you want)? It used to work and was super easy.

**Comment by bitwalker** [comment]
@hitoridewanai This seems like a pretty reasonable request, so I've made this change in master. It is now available as `Timex.DateFormat`.

**Comment by hitoridewanai** [comment]
Good stuff, thanks :)

**Comment by sheharyarn** [comment]
I've been going crazy over this for the last few hours. `DateFormat` worked when I did `use Timex`, but not when I did `Timex.DateFormat`, since I assumed that would be it. Anyways, thanks for this.
