### ISSUE TITLE
3.6.2 did not get a CHANGELOG update

### ISSUE THREAD

**Issue by hez** [bitwalker/timex#600]
### Description of issue

I was hoping to upgrade to the latest, but with the CHANGELOG missing it is complicated.

**Comment by tarpdalton** [comment]
It looks like a formatter ran through the code, so its hard to tell what is different between master and 3.6.1 https://github.com/bitwalker/timex/compare/3.6.1...master

**Comment by schnittchen** [comment]
Surprised to see there is no 3.6.2 tag

**Comment by bitwalker** [comment]
I've updated the changelog for 3.6.2 and .3
