### ISSUE TITLE
Parsing of second fractions

### ISSUE THREAD

**Issue by obrok** [bitwalker/timex#61]
ISO8601 allows for sub-second time amounts to appear after seconds, but trying to parse such a string results in an error:

```ruby
iex(3)> DateFormat.parse("2015-07-07T06:32:38.197894Z", "{ISO}")
{:error, "Input string does not match format!"}
```

Edit: this only happens when there's more than 3 digits in the sub-second part.

**Comment by bitwalker** [comment]
@obrok What would the representation of the sub-ms range be in `DateTime`? Right now `DateTime` only goes to millisecond precision (`Time` does microseconds). Should the value be truncated, rounded?

**Comment by obrok** [comment]
I think it should be rounded. There is some loss of precision, true, but that's probably still better than rejecting a valid input?

**Comment by bitwalker** [comment]
@obrok Yeah it's definitely incorrect to be restricting the precision, I'll change it to round to the nearest millisecond.

**Comment by bitwalker** [comment]
@obrok This is now fixed in master, I'll either push a new hex release today, or once I've got a few more things to push.

**Comment by obrok** [comment]
@bitwalker awesome, thanks!

**Comment by lang100** [comment]
@bitwalker  How can i get a DateTime with only 3 digits in the sub-second part?

**Comment by bitwalker** [comment]
@lang100 If you use `DateTime.new` you are able to do that, and you can achieve the same thing by setting the precision of the microseconds tuple to 3.

**Comment by lang100** [comment]
@bitwalker , thanks!
can you give an example of how to set precision of the microseconds tuple ??

**Comment by bitwalker** [comment]
@lang100 `%{datetime | :microsecond => {elem(datetime.microsecond, 0), 3}}` would do the trick.
