### ISSUE TITLE
Possible parse problem with %m :strftime

### ISSUE THREAD

**Issue by ewildgoose** [bitwalker/timex#62]
Hi, I see a possible bug in the strftime parser:

iex> DateFormat.parse("150623", "%y%m%d", :strftime)
{:error,
 "Invalid numeric value `62` for month. Outside of the allowed bounds: 1..12"}

iex> DateFormat.parse("151123", "%y%m%d", :strftime)
{:ok,
 %Timex.DateTime{calendar: :gregorian, day: 23, hour: 0, minute: 0, month: 11,
  ms: 0, second: 0,
  timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
   full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}}

I took a poke around the code, but I can't spot the issue? Seems like the leading 0 is getting stripped somewhere along the line, so the parser cuts an extra digit for %m

Thanks if you can take a look?

**Comment by bitwalker** [comment]
@ewildgoose Yeah that's a bug in the parser, I'll take a look tonight!

**Comment by bitwalker** [comment]
Released this fix in 0.16.1. Thanks for reporting it!
