### ISSUE TITLE
Able to create NaiveDateTime structs with Timex which are invalid dates.

### ISSUE THREAD

**Issue by Harper04** [bitwalker/timex#624]
### Steps to reproduce

```elixir
iex(13)> NaiveDateTime.utc_now |> Timex.add(Timex.Duration.from_hours(999_999_999))                                                  
~N[116100-04-17 06:50:18.734284]
iex(14)>  NaiveDateTime.new(116100,1,1,1,1,1)                                      
{:error, :invalid_date}
iex(15)> NaiveDateTime.utc_now |> Timex.add(Timex.Duration.from_hours(999_999_999)) |> NaiveDateTime.to_erl |> NaiveDateTime.from_erl
{:error, :invalid_date}
iex(16)> 
```
### Description of issue

- What are the expected results?
I would expect an error
I noticed this problem in production because Ecto was unable to parse a row from the Database because of invalid dates.
- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? 

The Documentation of NaiveDateTime states that `Developers should avoid creating the NaiveDateTime structs directly and instead, rely on the functions provided by this module as well as the ones in third-party calendar libraries.` Therefore i believe i should be able to serialize and deserialize every value i get from Timex.

**Comment by bitwalker** [comment]
Fixed locally, will be pushed shortly
