### ISSUE TITLE
Timex.equal? and other `boolean() | {:error, _}` return value funcs have a non-idiomatic interface

### ISSUE THREAD

**Issue by davidz627** [bitwalker/timex#629]
### Steps to reproduce

- API function called

https://hexdocs.pm/timex/Timex.html#equal?/3

Any other functions with return value of `boolean() | {:error, _}`

### Description of issue

The issue with these interfaces is that a statement like
```
if {:error, :not_found} do
   IO.puts "foo"
end
```

will go into the `if` block and print "foo". This manifests itself most often for me when exactly one of the arguments to `Timex.equal?` is `nil`: I would expect this to return `false` but it returns the error tuple instead. This is not the expected behavior when attempting to use a `?` type function with an expected boolean interface since you want it to only go into the block when your function returns `true`. Therefore the actual way you *have* to use these functions bug-free ends up being:

```
if true == Timex.equal?(a,b) do
   IO.puts "foo"
end
```

**NOTE:** The `true ==` part being the important part here.

Also note the [official naming conventions](https://hexdocs.pm/elixir/master/naming-conventions.html#trailing-question-mark-foo) state that `?` type functions must have a `boolean` type output so these functions are all unfortunately in violation of that convention.

**Comment by bitwalker** [comment]
Fixed by raising badarg if the arguments aren't valid date/time types
