### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by jschoch** [bitwalker/timex#64]
==> tzdata
Compiled lib/tzdata/parser_organizer.ex
Compiled lib/tzdata/release_parser.ex
Compiled lib/tzdata/util.ex
Compiled lib/tzdata/table_parser.ex
Compiled lib/tzdata/parser.ex
Compiled lib/tzdata/table_data.ex
Compiled lib/tzdata/leap_sec_parser.ex
Compiled lib/tzdata/basic_data.ex
Compiled lib/tzdata/period_builder.ex
Compiled lib/tzdata/far_future_dynamic_periods.ex
**Killed**

**Comment by bitwalker** [comment]
@jschoch Could you provide some more details? What version of Elixir/Erlang, and what OS are you building on? The builds are passing in Travis and locally, so I'll need some more detail in order to help troubleshoot.

/cc @lau

**Comment by jschoch** [comment]
https://github.com/lau/tzdata/issues/4#issuecomment-121946267

this is an AWS t2.micro so it is hitting the 2GB memory issue in the ticket above.

**Comment by bitwalker** [comment]
Ah that makes sense, sounds like @lau is working on a fix, so I'll keep this open until the next version of tzdata is released.

**Comment by bitwalker** [comment]
This should be fixed in master now.
