### ISSUE TITLE
Timex.now() |> Timex.shift(days: -1) does not give expected result

### ISSUE THREAD

**Issue by laurenfackler** [bitwalker/timex#643]
### Steps to reproduce

- Run `iex -S mix`
- Execute `Timex.now()`
- Execute `Timex.now() |> Timex.shift(days: -1)` and compare to output from `Timex.now()`

### Description of issue

- What are the expected results?
  - I would expect `Timex.now() |> Timex.shift(days: -1)` to be 1 day less than the output from `Timex.now`, e.g. `~U[2021-02-28 19:16:21.598034Z]`
  ![Screen Shot 2021-03-01 at 2 16 30 PM](https://user-images.githubusercontent.com/1793184/109547538-79fada00-7a99-11eb-9d11-3c1c519af910.png)

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite
  - In Ruby, I can do `now = DateTime.now` then `now - 1` and I get the expected result
  ![Screen Shot 2021-03-01 at 2 21 05 PM](https://user-images.githubusercontent.com/1793184/109547523-75cebc80-7a99-11eb-9d66-c888b6875175.png)

**Comment by bitwalker** [comment]
Fixed locally, will be pushed shortly
