### ISSUE TITLE
Timex.local/0 no longer returns a DateTime

### ISSUE THREAD

**Issue by ragamuf** [bitwalker/timex#644]
### Steps to reproduce
Upgrade from 3.6.2 to 3.7.0
%DateTime{} = Timex.local()

- API function called
Timex.local
- Arguments provided
none
### Description of issue
After upgrading to 3.7.0, Timex.local() is returning a TimezoneInfo as opposed to a DateTime.

- What are the expected results?
DateTime

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? 

I checked and Timex is correctly returning my timezone, just not the local datetime 
iex(16)> Application.get_env(:timex, :local_timezone)
"America/New_York"

**Comment by bitwalker** [comment]
Thanks for reporting, I'll get a release pushed ASAP

**Comment by bitwalker** [comment]
Fixed in 3.7.1
