### ISSUE TITLE
Cannot configure default_locale as described in the Changelog for 3.7.x

### ISSUE THREAD

**Issue by kaikuchn** [bitwalker/timex#648]
### Steps to reproduce

```
# Configure a default locale according to the Changelog
config :timex, Timex.Gettext, default_locale: "de"

# Start a shell and check the locale
> iex -S mix
iex(1)> Timex.Translator.current_locale()
"en"
```

### Description of issue

- I expected the current locale to be `de` as configured.
- It seems to work if I configure the default locale for Gettext instead: `config :gettext, default_locale: "de")`.

**Comment by bitwalker** [comment]
I should've reviewed the CHANGELOG entry from that PR a bit closer, it's a bit incorrect to say that Timex is responsible for this, you have a couple options:

# Global Locale

Set this via `:gettext` itself, e.g. `config :gettext, default_locale: "de"`. Timex will use this if no overriding configuration is present.

# Timex-specific Config

Set this via `config :your_app, Timex.Gettext, default_locale: "de"`. This sets the default specifically for Timex's backend. The key thing here is that you set this under `:your_app`, not `:timex`.

I'll push a fix to the CHANGELOG momentarily.
