### ISSUE TITLE
Possible bug with time zone conversion wrt daylight savings

### ISSUE THREAD

**Issue by dantswain** [bitwalker/timex#65]
I'm working on an application that needs to be able to convert epoch timestamps to dates in a standardized system time, which is US Central (don't ask... :rage1:).

On one of the remote boxes, using Ruby's `Time.at`, which I have used extensively and have no reason not to trust:

```
[3] pry(main)> t = Time.at(1394344799)
=> 2014-03-08 23:59:59 -0600
[4] pry(main)> Time.now
=> 2015-07-18 11:48:32 -0500
```

Note the difference from `now` and the date in question - one is daylight savings and one is not.

On my local box, which is in US Eastern, I can get the right answer in Ruby using `active_record/time`:

```
[16] pry(main)> require 'active_support/time'
=> true
[17] pry(main)> t = Time.at(1394344799)
=> 2014-03-09 00:59:59 -0500
[18] pry(main)> t.in_time_zone("America/Chicago")
=> Sat, 08 Mar 2014 23:59:59 CST -06:00
[19] pry(main)> t.utc
=> 2014-03-09 05:59:59 UTC
```

Using Timex on my local box:

```
iex(13)> t = Timex.Date.from(1394344799, :secs)
%Timex.DateTime{calendar: :gregorian, day: 9, hour: 5, minute: 59, month: 3,
 ms: 0, second: 59,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2014}
iex(14)> t |> Timex.Timezone.convert("America/Chicago")
%Timex.DateTime{calendar: :gregorian, day: 9, hour: 0, minute: 59, month: 3,
 ms: 0, second: 59,
 timezone: %Timex.TimezoneInfo{abbreviation: "CDT",
  from: {:sunday, {{2014, 3, 9}, {2, 0, 0}}}, full_name: "America/Chicago",
  offset_std: 60, offset_utc: -360,
  until: {:sunday, {{2014, 11, 2}, {1, 0, 0}}}}, year: 2014}
```

I get the same result on a box in the central timezone, actually.  `t |> Timex.Date.local` also gives the wrong answer on that box.

I say "possible bug" because maybe I'm not doing the conversion correctly?  Or it's possible that the Ruby code is wrong (but I don't _think_ so)?

**Comment by bitwalker** [comment]
@dantswain This was kind of a bug / kind of a naive approach to handling timezone conversions, there was no validation logic which checked whether the shift in time would put the date in a new timezone, and thus handling the shift across timezone boundaries properly. I've improved the way those conversions are done, and added tests for this specific case, but it should apply to any such shift across zone boundaries. Thanks for reporting!

**Comment by bitwalker** [comment]
I'll be pushing a new release to hex with this shortly by the way :)
