### ISSUE TITLE
Timex.to_datetime bug not default to UTC time.

### ISSUE THREAD

**Issue by andypho** [bitwalker/timex#651]
Timex.now("Japan") |> Timex.to_datetime()
Result:
#DateTime<2021-03-24 14:18:48.613352+09:00 JST Japan>

Expected result should be in UTC time, as mention in the doc
"Convert a date/time value to a DateTime. An optional timezone can be provided, UTC will be assumed if one is not provided."

**Comment by bitwalker** [comment]
You called to_datetime on a DateTime, so no change is made. If you did the same thing with a NaiveDateTime you would get a UTC DateTime as described. This is working as expected, but if you feel the docs should be clarified, I’m open to suggestions.

**Comment by andypho** [comment]
In version 3.6.1, when I call `Timex.now("Japan") |> Timex.to_datetime()` I will get back a UTC time.
However in 3.7.3 its no longer the case.
Unless you have mention it in the doc, or the changelog, I don't expect this to_datetime behaviour to be changed.

**Comment by bitwalker** [comment]
That definitely wasn’t intended behavior, but I apologize for any trouble it may have caused you. I make a point to avoid breaking changes, but in cases of unspecified behavior or bugs, breaking changes are sometimes made, and this is one such case. I will make a note to clarify the docs on this and add a note to the changelog.

**Comment by hadfieldn** [comment]
Just a note that we ran into this same issue, where we had old code that was depending on `Timex.to_datetime` to convert to UTC. It would be good to call this out in the changelog and explicitly state in the function doc that if a DateTime is passed as an argument, then the timezone parameter will be ignored. I would also state when the functionality changed, and reference `Timezone.convert/2` as the correct function to call to convert a DateTime to different timezone.

I might try to find some time to submit a PR for this, in case it would be helpful.
