### ISSUE TITLE
Timex.parse raises an exception

### ISSUE THREAD

**Issue by lumixmtb** [bitwalker/timex#652]
### Steps to reproduce

When trying to parse an invalid date with Timex.parse:

### with Timex 3.6.2
- Timex.parse("31.02.2020 00:15+0100", "{D}.{M}.{YYYY} {h24}:{m}{Z}")
- returns {:error, "invalid date"}

### with Timex 3.7.3
- Timex.parse("31.02.2020 00:15+0100", "{D}.{M}.{YYYY} {h24}:{m}{Z}")
- Raises an Exception (%ErlangError{original: :if_clause})

### Description of issue

- Is this a usual behaviour of Timex.parse?
- I would expect Timex.parse to return:  {:ok, DateTime.t() | NaiveDateTime.t()} | {:error, term()}

**Comment by bitwalker** [comment]
Thanks, I’ll take a look ASAP

**Comment by bitwalker** [comment]
I'll plan to get this out in a patch release today.
