### ISSUE TITLE
ArgumentError :time_zone_not_found with native DateTime function and tzdata DB

### ISSUE THREAD

**Issue by losvedir** [bitwalker/timex#664]
### Steps to reproduce

Environment:
* Elixir v1.10.3-otp-22
* Timex 3.7.5
* tzdata 1.1.0

Simple test case to reproduce:

```elixir
Calendar.put_time_zone_database(Tzdata.TimeZoneDatabase)
dt = Timex.parse!("2021-04-22T04:56:00-04:00", "{ISO:Extended}")
DateTime.add(dt, 10)

     ** (ArgumentError) cannot add 10 second to #DateTime<2021-04-22 04:56:00-04:00 -04 Etc/UTC-4> (with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
     code: assert DateTime.add(dt, 10)
     stacktrace:
       (elixir 1.10.3) lib/calendar/datetime.ex:1076: DateTime.add/4
       test/engine/scheduled_headways_test.exs:423: (test)
```

If I inspect the `Map.from_struct(dt)` I see:

```elixir
%{
  calendar: Calendar.ISO,
  day: 22,
  hour: 4,
  microsecond: {0, 0},
  minute: 56,
  month: 4,
  second: 0,
  std_offset: 0,
  time_zone: "Etc/UTC-4",
  utc_offset: -14400,
  year: 2021,
  zone_abbr: "-04"
}
```

It seems related to #645 but is still occurring on Timex 3.7.5. Unlike #663 there's no trailing whitespace on the time zone.

I believe the issue is that the time zone is parsed as `Etc/UTC-4`, which is not a valid timezone according to the `tzdata` DB that Timex brings in.

I'm aware that Timex has a `shift` function that does the same as my `DateTime.add` here, and that function does work, However, our large codebase with multiple developers has accrued a mix of Timex and native DateTime functions. I would expect that they should interoperate through the defined `DateTime.t()` interface and shared timezone database. 

Similarly, it looks like this is a problem only when using the `TzData.TimeZoneDatabase`. If I set it to `Timex.Timezone.Database` then the `DateTime.add/2` works.

So I guess the question is how interoperable Timex tries to be with the ecosystem. If you only support staying with "Timex land" and this is working as intended, feel free to close the issue, and we can work around it.

**Comment by losvedir** [comment]
Looking into this more, I think per [the docs](https://hexdocs.pm/elixir/1.11.4/Calendar.html#t:time_zone/0) an Elixir `Calendar.TimeZoneDatabase` is supposed to work with `Calendar.time_zone()` which is defined as:

> The time zone ID according to the IANA tz database (for example, Europe/Zurich)

Pulling up the latest IANA data, `Etc/UTC-4` is not a valid time zone ID, but `Etc/GMT-4` *is*, and in fact, if I update my datetime from above:

```ex
dt2 = %{dt | time_zone: "Etc/GMT-4"}
DateTime.add(dt2, 10)
# => works
```

then the native functions work with the `TzData.TimeZoneDatabase` again.

**Comment by bitwalker** [comment]
@losvedir The problem is the use of `Calendar.put_time_zone_database/1`, which overrides Timex's timezone database which understands an expanded set of timezones:

```elixir
# Without
iex> dt = Timex.parse!("2021-04-22T04:56:00-04:00", "{ISO:Extended}")
#DateTime<2021-04-22 04:56:00-04:00 -04 Etc/UTC-4>
...> DateTime.add(dt, 10)
#DateTime<2021-04-22 04:56:10-04:00 -04 Etc/UTC-4>

# With
iex> Calendar.put_time_zone_database(Tzdata.TimeZoneDatabase)
:ok
...> dt = Timex.parse!("2021-04-22T04:56:00-04:00", "{ISO:Extended}")
#DateTime<2021-04-22 04:56:00-04:00 -04 Etc/UTC-4>
...> DateTime.add(dt, 10)
** (ArgumentError) cannot add 10 second to #DateTime<2021-04-22 04:56:00-04:00 -04 Etc/UTC-4> (with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
    (elixir 1.12.1) lib/calendar/datetime.ex:1391: DateTime.add/4
```

If you use the following, you can use Timex's instead, which will do the correct thing (even with libraries not aware of Timex):

```elixir
iex(7)> Calendar.put_time_zone_database(Timex.Timezone.Database)
:ok
iex(8)> dt = Timex.parse!("2021-04-22T04:56:00-04:00", "{ISO:Extended}")
#DateTime<2021-04-22 04:56:00-04:00 -04 Etc/UTC-4>
iex(9)> DateTime.add(dt, 10)
#DateTime<2021-04-22 04:56:10-04:00 -04 Etc/UTC-4>
iex(10)>
```
