### ISSUE TITLE
Timex.Timezone.convert broken in 3.7

### ISSUE THREAD

**Issue by messutied** [bitwalker/timex#665]
### Steps to reproduce

- Timex.Timezone.convert/2
- NaiveDateTime.utc_now, "America/New_York"

### Description of issue

- What are the expected results? DateTime object should have NY time
- What's happening instead? DateTime remains in UTC time, only appends "America/New_York".

This started happening after I upgraded from 3.6, when switching back to 3.6 the problem is gone, do I have some wrong expectations here?

**Comment by bondarevts** [comment]
Just a bit more information about this issue:

Versions:
Erlang/OTP 23
Elixir 1.12.0

```elixir
# Timex 3.6.4
Timex.Timezone.convert(~N[2021-06-14 12:00:00], "America/New_York")
# #DateTime<2021-06-14 08:00:00-04:00 EDT America/New_York>
#                       ^ the function processed NaiveDateTime as if it was a UTC DateTime object

# Timex 3.7.5
Timex.Timezone.convert(~N[2021-06-14 12:00:00], "America/New_York")
# #DateTime<2021-06-14 12:00:00-04:00 EDT America/New_York>
#                       ^ convert just added a timezone information without changing time
```

This is related to the change in processing `NaiveDateTime` objects from [v.3.6.4][1] to [v.3.7.5][2]:
In 3.6.4 `NaiveDateTime` is not processed explicitly, it's transformed to a `DateTime` object with a call to `Timex.to_datetime(date)` which adds UTC time zone and then it's processed with an additional call to `convert` as a normal `DateTime` object
In 3.7.5 `NaiveDateTime` is processed explicitly and with a different operation 
```elixir
DateTime.from_naive(~N[2021-06-14 12:00:00], "America/New_York", Timex.Timezone.Database)
```
which just adds a timezone to a `NaiveDateTime` object.

@bitwalker could you please confirm which behavior is expected?

[1]: https://github.com/bitwalker/timex/blob/3.6.4/lib/timezone/timezone.ex#L537
[2]: https://github.com/bitwalker/timex/blob/3.7.5/lib/timezone/timezone.ex#L573

**Comment by bitwalker** [comment]
@bondarevts The behavior in 3.7.5 is the correct behavior. NaiveDateTimes cannot be assumed to belong to any particular timezone, so converting a NaiveDateTime to a timezone is equivalent to asserting that the NaiveDateTime was originally in that timezone. The behavior in 3.7.4 and previous was incorrect, and led to bugs in any situation in which the NaiveDateTime was _not_ originally in UTC.

If you want the original behavior, you can use the following approach: 

```elixir
naive |> Timex.Timezone.convert("UTC") |> Timex.Timezone.convert("America/New_York")
```
