### ISSUE TITLE
DateFormatter: Two digit month

### ISSUE THREAD

**Issue by stavro** [bitwalker/timex#67]
Would you be open to adding a `MM` format to the Date Formatter to print out the month as a two-digit value?

Currently these options exist:

```
  ### Months
  * `{M}`       - month number (1..12)
  * `{Mshort}`  - abbreviated month name (Jan..Dec, no padding)
  * `{Mfull}`   - full month name (January..December, no padding)
```

However, I need to have the month always take two digits.  (01 instead of 1).  - As you know this is quite common with formatting.

**Comment by bitwalker** [comment]
@stavro You can just do `{0M}` to accomplish padded two-digit months, this is mentioned in the documentation for the formatter, but it might not be clearly stated. If you have any suggestions on improving the docs, please let me know!
