### ISSUE TITLE
Compile warning when using gettext 0.20.0

### ISSUE THREAD

**Issue by ypconstante** [bitwalker/timex#718]
### Steps to reproduce

- Add timex 3.7.8 and gettext 0.20.0 to project dependencies
- run `mix deps.get && mix deps.compile`
- gettext will show a warning

### Description of issue

gettext deprecated the compiler on version 0.20.0, and [since timex adds gettext to compilers list](https://github.com/bitwalker/timex/blob/ed146eee9912e5f2fdbff71c308d3630fa67940a/mix.exs#L15), a warning will always be shown.

gettext compile change: https://github.com/elixir-gettext/gettext/commit/7dc9e4502e4323070c0ba1dbda504d0b829fb979?diff=split#diff-38ce6818891a446a1c2d89e7395759ce1c056424734593853cc8e0b714c39f32

**Comment by pecampelo** [comment]
I have been having the same issue, in the same versions you have reported:

`timex 3.7.8`
`gettext 0.20.0`

 It actually does not end compilation, and just hangs forever.

**Comment by bitwalker** [comment]
Fixed as of 3.7.11
