### ISSUE TITLE
ISO parser should allow omitting lower order time elements

### ISSUE THREAD

**Issue by colinbankier** [bitwalker/timex#75]
According to https://en.wikipedia.org/wiki/ISO_8601#Times it is acceptable to omit lower order time elements for reduced precision, e.g. [hh]:[mm], and [hh].

Timex currently does not allow this:
```
iex(10)> "2007-04-05T14:30Z" |> DateFormat.parse("{ISO}")
{:error, "Expected `:`, but found `Z` at line 1, column 17."}
```

**Comment by bitwalker** [comment]
This will be pushed in the next release of timex (sometime today probably).
