### ISSUE TITLE
DateTime.now and DateTime.local do not coincide

### ISSUE THREAD

**Issue by vans163** [bitwalker/timex#83]
I am in EDT timezone when I do:

Date.local
%Timex.DateTime{calendar: :gregorian, day: 3, hour: 11, minute: 33, month: 10,
 ms: 568, second: 51,
 timezone: %Timex.TimezoneInfo{abbreviation: "EDT",
  from: {:sunday, {{2015, 3, 8}, {2, 0, 0}}}, full_name: "America/New_York",
  offset_std: 60, offset_utc: -300,
  until: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}}, year: 2015}

Date.now("America/New_York")
%Timex.DateTime{calendar: :gregorian, day: 3, hour: 15, minute: 33, month: 10,
 ms: 714, second: 59,
 timezone: %Timex.TimezoneInfo{abbreviation: "EDT",
  from: {:sunday, {{2015, 3, 8}, {2, 0, 0}}}, full_name: "America/New_York",
  offset_std: 60, offset_utc: -300,
  until: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}}, year: 2015}

Date.now
%Timex.DateTime{calendar: :gregorian, day: 3, hour: 15, minute: 37, month: 10,
 ms: 782, second: 5,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}

Timex.Timezone.convert(Timex.Date.now, "America/New_York")
%Timex.DateTime{calendar: :gregorian, day: 3, hour: 11, minute: 39, month: 10,
 ms: 481, second: 50,
 timezone: %Timex.TimezoneInfo{abbreviation: "EDT",
  from: {:sunday, {{2015, 3, 8}, {2, 0, 0}}}, full_name: "America/New_York",
  offset_std: 60, offset_utc: -300,
  until: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}}, year: 2015}

As you can see they are off by 4 hours.  Why?  Im left at the conclusion its giving UTC time when you specify a Timezone.

**Comment by hassan** [comment]
I just hit this same problem (before finding this issue open). 

Here's a gist https://gist.github.com/hassan/c90e61dd8ce2b5cfd234 that demonstrates the issue and includes a failing test. 

I'd submit the test as a PR but not sure if it's appropriately colloquial Elixir  :-)

**Comment by bitwalker** [comment]
This is now fixed in master, I'll be pushing a new release to hex soon.
