### ISSUE TITLE
RFC: beginning_of_... and end_of_... helpers

### ISSUE THREAD

**Issue by krishandley** [bitwalker/timex#89]
Would you be interested in adding any of the following helper functions from active support?

* beginning_of_year
* beginning_of_month
* beginning_of_week
* beginning_of_day
* end_of_year
* end_of_month
* end_of_week
* end_of_day

Example from the ruby world
http://apidock.com/rails/ActiveSupport/CoreExtensions/Date/Calculations/beginning_of_week

I was making a calendar and needed to get the beginning and end of the month, and week. I have written some code for this because I've been trying to learn Elixir, but opening an issue to get your thoughts.

**Comment by bitwalker** [comment]
I'm open to adding these helpers, however let's break it up into multiple PRs and start with `beginning_of/end_of_year`. It'll be easier to review + merge, and the complexity increases as the timespan becomes more granular. Sound good?

**Comment by krishandley** [comment]
Great, sounds good to me :)

**Comment by krishandley** [comment]
Many thanks for accepting the helpers and a few elixir tips along the way :smile:

**Comment by bitwalker** [comment]
No problem! Thanks for the contributions!
