### ISSUE TITLE
Timex 0.17.0 isn't compatible with Elixir 1.1.0

### ISSUE THREAD

**Issue by meadsteve** [bitwalker/timex#90]
Hi not sure if this has already been tackled but I'm building against 0.17.0 of timex and 1.1.0 of elixir and I get this error:
```
== Compilation error on file lib/date/datetime.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Timex.DateTime
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:591: Protocol.derive/5
    (stdlib) lists.erl:1336: :lists.foreach/2
    (elixir) lib/protocol.ex:579: Protocol.__derive__/3
    lib/date/datetime.ex:6: (module)
```

**Comment by bitwalker** [comment]
@meadsteve If you want to use timex with Elixir 1.1.0, you should use `0.19.5` or `1.0.0-pre`, 0.17.0 still uses the deprecated `Access` protocol because it predates Elixir 1.1.0. There have also been many fixes in the releases since. Is there some reason you can't update?

**Comment by meadsteve** [comment]
@bitwalker thanks. This was caused by me being tired and silly and using a version number I took from the docs for some reason. I can absolutely use 0.19.5

**Comment by bitwalker** [comment]
@meadsteve I would recommend using 1.0.0-pre if you can, it is API compatible with 0.19.x and there are already a few bug fixes there that you may want.
