### ISSUE TITLE
Performance degradation of Date.local compared with older version of timex

### ISSUE THREAD

**Issue by akira** [bitwalker/timex#92]
There is a major performance degradation of date.local compared with older versions of timex.

On the older version, for example version 0.13.5, Date.local on my laptop:

```
date.local                       1000000   3.11 µs/op
```

versus latest stable release, 0.19.5:
```
date.local                         10000   135.24 µs/op
```

Using this for benchmarking:
```elixir
  bench "format date.local" do
    _ = Date.local
    :ok
  end
```

**Comment by bitwalker** [comment]
@akira I'd like to point out that this is not a "major" performance degradation. An increase of ~130 microseconds, or ~0.1 milliseconds, while significant relative to the old value, is still very performant considering that `Date.local` does lookups against the filesystem, reads and parses a binary file, and then does an internal lookup for the timezone metadata in the Olson database based on the date, and validates it, that's about as good as it can get without some rather intense micro-optimizations. The old version of Timex that you are referencing was doing roughly half the work, and was not accurate when it came to timezone information. So while it is slower today, it's certainly a worthy tradeoff, and is also minuscule enough to not be of concern in my opinion.

That said however, if you can give me a good use case where this thinking is flawed, I can either suggest an alternative, or look deeper into how I can improve performance of this function. In general, you should be avoiding `Date.local` in any kind of tight loop. The zoneinfo file parsing result is cached, but every time you lookup timezone information for a date, the Olson database has to be consulted to verify that the date is valid for that zone. However there are ways to construct dates without needing to do those lookups if some assumptions hold true, but I'd need to know more about the specific use case to give you guidance or to make appropriate changes to timex itself.

**Comment by akira** [comment]
I see - the use case is for exq, which is a sidekiq/resque type queueing library. We use Timex when we serialize our jobs to JSON as they are enqueued:

https://github.com/akira/exq/blob/master/lib/exq/redis/job_queue.ex#L124

Let me know your thoughts regarding this specific use case.  Thanks!

**Comment by bitwalker** [comment]
@akira Is there any particular reason you use `Date.local` there instead of `Date.universal`? In general you should avoid using local time for anything that isn't user facing, particularly since you might have your application split across geographic areas where the local timezone is different. Within Timex, constructing a date in UTC is much much faster.

**Comment by akira** [comment]
@bitwalker good call, I can use Date.universal. 

After making that switch, I still performance degradations with Date.format! versus previous versions:

0.19.5:
```
(strftime) tokenize ISO 8601               5000   305.00 µs/op
(strftime) format ISO 8601 datetime        5000   408.99 µs/op
(default) format ISO 8601 datetime         5000   624.78 µs/op
(strftime) parse ISO 8601 datetime         2000   667.46 µs/op
(default) parse ISO 8601 datetime          5000   676.52 µs/op
(default) tokenize ISO 8601                2000   823.01 µs/op
```
versus 0.13.5:
```
(default) format ISO 8601 datetime        20000   96.47 µs/op
(default) parse ISO 8601 datetime         10000   199.60 µs/op
(strftime) format ISO 8601 datetime       10000   215.05 µs/op
(strftime) parse ISO 8601 datetime         5000   342.47 µs/op
```

Does that seem right? I can't seem to run the benchmark multiple times on 0.19.5, as it fails on subsequent runs, but from the above it seems like there's a slowdown from previous version.

**Comment by bitwalker** [comment]
@akira Yes the formatters/parsers were rewritten because of a few issues in my original handwritten ones that were difficult to resolve without significant changes. I made the tradeoff of using parser combinators in the new parsers instead of handwriting them again for a few reasons:

1. The new formatters/parsers are significantly easier to maintain and extend, for myself, potential contributors, and in your own projects.
2. A number of bugs in both formatting and parsing were fixed as a result due to edge cases in the original implementation.
3. The parser is now much more helpful when errors occur.

However, the tradeoff comes at the cost of increased overhead, and thus the performance degradation. Since formatting and parsing was still sub-millisecond, I felt it was a worthy tradeoff.

I'll do some profiling and see if there is some opportunity for improvement here, perhaps I can bring the numbers down. As a performance tip in the meantime though, the more specific you are with your formatting directives, the faster the parser will be. If you use the `{ISO}` token, it is handling all the edge cases of ISO 8601, which is expensive. If you know the precise format your datetime strings will be received in, then you can gain some time back by specifying that exact format, i.e. `{YYYY}-{M}-{D}T{h24}:{m}:{s}{Z}` for a typical ISO-8601 datetime string.

**Comment by bitwalker** [comment]
@akira I've pushed some pretty significant performance improvements to `combine` in version 0.5.3, the parser combinator library used in `timex`. You'll have to update that dependency, but if you do, the following benchmark results show the before and after when running `mix bench -d 2`:

```
Before:

Finished in 37.43 seconds

## Timex.DateFormat.Bench
Date.local                                20000   189.30 µs/op
(strftime) tokenize ISO 8601              10000   274.54 µs/op
(strftime) format ISO 8601 datetime       10000   411.02 µs/op
(default) format ISO 8601 datetime        10000   566.09 µs/op
(default) tokenize ISO 8601                5000   741.09 µs/op
(strftime) parse ISO 8601 datetime         5000   1004.36 µs/op
(default) parse ISO 8601 datetime          5000   1145.74 µs/op

After:

Finished in 31.63 seconds

## Timex.DateFormat.Bench
Date.local                                20000   190.03 µs/op
(strftime) tokenize ISO 8601              10000   257.33 µs/op
(strftime) format ISO 8601 datetime       10000   319.37 µs/op
(default) format ISO 8601 datetime        10000   484.78 µs/op
(strftime) parse ISO 8601 datetime        10000   550.00 µs/op
(default) parse ISO 8601 datetime          5000   612.15 µs/op
(default) tokenize ISO 8601                5000   665.06 µs/op
```

My laptop isn't all that powerful, so the numbers on a beefier machine would probably be quite a bit better, but who knows without actually testing. Anyway, give it a shot and let me know how it works out for you.

**Comment by akira** [comment]
Thanks!  I will check it out when I get a chance and will let you know.

**Comment by akira** [comment]
@bitwalker I'm not seeing same results.  Which versions are you comparing? 


Using the same benchmark:

0.19.5:

```
Date.local                                50000   124.13 µs/op
(strftime) tokenize ISO 8601              10000   291.04 µs/op
(strftime) format ISO 8601 datetime       10000   357.44 µs/op
(strftime) parse ISO 8601 datetime        10000   521.77 µs/op
(default) format ISO 8601 datetime        10000   531.40 µs/op
(default) parse ISO 8601 datetime         10000   585.52 µs/op
(default) tokenize ISO 8601                5000   659.58 µs/op
```

Latest master branch of timex with master branch of combine
```
Date.local                                50000   125.33 µs/op
(strftime) tokenize ISO 8601              10000   288.53 µs/op
(strftime) format ISO 8601 datetime       10000   352.40 µs/op
(strftime) parse ISO 8601 datetime        10000   519.36 µs/op
(default) format ISO 8601 datetime         5000   632.67 µs/op
(default) parse ISO 8601 datetime          5000   636.76 µs/op
(default) tokenize ISO 8601                5000   647.30 µs/op
```

**Comment by lau** [comment]
@akira I would recommend never using the local time of the server for anything. Use UTC instead. Besides being faster, it is more simple and you avoid certain bugs.

**Comment by akira** [comment]
@lau Thanks! I was planning on switching that over to use UTC and will do that.  I think the primary issue I was seeing was with the date formatting which is done as well during the serialization process. 

In general I just wanted to bring this different between the version up in case no one was aware, but sounds like this was more of a tradeoff in the design which is fine.  Anyways, I'll keep an eye on any future updates and investigate some optimizations as well.

**Comment by bitwalker** [comment]
@akira I'll continue looking into improvements within combine. If you have any specific optimization suggestions, I'm glad to take a look. One thing that's being worked on right now is splitting the implementation of the ISO-8601 parser into two parsers, Basic and Extended, which can be strict within their subset of the spec, and therefore skip a lot of alternation steps which slow the parsing down. I'm hoping to have those merged soon (the old `{ISO}` and `{ISOz}` tokens will still exist for backwards-compatibility)

**Comment by bitwalker** [comment]
I think things are about as they can be for now. At some point in the future I may hand optimize some of the more complex parsers. If anyone has any particular suggestions or a PR, open an issue and I'll gladly look into it.
