### ISSUE TITLE
Wrong timezone name

### ISSUE THREAD

**Issue by JustMikey** [bitwalker/timex#94]
I may be wrong or not understand something, but quick googling says that there is no `Katmandu` but only `Kathmandu`, so maybe `Asia/Katmandu` should be renamed to `Asia/Kathmandu` ?

**Comment by bitwalker** [comment]
Both `Asia/Kathmandu` and `Asia/Katmandu` exist in the Olson timezone database, so this is valid. I'm not sure why both are there, but I'm guessing it's a historical change.
