### ISSUE TITLE
Sorting bug (or misunderstanding)

### ISSUE THREAD

**Issue by henrik** [bitwalker/timex#97]
Docs say:

> You can diff two dates, compare them for sorting, and more.

But I see this unexpected behaviour:

``` elixir
iex(47)> date_2001_sec_1 = Timex.Date.from({{2001, 1, 1}, {0, 0, 1}})
%Timex.DateTime{calendar: :gregorian, day: 1, hour: 0, minute: 0, month: 1,
 ms: 0, second: 1,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2001}

iex(48)> date_2000_sec_1 = Timex.Date.from({{2000, 1, 1}, {0, 0, 1}})
%Timex.DateTime{calendar: :gregorian, day: 1, hour: 0, minute: 0, month: 1,
 ms: 0, second: 1,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2000}

iex(49)> date_2000_sec_2 = Timex.Date.from({{2000, 1, 1}, {0, 0, 2}})
%Timex.DateTime{calendar: :gregorian, day: 1, hour: 0, minute: 0, month: 1,
 ms: 0, second: 2,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min,
  full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2000}

iex(50)> date_2001_sec_1 > date_2000_sec_2
false
iex(51)> date_2001_sec_1 > date_2000_sec_1
true
```

So the datetime that is 1 year later is not considered greater… unless seconds match.

Are `DateTime` structs meant to be comparable like this? Am I misunderstanding something, or is this a bug?

**Comment by henrik** [comment]
…and now I found https://hexdocs.pm/timex/Timex.Date.html#compare/2 :D I'll make a PR to clarify the docs.

**Comment by henrik** [comment]
Or not – not sure how I'd clarify that without getting into perhaps too much detail.

**Comment by bitwalker** [comment]
@henrik Yeah I see where the confusion comes from, in Elixir/Erlang there is no way to override the comparison operators, so comparing two structs is going to boil down to however Erlang compares maps by default. So any time we need to do custom comparison we have to provide our own `compare/2` function. If you have thoughts on how to best express that in the docs, I'd gladly merge a PR or make the change myself.

**Comment by henrik** [comment]
Hm. Maybe just linking "compare them" to the docs, and similarly for "diff two dates"? Would have helped me at least.

If you agree, feel free to change it yourself.
